#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  PROVA PG17 — 20260906170000_reposicao_selo_aprovacao_m1_expandir.sql          ║
# ║  Selo de aprovação (M1 "expandir"): reposicao_selar_pedido VALIDA e sela;      ║
# ║  snapshot do de-para no item; hash estável em SQL; conferência pré-Browserless ║
# ║  (o de-para muda SEM mudar o selo); token de revisão; cancelar recusa envio em  ║
# ║  voo; claims recusam recusa durável; split sela os filhos.                      ║
# ║  Rode: bash db/test-reposicao-selo-aprovacao.sh > /tmp/t.log 2>&1; echo $?      ║
# ║  NAO reprova o TOCTOU de aprovar/cancelar: isso ja e provado com DUAS sessoes   ║
# ║  por db/test-aprovar-pedido-guard.sh e db/test-cancelar-pedido-guard-atomico.sh ║
# ║  (na main). Aqui o FOR UPDATE e ADITIVO — ele existe porque o selo precisa do    ║
# ║  lock segurado ATRAVES de varias instrucoes, nao so no instante da escrita.      ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PGVER=17
PGBIN="/opt/homebrew/opt/postgresql@${PGVER}/bin"
PORT="${PGPORT_TEST:-5479}"
SLUG="selo-aprovacao"
SAB=""   # o trap de cleanup referencia $SAB; sob set -u ele explodiria antes da ZONA 4
DATA="$(mktemp -d "/tmp/pgtest-${SLUG}.XXXXXX")/data"
export LC_ALL=C LANG=C

[ -x "$PGBIN/initdb" ] || { echo "postgresql@${PGVER} ausente: brew install postgresql@${PGVER} pgvector"; exit 1; }
CELLAR="$(brew --prefix "postgresql@${PGVER}")"
cp -Rn "$CELLAR"/share/postgresql/. "/opt/homebrew/share/postgresql@${PGVER}/" 2>/dev/null || true
mkdir -p "/opt/homebrew/lib/postgresql@${PGVER}"
cp -Rn "$CELLAR"/lib/postgresql/. "/opt/homebrew/lib/postgresql@${PGVER}/" 2>/dev/null || true

cleanup() { "$PGBIN/pg_ctl" -D "$DATA" stop -m immediate >/dev/null 2>&1 || true; rm -rf "$(dirname "$DATA")"; rm -f "$SAB" 2>/dev/null || true; }
trap cleanup EXIT

"$PGBIN/initdb" -D "$DATA" -U postgres -E UTF8 --locale=C >/dev/null
"$PGBIN/pg_ctl" -D "$DATA" -o "-p $PORT -k /tmp" -l "/tmp/pg-${SLUG}.log" -w start >/dev/null
"$PGBIN/createdb" -p "$PORT" -h /tmp -U postgres prove
P()  { "$PGBIN/psql" -p "$PORT" -h /tmp -U postgres -d prove -v ON_ERROR_STOP=1 "$@"; }
Pq() { P -tA "$@"; }

P -q -f "$REPO_ROOT/db/stubs-supabase.sql"
P -q <<'SQL'
CREATE OR REPLACE FUNCTION auth.uid()  RETURNS uuid LANGUAGE sql STABLE AS $f$ SELECT nullif(current_setting('test.uid',  true), '')::uuid $f$;
CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $f$ SELECT nullif(current_setting('test.role', true), '') $f$;
ALTER ROLE service_role BYPASSRLS;
SQL

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  OK  $1"; }
bad() { FAIL=$((FAIL+1)); echo "  FAIL $1"; }
eq()  { if [ "$2" = "$3" ]; then ok "$1 (=$2)"; else bad "$1 - esperado [$3], veio [$2]"; fi; }

echo "=== setup pronto (PG17 :$PORT) ==="

# ══════════ ZONA 1 — pré-requisitos (o que a migration LÊ mas não cria) ══════════
P -q <<'SQL'
CREATE SCHEMA IF NOT EXISTS private;
DO $$ BEGIN CREATE TYPE public.app_role AS ENUM ('employee','customer','master'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.user_roles (user_id uuid NOT NULL, role public.app_role NOT NULL);
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER AS $f$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $f$;
CREATE TABLE IF NOT EXISTS private.cap_compras (uid uuid PRIMARY KEY);
CREATE OR REPLACE FUNCTION private.cap_compras_ler(_uid uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER AS $f$ SELECT EXISTS (SELECT 1 FROM private.cap_compras WHERE uid=_uid) $f$;

CREATE TABLE IF NOT EXISTS public.pedido_compra_sugerido (
  -- IDENTITY (nao `bigint` pelado): em prod a coluna tem sequencia, e o pedido_compra_split
  -- insere o FILHO sem informar id. Um stub sem default reprova a migration por um defeito do
  -- STUB — o teste tem de ser fiel no eixo que ele mede. START alto para nao colidir com os
  -- ids explicitos do seed (100..1000).
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 900000) PRIMARY KEY,
  empresa text NOT NULL,
  fornecedor_nome text NOT NULL,
  grupo_codigo text, data_ciclo date,
  horario_geracao timestamptz, horario_corte_planejado timestamptz, horario_disparo_real timestamptz,
  valor_total numeric DEFAULT 0, num_skus integer DEFAULT 0,
  status text NOT NULL DEFAULT 'pendente_aprovacao',
  status_envio_portal text NOT NULL DEFAULT 'nao_aplicavel',
  portal_tentativas integer DEFAULT 0, portal_protocolo text, portal_erro text, portal_proximo_retry_em timestamptz,
  condicao_pagamento_codigo text, condicao_pagamento_descricao text,
  num_parcelas integer, dias_parcelas text, condicao_origem text,
  aprovado_em timestamptz, aprovado_por text,
  cancelado_em timestamptz, cancelado_por text, justificativa_cancelamento text,
  criado_em timestamptz DEFAULT now(), atualizado_em timestamptz DEFAULT now(),
  split_parent_id bigint, split_lote integer, split_total integer
);
CREATE TABLE IF NOT EXISTS public.pedido_compra_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 900000) PRIMARY KEY,
  pedido_id bigint NOT NULL REFERENCES public.pedido_compra_sugerido(id) ON DELETE CASCADE,
  sku_codigo_omie text NOT NULL, sku_descricao text,
  qtde_sugerida numeric NOT NULL DEFAULT 0, qtde_final numeric,
  preco_unitario numeric, valor_linha numeric,
  fator_embalagem_portal numeric
);
CREATE TABLE IF NOT EXISTS public.sku_fornecedor_externo (
  id bigserial PRIMARY KEY,
  empresa text NOT NULL, fornecedor_nome text NOT NULL, sku_omie text NOT NULL,
  sku_portal text, unidade_portal text DEFAULT 'UN' NOT NULL,
  fator_conversao numeric DEFAULT 1 NOT NULL, ativo boolean DEFAULT true NOT NULL
);
INSERT INTO private.cap_compras(uid) VALUES ('11111111-1111-1111-1111-111111111111') ON CONFLICT DO NOTHING;
SQL

# ══════════ ZONA 2 — aplicar a migration REAL ══════════
MIG="$REPO_ROOT/supabase/migrations/20260906170000_reposicao_selo_aprovacao_m1_expandir.sql"
P -q -f "$MIG"
echo "migration aplicada: $(basename "$MIG")"

# ══════════ ZONA 3 — seed re-semeável ══════════
# 100 portal OK (fator 0,2 · 40 L = 8 baldes) · 200 portal sem de-para · 300 portal ambiguo
# 400 portal fator do motor != vivo · 500 nao-portal · 600 fracao · 700 nao-multiplo · 800 NaN
# 900 portal com 5 itens (split)
seed() {
P -q <<'SQL'
TRUNCATE public.pedido_compra_item, public.pedido_compra_sugerido, public.sku_fornecedor_externo RESTART IDENTITY CASCADE;
INSERT INTO public.pedido_compra_sugerido (id, empresa, fornecedor_nome, status) VALUES
  (100,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (200,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (300,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (400,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (500,'OBEN','OUTRO FORNECEDOR LTDA','pendente_aprovacao'),
  (600,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (700,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (800,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (900,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao'),
  (1000,'OBEN','RENNER SAYERLACK S/A','pendente_aprovacao');
INSERT INTO public.pedido_compra_item (id, pedido_id, sku_codigo_omie, qtde_final, qtde_sugerida, preco_unitario, fator_embalagem_portal) VALUES
  (101,100,'TEH.3505.00BB',40,36,10,0.2),
  (102,100,'FOA05',3,3,20,NULL),
  (201,200,'SEM.DEPARA',5,5,10,NULL),
  (301,300,'AMBIGUO',5,5,10,NULL),
  (401,400,'TEH.3505.00BB',40,36,10,0.2),
  (501,500,'QUALQUER',7,7,10,NULL),
  (601,600,'FOA05',3.5,3.5,10,NULL),
  (701,700,'TEH.3505.00BB',41,41,10,0.2),
  (801,800,'FOA05','NaN',1,10,NULL),
  (901,900,'A1',1,1,10,NULL),(902,900,'A2',1,1,10,NULL),(903,900,'A3',1,1,10,NULL),
  (904,900,'A4',1,1,10,NULL),(905,900,'A5',1,1,10,NULL),
  -- P1-2: o motor NAO arredondou (fator NULL) mas o de-para vivo e 0,2 — 41 L nao e multiplo.
  -- Em prod ha 16 itens desta classe; a checagem antiga, gateada por fator_embalagem_portal,
  -- era cega a eles.
  (1001,1000,'TEH.3505.00BB',41,41,10,NULL);
INSERT INTO public.sku_fornecedor_externo (empresa, fornecedor_nome, sku_omie, sku_portal, fator_conversao, ativo) VALUES
  ('OBEN','RENNER SAYERLACK S/A','TEH.3505.00BB','TEH350500BB',0.2,true),
  ('OBEN','RENNER SAYERLACK S/A','FOA05','FOA05P',1,true),
  ('OBEN','RENNER SAYERLACK S/A','AMBIGUO','X1',1,true),
  ('OBEN','RENNER SAYERLACK S/A','A1','A1P',1,true),('OBEN','RENNER SAYERLACK S/A','A2','A2P',1,true),
  ('OBEN','RENNER SAYERLACK S/A','A3','A3P',1,true),('OBEN','RENNER SAYERLACK S/A','A4','A4P',1,true),
  ('OBEN','RENNER SAYERLACK S/A','A5','A5P',1,true);
UPDATE public.sku_fornecedor_externo SET fator_conversao=0.18 WHERE sku_omie='TEH.3505.00BB' AND EXISTS (SELECT 1 FROM public.pedido_compra_item WHERE id=401 AND false);
SQL
}
seed

# aprova() ecoa o jsonb da RPC; falha_sqlstate() ecoa a SQLSTATE de reposicao_selar_pedido
aprova()      { Pq -c "SELECT public.aprovar_pedido_sugerido($1,'comprador@x', $2)"; }
aprova2args() { Pq -c "SELECT public.aprovar_pedido_sugerido($1,'comprador@x')"; }
selo()        { Pq -c "SELECT COALESCE(aprovacao_selo,'NULO') FROM public.pedido_compra_sugerido WHERE id=$1"; }
status()      { Pq -c "SELECT status FROM public.pedido_compra_sugerido WHERE id=$1"; }
snap()        { Pq -c "SELECT COALESCE(sku_portal_aprovado,'NULO')||'/'||COALESCE(trim_scale(fator_portal_aprovado)::text,'NULO') FROM public.pedido_compra_item WHERE id=$1"; }
# assert negativo por SQLSTATE EXATA: captura a esperada, RE-LANÇA o resto.
sqlstate_de() {
  Pq <<SQL
DO \$t\$ BEGIN
  PERFORM public.reposicao_selar_pedido($1);
  RAISE NOTICE 'SEM_ERRO';
EXCEPTION WHEN SQLSTATE '$2' THEN RAISE NOTICE 'MARCA_OK';
END \$t\$;
SQL
}
marca() { P -c "DO \$t\$ BEGIN PERFORM public.reposicao_selar_pedido($1); RAISE WARNING 'SEM_ERRO'; EXCEPTION WHEN SQLSTATE '$2' THEN RAISE WARNING 'MARCA_OK'; END \$t\$;" 2>&1 | grep -oE 'SEM_ERRO|MARCA_OK' | head -1; }

echo "--- POSITIVOS ---"
R=$(aprova 100 "'[{\"id\":101,\"sku_codigo_omie\":\"TEH.3505.00BB\",\"qtde_final\":40,\"fator_embalagem_portal\":0.2},{\"id\":102,\"sku_codigo_omie\":\"FOA05\",\"qtde_final\":3,\"fator_embalagem_portal\":null}]'::jsonb")
case "$R" in *'"status": "ok"'*) ok "P1 RPC 3-args com token correto aprova";; *) bad "P1 RPC 3-args recusou: $R";; esac
eq  "P2 selou (selo tem 64 hex)" "$(Pq -c "SELECT length(aprovacao_selo) FROM public.pedido_compra_sugerido WHERE id=100")" "64"
eq  "P3 snapshot do de-para gravado no item"  "$(snap 101)" "TEH350500BB/0.2"
eq  "P4 snapshot tambem no item de fator 1"   "$(snap 102)" "FOA05P/1"
eq  "P5 status virou aprovado"                "$(status 100)" "aprovado_aguardando_disparo"
eq  "P6 selo e ESTAVEL (recomputar da o mesmo)" "$(Pq -c "SELECT (public.reposicao_selo_itens(100) = aprovacao_selo)::text FROM public.pedido_compra_sugerido WHERE id=100")" "true"
eq  "P7 conferir_envio: tudo ok"              "$(Pq -c "SELECT selo_ok::text||'/'||depara_ok::text||'/'||COALESCE(motivo,'-') FROM public.reposicao_conferir_envio(100)")" "true/true/-"
seed
R=$(aprova2args 500); case "$R" in *'"status": "ok"'*) ok "P8 wrapper 2-args aprova pedido NAO-portal";; *) bad "P8 wrapper recusou: $R";; esac
eq  "P9 nao-portal nao exige de-para (sem snapshot)" "$(snap 501)" "NULO/NULO"
eq  "P10 nao-portal mesmo assim SELA"          "$(Pq -c "SELECT length(aprovacao_selo) FROM public.pedido_compra_sugerido WHERE id=500")" "64"
seed
R=$(aprova2args 100); case "$R" in *'"status": "ok"'*) ok "P11 wrapper 2-args (UI velha) tambem sela portal";; *) bad "P11 wrapper recusou: $R";; esac
S12=$(Pq -c "SELECT public.reposicao_selo_itens(100)")
P -q -c "UPDATE public.pedido_compra_item SET fator_portal_aprovado=0.200 WHERE id=101"
eq  "P12 0,200 e 0,2 dao o MESMO selo (trim_scale)" "$(Pq -c "SELECT public.reposicao_selo_itens(100)")" "$S12"
P -q -c "UPDATE public.pedido_compra_item SET qtde_final=41 WHERE id=101"
if [ "$(Pq -c "SELECT public.reposicao_selo_itens(100)")" != "$S12" ]; then ok "P13 mudar a QUANTIDADE muda o selo (o hash tem dente)"; else bad "P13 o selo nao reagiu a mudanca de quantidade"; fi

echo "--- NEGATIVOS (SQLSTATE exata) ---"
seed
eq "N1 sem de-para utilizavel -> SA006"        "$(marca 200 SA006)" "MARCA_OK"
# SA003 ficou INALCANCAVEL enquanto o UNIQUE parcial existir — e esse e o ponto do P1-5: a
# unicidade virou invariante da TABELA, nao conclusao de query. O ramo continua no codigo como
# fail-closed para o dia em que o indice cair, e e assim que se prova que ele tem dente.
P -q -c "DROP INDEX public.ux_sku_fornecedor_externo_ativo"
P -q -c "INSERT INTO public.sku_fornecedor_externo (empresa,fornecedor_nome,sku_omie,sku_portal,fator_conversao,ativo) VALUES ('OBEN','RENNER SAYERLACK S/A','AMBIGUO','X2',1,true)"
eq "N2 sem o indice, de-para ambiguo -> SA003 (o ramo fail-closed tem dente)" "$(marca 300 SA003)" "MARCA_OK"
P -q -c "DELETE FROM public.sku_fornecedor_externo WHERE sku_portal='X2'"
P -q -c "CREATE UNIQUE INDEX ux_sku_fornecedor_externo_ativo ON public.sku_fornecedor_externo (empresa, fornecedor_nome, sku_omie) WHERE ativo"
eq "N3 quantidade fracionaria (portal) -> SA005"        "$(marca 600 SA005)" "MARCA_OK"
# N3b existe para ISOLAR a camada de inteireza. No pedido de PORTAL a fracao e pega por DUAS
# camadas independentes (inteireza e round-trip pelo snapshot), e sabotar so uma nao prova nada
# — foi o que a falsificacao F1 acusou. Pedido NAO-portal nao ganha snapshot, entao ali a
# inteireza e a UNICA camada e a sabotagem tem onde morder.
P -q -c "UPDATE public.pedido_compra_item SET qtde_final=7.5 WHERE id=501"
eq "N3b fracao em pedido NAO-portal -> SA005 (camada de inteireza sozinha)" "$(marca 500 SA005)" "MARCA_OK"
eq "N4 quantidade NaN -> SA005"                "$(marca 800 SA005)" "MARCA_OK"
eq "N5 nao-multiplo da embalagem -> SA005"     "$(marca 700 SA005)" "MARCA_OK"
P -q -c "UPDATE public.sku_fornecedor_externo SET fator_conversao=0.18 WHERE sku_omie='TEH.3505.00BB'"
eq "N6 fator do motor != fator vivo -> SA004"  "$(marca 400 SA004)" "MARCA_OK"
seed
eq "N7 recusa NAO deixa rastro: status intacto" "$(status 600)" "pendente_aprovacao"
R=$(aprova 600 "NULL::jsonb"); case "$R" in *'"error"'*) ok "N8 RPC devolve {error} (contrato do front) na fracao";; *) bad "N8 RPC nao devolveu error: $R";; esac
eq "N9 recusa nao selou"                       "$(selo 600)" "NULO"
eq "N10 recusa nao aprovou"                    "$(status 600)" "pendente_aprovacao"
R=$(aprova 100 "'[{\"id\":101,\"sku_codigo_omie\":\"TEH.3505.00BB\",\"qtde_final\":45,\"fator_embalagem_portal\":0.2},{\"id\":102,\"sku_codigo_omie\":\"FOA05\",\"qtde_final\":3,\"fator_embalagem_portal\":null}]'::jsonb")
case "$R" in *'mudaram desde'*) ok "N11 token com qtde divergente -> recarregue";; *) bad "N11 token divergente passou: $R";; esac
eq "N12 token divergente nao selou"            "$(selo 100)" "NULO"
R=$(aprova 100 "'[{\"id\":101,\"sku_codigo_omie\":\"OUTRO.SKU\",\"qtde_final\":40,\"fator_embalagem_portal\":0.2},{\"id\":102,\"sku_codigo_omie\":\"FOA05\",\"qtde_final\":3,\"fator_embalagem_portal\":null}]'::jsonb")
case "$R" in *'mudaram desde'*) ok "N13 token com SKU trocado (mesma qtde) -> recarregue";; *) bad "N13 SKU trocado passou: $R";; esac
R=$(aprova 100 "'[{\"id\":101,\"sku_codigo_omie\":\"TEH.3505.00BB\",\"qtde_final\":40,\"fator_embalagem_portal\":0.2}]'::jsonb")
case "$R" in *'mudaram desde'*) ok "N14 token com item FALTANDO -> recarregue";; *) bad "N14 conjunto menor passou: $R";; esac
P -q -c "SET test.uid='99999999-9999-9999-9999-999999999999'" >/dev/null
R=$(P -c "SET test.uid='99999999-9999-9999-9999-999999999999'; SELECT public.reposicao_selar_pedido(100);" 2>&1 | grep -c "42501\|Acesso negado" || true)
if [ "$R" -ge 1 ]; then ok "N15 uid sem cap_compras_ler -> 42501"; else bad "N15 gate de capacidade nao barrou"; fi

seed
P -q -c "UPDATE public.pedido_compra_sugerido SET status='cancelado_humano' WHERE id=100"
R=$(aprova2args 100); case "$R" in *'"error"'*) ok "N16 pedido cancelado nao pode ser aprovado";; *) bad "N16 aprovou pedido cancelado: $R";; esac
eq "N17 pedido cancelado nao foi selado" "$(selo 100)" "NULO"

echo "--- P0-2: as PRIMITIVAS estao fora do alcance de authenticated ---"
# `SET ROLE authenticated` de verdade — nao so o GUC de uid. Sem isto o teste roda como postgres
# e o ACL nunca e exercido (achado P1-6 do challenge Codex).
nega_exec() { P -c "SET ROLE authenticated; $1" 2>&1 | grep -cE "permission denied|permissao negada" || true; }
seed
eq "R1 authenticated NAO executa reposicao_selar_pedido"  "$(nega_exec "SELECT public.reposicao_selar_pedido(100);")" "1"
eq "R2 authenticated NAO executa reposicao_selo_itens"    "$(nega_exec "SELECT public.reposicao_selo_itens(100);")" "1"
eq "R3 authenticated NAO executa reposicao_conferir_envio" "$(nega_exec "SELECT * FROM public.reposicao_conferir_envio(100);")" "1"
eq "R4 authenticated AINDA executa a RPC de aprovacao (e a porta)" "$(P -c "SET ROLE authenticated; SELECT public.aprovar_pedido_sugerido(100,'x',NULL::jsonb);" 2>&1 | grep -cE "permission denied" || true)" "0"

echo "--- P1-2: round-trip pelo fator do SNAPSHOT (fator do motor NULL) ---"
seed
eq "Q1 fator do motor NULL + vivo 0,2 + qtde 41 -> SA005" "$(marca 1000 SA005)" "MARCA_OK"
eq "Q2 e nao selou"                                       "$(selo 1000)" "NULO"
P -q -c "UPDATE public.pedido_compra_item SET qtde_final=40 WHERE id=1001"
eq "Q3 corrigido para 40 (multiplo de 5 L) o selo passa"  "$(marca 1000 SA005)" "SEM_ERRO"

echo "--- P0-1 / P1-3: split fail-closed ---"
seed; aprova2args 900 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='enviando_portal' WHERE id=900"
R=$(P -c "SELECT * FROM public.pedido_compra_split(900,2);" 2>&1 | grep -c "SA009\|duplicar o pedido" || true)
if [ "$R" -ge 1 ]; then ok "X1 split com portal EM VOO -> SA009 (nao duplica no fornecedor)"; else bad "X1 split dividiu com envio em voo"; fi
eq "X2 e nao criou filho"  "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900")" "0"
seed; aprova2args 900 >/dev/null
P -q -c "UPDATE public.pedido_compra_item SET qtde_final=99 WHERE id=901"
R=$(P -c "SELECT * FROM public.pedido_compra_split(900,2);" 2>&1 | grep -c "SA010\|selo nao confere\|selo não confere" || true)
if [ "$R" -ge 1 ]; then ok "X3 split com pai ADULTERADO -> SA010 (nao abencoa o estado alterado)"; else bad "X3 split abencoou pai adulterado"; fi

echo "--- P1-1 / P1-4: retry de orfaos e carimbo do watchdog ---"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status='falha_envio', status_envio_portal='pendente_envio_portal' WHERE id=100"
eq "Y1 claim ACEITA falha_envio (sayerlack_retry_orfaos depende)" "$(Pq -c "SELECT count(*) FROM public.envio_portal_claim_ids(ARRAY[100]::bigint[])")" "1"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='pendente_envio_portal', atualizado_em=now()-interval '2 hours' WHERE id=100"
P -q -c "SELECT count(*) FROM public.envio_portal_claim_ids(ARRAY[100]::bigint[])" >/dev/null
eq "Y2 claim CARIMBA atualizado_em (watchdog de 5min nao mata o envio em curso)" "$(Pq -c "SELECT (atualizado_em > now()-interval '1 minute')::text FROM public.pedido_compra_sugerido WHERE id=100")" "true"

echo "--- P1-5: unicidade e invariante da TABELA ---"
seed
R=$(P -c "INSERT INTO public.sku_fornecedor_externo (empresa,fornecedor_nome,sku_omie,sku_portal,fator_conversao,ativo) VALUES ('OBEN','RENNER SAYERLACK S/A','FOA05','OUTRO',1,true);" 2>&1 | grep -c "ux_sku_fornecedor_externo_ativo\|duplicate key" || true)
if [ "$R" -ge 1 ]; then ok "Z1 UNIQUE parcial barra 2a linha ATIVA para o mesmo SKU"; else bad "Z1 duplicata ativa passou"; fi
eq "Z2 mas linha INATIVA duplicada continua permitida" "$(P -q -c "INSERT INTO public.sku_fornecedor_externo (empresa,fornecedor_nome,sku_omie,sku_portal,fator_conversao,ativo) VALUES ('OBEN','RENNER SAYERLACK S/A','FOA05','HIST',1,false);" >/dev/null 2>&1 && echo ok || echo falhou)" "ok"

echo "--- CONFERENCIA PRE-BROWSERLESS ---"
seed; aprova2args 100 >/dev/null
S0=$(selo 100)
P -q -c "UPDATE public.sku_fornecedor_externo SET sku_portal='OUTRO_CODIGO' WHERE sku_omie='TEH.3505.00BB'"
eq "C1 de-para mudou: o SELO NAO muda (e snapshot, nao leitura viva)" "$(selo 100)" "$S0"
eq "C2 de-para mudou: conferencia acusa depara_aprovado_divergente" "$(Pq -c "SELECT selo_ok::text||'/'||depara_ok::text||'/'||motivo FROM public.reposicao_conferir_envio(100)")" "true/false/depara_aprovado_divergente"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.sku_fornecedor_externo SET ativo=false WHERE sku_omie='TEH.3505.00BB'"
eq "C3 de-para DESATIVADO nao some da conferencia (LEFT, nao CROSS)" "$(Pq -c "SELECT depara_ok::text||'/'||motivo FROM public.reposicao_conferir_envio(100)")" "false/depara_aprovado_divergente"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_item SET qtde_final=45 WHERE id=101"
eq "C4 item alterado depois do selo -> selo_aprovacao_divergente" "$(Pq -c "SELECT selo_ok::text||'/'||motivo FROM public.reposicao_conferir_envio(100)")" "false/selo_aprovacao_divergente"
seed
eq "C5 pedido sem selo -> selo_ausente" "$(Pq -c "SELECT motivo FROM public.reposicao_conferir_envio(100)")" "selo_ausente"

echo "--- CANCELAR / CLAIMS / SPLIT ---"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='enviando_portal' WHERE id=100"
R=$(Pq -c "SELECT public.cancelar_pedido_sugerido(100,'x','y')")
case "$R" in *'em voo'*|*'enviando_portal'*) ok "K1 cancelar com envio EM VOO -> {error}";; *) bad "K1 cancelou em voo: $R";; esac
eq "K2 cancelar em voo nao mudou status"  "$(status 100)" "aprovado_aguardando_disparo"
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='erro_retentavel' WHERE id=100"
R=$(Pq -c "SELECT public.cancelar_pedido_sugerido(100,'x','y')")
case "$R" in *'"status": "ok"'*) ok "K3 cancelar fora de voo continua funcionando";; *) bad "K3 cancelar legitimo recusado: $R";; esac
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='pendente_envio_portal' WHERE id=100"
eq "K4 claim aceita pedido elegivel"      "$(Pq -c "SELECT count(*) FROM public.envio_portal_claim_ids(ARRAY[100]::bigint[])")" "1"
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='pendente_envio_portal', portal_recusa_motivo='selo_aprovacao_divergente' WHERE id=100"
eq "K5 claim RECUSA pedido com recusa duravel" "$(Pq -c "SELECT count(*) FROM public.envio_portal_claim_ids(ARRAY[100]::bigint[])")" "0"
eq "K6 lock_candidatos idem"                   "$(Pq -c "SELECT count(*) FROM public.envio_portal_lock_candidatos(5)")" "0"
eq "K7 pre_claim idem"                         "$(Pq -c "SELECT public.iniciar_envio_portal_pre_claim(100)::text")" "false"
seed; aprova2args 900 >/dev/null
SP=$(selo 900)
P -q -c "SELECT * FROM public.pedido_compra_split(900, 2)" >/dev/null
eq "S1 split gerou 3 filhos"                   "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900")" "3"
eq "S2 TODO filho nasce SELADO"                "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND aprovacao_selo IS NOT NULL")" "3"
eq "S3 filho fica aprovado (nao pendente)"     "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND status='aprovado_aguardando_disparo'")" "3"
eq "S4 filho conferido: selo e de-para batem"  "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido p, LATERAL public.reposicao_conferir_envio(p.id) c WHERE p.split_parent_id=900 AND c.selo_ok AND c.depara_ok")" "3"
eq "S5 pai foi para split_em_filhos"           "$(status 900)" "split_em_filhos"
eq "S6 selo do filho DIFERE do pai (itens outros)" "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND aprovacao_selo='$SP'")" "0"
seed
# pai LEGADO: aprovado ANTES da M1, portanto sem selo nem snapshot
P -q -c "UPDATE public.pedido_compra_sugerido SET status='aprovado_aguardando_disparo' WHERE id=900"
P -q -c "SELECT * FROM public.pedido_compra_split(900, 2)" >/dev/null
eq "S7 pai LEGADO (sem selo) nao quebra o split e os filhos selam" "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND aprovacao_selo IS NOT NULL")" "3"

# ══════════ ZONA 4 — FALSIFICAÇÃO (uma camada por vez; a que ficar VERDE nao tem dente) ══════════
echo "--- FALSIFICACAO ---"
SAB="$(mktemp /tmp/sab-selo.XXXXXX.sql)"
sabota()  { sed "$1" "$MIG" > "$SAB"; P -q -f "$SAB"; }
restaura(){ P -q -f "$MIG"; }

sabota "s/AND i.qtde_final = trunc(i.qtde_final))/AND true)/"
seed; P -q -c "UPDATE public.pedido_compra_item SET qtde_final=7.5 WHERE id=501"
eq "F1 sem o teste de inteireza, a fracao NAO-portal PASSA (N3b tem dente)" "$(marca 500 SA005)" "SEM_ERRO"
restaura

sabota "s/AND i.qtde_final < 1e9/AND true/"
seed; eq "F2 sem o bound 1e9, NaN PASSA (N4 tem dente; > 0 sozinho nao pega NaN)" "$(marca 800 SA005)" "SEM_ERRO"; restaura

sabota "s|AND i.fator_portal_aprovado IS NOT NULL|AND false|"
seed; eq "F3 sem o round-trip da embalagem, 41 L PASSA (N5 tem dente)" "$(marca 700 SA005)" "SEM_ERRO"; restaura

# Sabotar SO o ramo `n_ativas > 1` nao serve: a linha continua sendo SELECIONADA e cai no
# RAISE de inutilizavel (SA006) — o marcador nao vira SEM_ERRO e a falsificacao mede outra
# coisa. A camada que de fato DETECTA a nao-unicidade e o predicado do SELECT; e ela que tem
# de ficar cega para provar que N2 depende dela.
sabota "s/AND (d.n_util <> 1 OR d.n_ativas <> 1)/AND false/"
seed
P -q -c "DROP INDEX public.ux_sku_fornecedor_externo_ativo"
P -q -c "INSERT INTO public.sku_fornecedor_externo (empresa,fornecedor_nome,sku_omie,sku_portal,fator_conversao,ativo) VALUES ('OBEN','RENNER SAYERLACK S/A','AMBIGUO','X2',1,true)"
eq "F4 sem a deteccao de nao-unicidade, 2 linhas ativas PASSAM (N2 tem dente)" "$(marca 300 SA003)" "SEM_ERRO"
# A duplicata TEM de sair antes do restaura: a migration recria o UNIQUE parcial e abortaria
# com "could not create unique index" — o harness morreria na limpeza, nao no assert.
P -q -c "DELETE FROM public.sku_fornecedor_externo WHERE sku_portal='X2'"
restaura

sabota "s/IF v_div > 0 THEN/IF false THEN/"
seed; R=$(aprova 100 "'[{\"id\":101,\"sku_codigo_omie\":\"TEH.3505.00BB\",\"qtde_final\":45,\"fator_embalagem_portal\":0.2},{\"id\":102,\"sku_codigo_omie\":\"FOA05\",\"qtde_final\":3,\"fator_embalagem_portal\":null}]'::jsonb")
case "$R" in *'"status": "ok"'*) ok "F5 sem a comparacao do token, o token divergente PASSA (N11-N14 tem dente)";; *) bad "F5 sabotei o token e N11 nao mudou: $R";; esac
restaura

sabota "/AND COALESCE(status_envio_portal, 'nao_aplicavel') NOT IN ($/,+2d"
seed; aprova2args 100 >/dev/null; P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='enviando_portal' WHERE id=100"
R=$(Pq -c "SELECT public.cancelar_pedido_sugerido(100,'x','y')")
case "$R" in *'"status": "ok"'*) ok "F6 sem o guard de voo, cancelar EM VOO passa (K1 tem dente)";; *) bad "F6 sabotei o guard de voo e K1 nao mudou: $R";; esac
restaura

# A sabotagem NAO pode APAGAR o predicado: a postcondicao da migration conta as 3 funcoes que
# citam `portal_recusa_motivo` e abortaria o apply do arquivo sabotado — o harness morreria
# antes do assert, e um vermelho na limpeza nao prova nada sobre o guard.
# Neutralizar MANTENDO o texto tambem expoe o limite da postcondicao: ela mede PRESENCA de
# string, nao CONTROLE. E exatamente por isso a falsificacao existe.
sabota "s/AND p.portal_recusa_motivo IS NULL/AND (p.portal_recusa_motivo IS NULL OR true)/"
seed; aprova2args 100 >/dev/null
P -q -c "UPDATE public.pedido_compra_sugerido SET status_envio_portal='pendente_envio_portal', portal_recusa_motivo='selo_aprovacao_divergente' WHERE id=100"
eq "F7 sem o filtro de recusa duravel, o claim ACEITA (K5 tem dente)" "$(Pq -c "SELECT count(*) FROM public.envio_portal_claim_ids(ARRAY[100]::bigint[])")" "1"
restaura

# Mesma familia da F7: APAGAR a chamada faria a postcondicao (que exige o texto
# `reposicao_selar_pedido` dentro do split) abortar o apply do arquivo sabotado. Envolver em
# `IF false` mata a chamada e preserva a string — a sabotagem mede o SPLIT, nao a postcondicao.
sabota "s/PERFORM public.reposicao_selar_pedido(v_filho_id, v_selo_pai IS NOT NULL);/IF false THEN PERFORM public.reposicao_selar_pedido(v_filho_id, v_selo_pai IS NOT NULL); END IF;/"
seed; aprova2args 900 >/dev/null; P -q -c "SELECT * FROM public.pedido_compra_split(900, 2)" >/dev/null
eq "F8 split sem selar, filho nasce SEM selo (S2 tem dente)" "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND aprovacao_selo IS NOT NULL")" "0"
restaura

sabota "s/LEFT JOIN LATERAL (/JOIN LATERAL (/"   # INNER: mesma cegueira do CROSS, mas SQL valido
seed; aprova2args 100 >/dev/null; P -q -c "UPDATE public.sku_fornecedor_externo SET ativo=false WHERE sku_omie='TEH.3505.00BB'"
eq "F9 com INNER JOIN, o item SEM de-para some e a conferencia diz ok (C3 tem dente)" "$(Pq -c "SELECT depara_ok::text FROM public.reposicao_conferir_envio(100)")" "true"
restaura

# controle: restaurado, o assert central volta a VERMELHO
seed
eq "F10 controle: apos restaurar, a fracao volta a SA005" "$(marca 600 SA005)" "MARCA_OK"
seed; aprova2args 900 >/dev/null; P -q -c "SELECT * FROM public.pedido_compra_split(900, 2)" >/dev/null
eq "F11 controle: apos restaurar, o split VOLTA a selar os 3 filhos" "$(Pq -c "SELECT count(*) FROM public.pedido_compra_sugerido WHERE split_parent_id=900 AND aprovacao_selo IS NOT NULL")" "3"

echo "------------------------------"
echo "RESULTADO: $PASS ok / $FAIL fail"
[ "$FAIL" = "0" ] || { echo "HARNESS VERMELHO"; exit 1; }
echo "HARNESS VERDE"
