#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  PROVA PG17 — 20260904233000_sku_fornecedor_externo_fator_positivo.sql         ║
# ║  CHECK (fator_conversao > 0 AND fator_conversao < 'Infinity') fecha os TRÊS    ║
# ║  lados: sinal, NaN e Infinity (money-path.md: `> 0` aceita NaN E Infinity).    ║
# ║  (P) acervo válido sobrevive · valores válidos entram · re-run idempotente ·   ║
# ║      dado sujo derruba o apply (auto-defesa, atômico)                          ║
# ║  (N) 0/-1/NaN/Infinity/-Infinity barrados com 23514 em INSERT e UPDATE         ║
# ║  (F) falsificação: forma fraca `> 0` e `> 0 AND <> NaN` → postcondição GRITA;  ║
# ║      ADD removido → A1 grita; constraint dropada → o assert do harness fica    ║
# ║      VERMELHO (dente provado); estado real preservado após cada sabotagem.     ║
# ║  Rode: bash db/test-sku-fornecedor-externo-fator-positivo.sh > /tmp/t.log 2>&1; echo "exit=$?" ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PGVER=17
PGBIN="/opt/homebrew/opt/postgresql@${PGVER}/bin"
PORT="${PGPORT_TEST:-5497}"     # fora das portas dos outros harnesses (5434-5496)
SLUG="fatorpositivo"
DATA="$(mktemp -d "/tmp/pgtest-${SLUG}.XXXXXX")/data"
export LC_ALL=C LANG=C

[ -x "$PGBIN/initdb" ] || { echo "postgresql@${PGVER} ausente: brew install postgresql@${PGVER} pgvector"; exit 1; }

CELLAR="$(brew --prefix "postgresql@${PGVER}")"
cp -Rn "$CELLAR"/share/postgresql/. "/opt/homebrew/share/postgresql@${PGVER}/" 2>/dev/null || true
mkdir -p "/opt/homebrew/lib/postgresql@${PGVER}"
cp -Rn "$CELLAR"/lib/postgresql/. "/opt/homebrew/lib/postgresql@${PGVER}/" 2>/dev/null || true

SABOT_DIR="$(mktemp -d "/tmp/pgtest-${SLUG}-sabot.XXXXXX")"
cleanup() { "$PGBIN/pg_ctl" -D "$DATA" stop -m immediate >/dev/null 2>&1 || true; rm -rf "$(dirname "$DATA")" "$SABOT_DIR"; }
trap cleanup EXIT

"$PGBIN/initdb" -D "$DATA" -U postgres -E UTF8 --locale=C >/dev/null
"$PGBIN/pg_ctl" -D "$DATA" -o "-p $PORT -k /tmp" -l "/tmp/pg-${SLUG}.log" -w start >/dev/null
"$PGBIN/createdb" -p "$PORT" -h /tmp -U postgres prove
P()  { "$PGBIN/psql" -p "$PORT" -h /tmp -U postgres -d prove -v ON_ERROR_STOP=1 "$@"; }
Pq() { P -tA "$@"; }

P -q -f "$REPO_ROOT/db/stubs-supabase.sql"

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✅ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ❌ $1"; }
eq()  { if [ "$2" = "$3" ]; then ok "$1 (=$2)"; else bad "$1 — esperado [$3], veio [$2]"; fi; }

MIG="$REPO_ROOT/supabase/migrations/20260904233000_sku_fornecedor_externo_fator_positivo.sql"

# Estado da constraint no catálogo: "<n>|<convalidated>" (n = quantas com esse nome; t/f).
estado_constraint() {
  Pq -c "SELECT count(*) || '|' || CASE WHEN bool_and(convalidated) IS NULL THEN '-' WHEN bool_and(convalidated) THEN 't' ELSE 'f' END FROM pg_constraint
         WHERE conrelid = 'public.sku_fornecedor_externo'::regclass
           AND conname = 'sku_fornecedor_externo_fator_positivo' AND contype = 'c';"
}

# sonda_rejeita SQL → retorna 0 se o statement foi barrado com check_violation (23514),
# 1 se PASSOU, e ABORTA o harness em qualquer outro erro (re-lança — Lei #2).
# Sentinela FATOR_BARROU_SENTINELA é NOSSA (não é texto do Postgres nem da migration).
sonda_rejeita() {
  local R
  R=$(P -tA 2>&1 <<SQL
DO \$do\$
BEGIN
  $1;
  RAISE NOTICE 'FATOR_PASSOU_SENTINELA';
EXCEPTION
  WHEN check_violation THEN RAISE NOTICE 'FATOR_BARROU_SENTINELA';
  WHEN OTHERS THEN RAISE;
END
\$do\$;
SQL
) || { echo "  ‼ erro INESPERADO na sonda ($1): $R"; exit 2; }
  case "$R" in
    *FATOR_BARROU_SENTINELA*) return 0;;
    *FATOR_PASSOU_SENTINELA*) return 1;;
    *) echo "  ‼ sonda sem sentinela: $R"; exit 2;;
  esac
}
ins_sql() { echo "INSERT INTO public.sku_fornecedor_externo (empresa, fornecedor_nome, sku_omie, fator_conversao) VALUES ('colacor', 'Sayerlack', 'SONDA-$RANDOM-$RANDOM', '$1'::numeric)"; }
must_reject() { if sonda_rejeita "$1"; then ok "$2 (rejeitado: check_violation 23514)"; else bad "$2 — devia barrar com 23514 e PASSOU"; fi; }
must_accept() { if sonda_rejeita "$1"; then bad "$2 — valor VÁLIDO foi barrado"; else ok "$2 (aceito)"; fi; }

echo "═══ setup pronto (PG17 :$PORT) ═══"

# ══════════════════════════════════════════════════════════════════════════════
# ZONA 1 — PRÉ-REQUISITO: a tabela (DDL do schema-snapshot + pkey + unique da prod)
# ══════════════════════════════════════════════════════════════════════════════
P -q <<'SQL'
CREATE TABLE public.sku_fornecedor_externo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa text NOT NULL,
    fornecedor_nome text NOT NULL,
    sku_omie text NOT NULL,
    sku_portal text,
    unidade_portal text DEFAULT 'UN'::text NOT NULL,
    fator_conversao numeric DEFAULT 1 NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    observacoes text,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    atualizado_em timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sku_fornecedor_externo_unique UNIQUE (empresa, fornecedor_nome, sku_omie)
);
-- acervo espelhando a prod: fator 1 (maioria) e 0.2 (balde 20L → litro, ids 131/139/252)
INSERT INTO public.sku_fornecedor_externo (empresa, fornecedor_nome, sku_omie, fator_conversao) VALUES
  ('colacor', 'Sayerlack', 'SKU-A', 1),
  ('colacor', 'Sayerlack', 'SKU-B', 1),
  ('colacor', 'Sayerlack', 'SKU-C', 0.2);
SQL

# ══════════════════════════════════════════════════════════════════════════════
# ZONA 2 — MIGRATION REAL
# ══════════════════════════════════════════════════════════════════════════════
P -q -f "$MIG"
echo "migration aplicada: $(basename "$MIG")"

# ══════════════════════════════════════════════════════════════════════════════
# ZONA 4 — ASSERTS
# ══════════════════════════════════════════════════════════════════════════════
echo "── positivos ──"
eq "P1 constraint existe, é CHECK e está VALIDATED"           "$(estado_constraint)" "1|t"
eq "P2 acervo válido (1, 1, 0.2) sobreviveu ao ADD"           "$(Pq -c 'SELECT count(*) FROM public.sku_fornecedor_externo;')" "3"
must_accept "$(ins_sql 2.5)"        "P3 INSERT fator 2.5 (litro → balde) entra"
must_accept "$(ins_sql 0.000001)"   "P4 INSERT fator 0.000001 (positivo minúsculo) entra"
must_accept "UPDATE public.sku_fornecedor_externo SET fator_conversao = 0.2 WHERE sku_omie = 'SKU-A'" "P5 UPDATE para 0.2 entra"

echo "── negativos (os três lados) ──"
must_reject "$(ins_sql 0)"          "N1 INSERT fator 0"
must_reject "$(ins_sql -1)"         "N2 INSERT fator -1"
must_reject "$(ins_sql NaN)"        "N3 INSERT fator NaN (NaN > 0 é TRUE — só o bound de finitude pega)"
must_reject "$(ins_sql Infinity)"   "N4 INSERT fator Infinity (Infinity > 0 é TRUE — idem)"
must_reject "$(ins_sql -Infinity)"  "N5 INSERT fator -Infinity"
must_reject "UPDATE public.sku_fornecedor_externo SET fator_conversao = 0 WHERE sku_omie = 'SKU-B'"        "N6 UPDATE linha existente para 0"
must_reject "UPDATE public.sku_fornecedor_externo SET fator_conversao = 'NaN' WHERE sku_omie = 'SKU-B'"    "N7 UPDATE linha existente para NaN"
eq "N8 nenhum veneno ficou gravado" "$(Pq -c "SELECT count(*) FROM public.sku_fornecedor_externo WHERE NOT (fator_conversao > 0 AND fator_conversao < 'Infinity'::numeric);")" "0"

echo "── idempotência / auto-defesa ──"
P -q -f "$MIG"
eq "P6 re-run da migration: ainda exatamente 1 constraint, validated" "$(estado_constraint)" "1|t"
must_reject "$(ins_sql 0)"          "P7 re-run preservou o dente (fator 0 barrado)"

# Dado sujo pré-existente: o ADD tem de ABORTAR (23514) e, por BEGIN/COMMIT, deixar o
# banco como estava (constraint anterior intacta — o DROP IF EXISTS foi desfeito junto).
P -q -c "ALTER TABLE public.sku_fornecedor_externo DROP CONSTRAINT sku_fornecedor_externo_fator_positivo;"
P -q -c "INSERT INTO public.sku_fornecedor_externo (empresa, fornecedor_nome, sku_omie, fator_conversao) VALUES ('colacor','Sayerlack','SUJO', 0);"
eq "P8 cenário: constraint ausente + linha suja" "$(estado_constraint)" "0|-"
if P -q -f "$MIG" > "$SABOT_DIR/sujo.log" 2>&1; then
  bad "P9 apply sobre dado sujo devia ABORTAR e passou"
else
  if command grep -q "23514\|check constraint \"sku_fornecedor_externo_fator_positivo\"" "$SABOT_DIR/sujo.log"; then
    ok "P9 apply sobre dado sujo abortou no ADD (23514) — constraint NÃO fica NOT VALID em silêncio"
  else
    bad "P9 apply abortou pelo motivo ERRADO: $(head -c 300 "$SABOT_DIR/sujo.log")"
  fi
fi
eq "P10 após o aborto, nada meio-aplicado (constraint continua ausente, transação desfeita)" "$(estado_constraint)" "0|-"
P -q -c "DELETE FROM public.sku_fornecedor_externo WHERE sku_omie = 'SUJO';"
P -q -f "$MIG"
eq "P11 acervo limpo → apply volta a pegar" "$(estado_constraint)" "1|t"

# ══════════════════════════════════════════════════════════════════════════════
# ZONA 5 — FALSIFICAÇÃO (sabotagens em CÓPIA da migration; o arquivo real não é tocado)
# ══════════════════════════════════════════════════════════════════════════════
echo "── falsificação ──"
# aplica uma cópia sabotada; exige exit≠0 E o assert numerado esperado na saída;
# e que o estado REAL (1|t) tenha sobrevivido (atomicidade do BEGIN/COMMIT).
falsifica() {  # $1 rótulo · $2 arquivo sabotado · $3 assert esperado (A1|A2)
  if P -q -f "$2" > "$SABOT_DIR/$3.log" 2>&1; then
    bad "$1 — migration sabotada PASSOU (postcondição sem dente)"
  elif command grep -q "$3 FALHOU" "$SABOT_DIR/$3.log"; then
    ok "$1 — postcondição gritou '$3 FALHOU'"
  else
    bad "$1 — abortou pelo motivo ERRADO: $(head -c 300 "$SABOT_DIR/$3.log")"
  fi
  eq "$1 — estado real preservado após a sabotagem" "$(estado_constraint)" "1|t"
}

# F1: forma fraca clássica `CHECK (x > 0)` → NaN e Infinity entram → A2 tem de gritar
sed 's/CHECK (fator_conversao > 0 AND fator_conversao < '"'"'Infinity'"'"'::numeric)/CHECK (fator_conversao > 0)/' "$MIG" > "$SABOT_DIR/f1.sql"
command grep -q "CHECK (fator_conversao > 0);" "$SABOT_DIR/f1.sql" || { echo "‼ sed F1 não pegou"; exit 2; }
falsifica "F1 sabotagem: CHECK (x > 0)" "$SABOT_DIR/f1.sql" "A2"

# F2: `CHECK (x > 0 AND x <> 'NaN')` → Infinity entra → A2 tem de gritar
sed 's/fator_conversao < '"'"'Infinity'"'"'::numeric/fator_conversao <> '"'"'NaN'"'"'::numeric/' "$MIG" > "$SABOT_DIR/f2.sql"
command grep -q "<> 'NaN'::numeric" "$SABOT_DIR/f2.sql" || { echo "‼ sed F2 não pegou"; exit 2; }
falsifica "F2 sabotagem: CHECK (x > 0 AND x <> NaN)" "$SABOT_DIR/f2.sql" "A2"

# F3: ADD CONSTRAINT removido (só o DROP sobra) → A1 tem de gritar
# remove o statement inteiro (o ALTER TABLE da linha ANTERIOR + ADD … até o ';'), segurando 1 linha de lookbehind
awk 'BEGIN{skip=0; have=0}
  /ADD CONSTRAINT sku_fornecedor_externo_fator_positivo/ { skip=1; have=0; next }
  { if (skip) { if ($0 ~ /;/) skip=0; next }
    if (have) print held; held=$0; have=1 }
  END { if (have) print held }' "$MIG" > "$SABOT_DIR/f3.sql"
command grep -v -- '^--' "$SABOT_DIR/f3.sql" | command grep -q "ADD CONSTRAINT" && { echo "‼ awk F3 não removeu o ADD"; exit 2; }
falsifica "F3 sabotagem: ADD CONSTRAINT removido" "$SABOT_DIR/f3.sql" "A1"

# F4: o assert DO HARNESS tem dente? Sem constraint, must_reject de 0 tem de ficar VERMELHO.
P -q -c "ALTER TABLE public.sku_fornecedor_externo DROP CONSTRAINT sku_fornecedor_externo_fator_positivo;"
if sonda_rejeita "$(ins_sql 0)"; then
  bad "F4 sem constraint a sonda AINDA diz 'barrou' — assert sem dente"
else
  ok "F4 sem constraint a sonda vira VERMELHO (fator 0 entrou) — dente provado"
fi
P -q -c "DELETE FROM public.sku_fornecedor_externo WHERE fator_conversao = 0;"
P -q -f "$MIG"   # restaura a versão verdadeira
must_reject "$(ins_sql 0)"  "F5 restaurado: fator 0 volta a ser barrado"
eq "F6 estado final" "$(estado_constraint)" "1|t"

# ── veredito ──
echo "──────────────────────────────"
echo "RESULTADO: $PASS ok / $FAIL fail"
[ "$FAIL" = "0" ] || { echo "❌ HARNESS VERMELHO"; exit 1; }
echo "✅ HARNESS VERDE"
