// MANIFESTO DE MÓDULOS — fonte única de "qual path pertence a qual módulo".
// F1 da modularização (spec: docs/superpowers/specs/2026-07-08-modularizacao-f1-manifesto-boletim-design.md).
//
// Regras (garantidas pelo gate em __tests__/manifesto.gate.test.ts, que roda no CI):
//   1. Todo arquivo de src/ tem EXATAMENTE 1 dono, ou está em NAO_CLASSIFICADOS (dívida visível e datada).
//   2. Sobreposição de globs entre módulos é ERRO — efeito cruzado é dependência (F2), não dupla posse.
//   3. Glob que não casa nada é ERRO (manifesto apodrecendo).
// Gramática dos globs: "dir/**" (tudo sob dir) · "*" (wildcard num segmento) · caminho exato — ver padrao.ts.
import type { ModuloApp, NaoClassificado } from "./tipos";

export const MODULOS: ModuloApp[] = [
  {
    id: "loja-afiacao",
    nome: "Loja / Afiação (cliente)",
    kind: "negocio",
    rotaPrefixos: ["/", "/orders", "/new-order", "/tools", "/loyalty", "/gamification", "/training", "/savings"],
    gates: [],
    codigo: [
      "src/lib/afiacao/**",
      "src/lib/tools/**",
      "src/components/customerDashboard/**",
      "src/components/loyalty/**",
      "src/components/AddToolDialog.tsx",
      "src/components/CustomerDashboard.tsx",
      "src/components/GamificationCertificate.tsx",
      "src/components/OrderCard.tsx",
      "src/components/OrderChat.tsx",
      "src/components/OrderPrintLayout.tsx",
      "src/components/OrderReview.tsx",
      "src/components/OrderSuccessDialog.tsx",
      "src/components/OrderTimeline.tsx",
      "src/components/SendingQualityChecklist.tsx",
      "src/components/SharpeningSuggestions.tsx",
      "src/components/ToolImageIdentifier.tsx",
      "src/pages/Index.tsx",
      "src/pages/Orders.tsx",
      "src/pages/OrderDetail.tsx",
      "src/pages/Tools.tsx",
      "src/pages/Tool*.tsx",
      "src/pages/Loyalty.tsx",
      "src/pages/Gamification.tsx",
      "src/pages/Training.tsx",
      "src/pages/SavingsDashboard.tsx",
      "src/pages/CentralFerramenta.tsx",
      "src/pages/Addresses.tsx",
      "src/pages/Profile.tsx",
      "src/pages/Support.tsx",
      "src/pages/QualityChecklist.tsx",
      "src/pages/RecurringSchedules.tsx",
      "src/pages/AdminLoyalty.tsx",
      "src/pages/AdminGamification.tsx",
      "src/pages/AdminTraining.tsx",
      "src/queries/useOrders.ts",
      "src/queries/useTraining.ts",
      "src/queries/useUserTools.ts",
      "src/queries/useRecurringSchedules.ts",
      "src/queries/useSavings.ts",
      "src/hooks/useGamificationScore.ts",
      "src/hooks/useSharpeningSuggestions.ts",
    ],
    testes: ["src/pages/__tests__/CentralFerramenta.test.tsx"],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "prime",
    nome: "Prime Colacor (assinatura B2B)",
    kind: "negocio",
    rotaPrefixos: ["/admin/prime"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/prime/competencia.ts",
      "src/lib/prime/erros.ts",
      "src/lib/prime/format.ts",
      "src/lib/prime/uso-form.ts",
      "src/components/adminPrime/**",
      "src/pages/AdminPrime.tsx",
      "src/queries/usePrimeAdmin.ts",
      "src/types/prime.ts",
    ],
    testes: ["src/lib/prime/prime.test.ts"],
    risco: { moneyPath: true, offlineFirst: false, authSensitive: false },
  },
  {
    id: "tarefas",
    nome: "Tarefas",
    kind: "negocio",
    rotaPrefixos: ["/tarefas"],
    gates: [],
    codigo: [
      "src/lib/tarefas/**",
      "src/components/tarefas/**",
      "src/components/KanbanBoard.tsx",
      "src/pages/Tarefas.tsx",
      "src/pages/TarefasTemplates.tsx",
      "src/hooks/useTarefas*.ts",
    ],
    testes: [],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "financeiro",
    nome: "Financeiro",
    kind: "negocio",
    rotaPrefixos: ["/financeiro"],
    gates: ["RequireFinanceiroAccess"],
    codigo: [
      "src/lib/financeiro/**",
      "src/components/financeiro/**",
      "src/services/financeiro*.ts",
      "src/utils/financeiroAlerts.ts",
      "src/pages/Financeiro*.tsx",
      "src/hooks/useFinanceiro*.ts",
      "src/hooks/useAntecipacoes.ts",
      "src/hooks/useCashflow*.ts",
      "src/hooks/useEndividamento.ts",
      "src/hooks/useFunding.ts",
      "src/hooks/useRegimeTributario.ts",
      "src/hooks/useValor.ts",
      "src/hooks/useValorCockpit.ts",
      "src/hooks/usePontoEquilibrio.ts",
      "src/hooks/useConcentracaoRecebiveis.ts",
      "src/hooks/useUtiContas.ts",
      "src/hooks/useProximaAcao.ts",
      "src/hooks/useEventosEventuais.ts",
      "src/hooks/useEventosRecorrentes.ts",
      "src/hooks/usePeriodOverride.ts",
      "src/hooks/useSuggestedMapping.ts",
    ],
    testes: [
      "src/__tests__/financeiro.test.ts",
      "src/hooks/__tests__/useFinanceiroRegime.test.tsx",
      "src/hooks/__tests__/usePeriodOverride.test.tsx",
      "src/hooks/__tests__/useUtiContas.test.ts",
      "src/hooks/__tests__/ponto-equilibrio-folha-ambigua.test.ts",
      "src/services/__tests__/getCapitalDeGiro.test.ts",
      "src/services/__tests__/getFluxoCaixa.test.ts",
      "src/services/__tests__/getResumoFinanceiro.test.ts",
      "src/services/__tests__/getTopInadimplentes.test.ts",
      "src/services/__tests__/somarSaldoAberto.test.ts",
    ],
    risco: { moneyPath: true, offlineFirst: false, authSensitive: true },
  },
  {
    id: "vendas",
    nome: "Vendas",
    kind: "negocio",
    rotaPrefixos: ["/sales", "/unified-order", "/pedidos-programados"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/unified-order/**",
      "src/lib/venda-assistida/**",
      "src/lib/pedido/**",
      "src/lib/pedidosProgramados/**",
      "src/lib/preco/**",
      "src/lib/pricing/**",
      "src/lib/regua-preco/**",
      "src/components/sales/**",
      "src/components/salesOrders/**",
      "src/components/salesOrderEdit/**",
      "src/components/unified-order/**",
      "src/components/unifiedAI/**",
      "src/components/pedidosProgramados/**",
      "src/components/regua-preco/**",
      "src/components/UnifiedAIAssistant.tsx",
      "src/services/orderSubmission/**",
      "src/hooks/unifiedOrder/**",
      "src/pages/Sales*.tsx",
      "src/pages/UnifiedOrder.tsx",
      "src/pages/VendasFerramentas.tsx",
      "src/pages/PedidosProgramados.tsx",
      "src/pages/PedidoProgramadoDetalhe.tsx",
      "src/hooks/useUnifiedOrder.ts",
      "src/hooks/usePricingEngine.ts",
      "src/hooks/useReguaPreco*.ts",
      "src/hooks/useCanariaPreco.ts",
      "src/hooks/usePrecoCockpit.ts",
      "src/hooks/usePriceHistory.ts",
      "src/hooks/useCustoPrazoRegua.ts",
      "src/hooks/useOrderDraft.ts",
      "src/hooks/useOrderDeepLink.ts",
      "src/hooks/useAlertaCreditoCliente.ts",
      "src/hooks/useExcecaoCredito.ts",
      "src/hooks/useBuscaClienteOmie.ts",
      "src/hooks/useHistoricoCompras.ts",
      "src/hooks/useCrossSellEngine.ts",
      "src/hooks/usePedidosProgramados.ts",
    ],
    testes: [
      "src/__tests__/edge-money-path-invariants.test.ts",
      "src/hooks/__tests__/useAlertaCreditoCliente.test.ts",
      "src/hooks/__tests__/usePedidosProgramados.cancelamento.test.tsx",
      "src/hooks/__tests__/usePricingEngine.test.ts",
      "src/hooks/__tests__/useReguaPreco.test.tsx",
      "src/hooks/__tests__/useReguaPreco360.test.tsx",
      "src/hooks/__tests__/useUnifiedOrder.accountGuard.test.ts",
      "src/hooks/__tests__/cross-sell-escopo-sob-falha.test.tsx",
      "src/hooks/__tests__/leitoresObenProof.fatia3.test.ts",
      "src/pages/__tests__/SalesQuotes.accountGuard.test.tsx",
      "src/pages/__tests__/SalesQuotes.priceGuard.test.tsx",
      "src/pages/__tests__/displayReaders.viewFresca.test.ts",
      "src/pages/__tests__/writersCarteiraRpc.fatia4.test.ts",
    ],
    risco: { moneyPath: true, offlineFirst: false, authSensitive: false },
  },
  {
    id: "farmer-inteligencia",
    nome: "Farmer / Inteligência",
    kind: "negocio",
    rotaPrefixos: ["/farmer", "/meu-dia", "/coaching", "/intelligence", "/executive/dashboard", "/radar"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/scoring/**",
      "src/lib/tactical/**",
      "src/lib/radar/**",
      "src/lib/carteira/**",
      "src/lib/carteira-saude/**",
      "src/lib/positivacao/**",
      "src/lib/mixgap/**",
      "src/lib/visitas/**",
      "src/lib/visit-scoring/**",
      "src/lib/dashboard/**",
      "src/lib/sinais/**",
      "src/lib/fila/**",
      "src/components/fila/**",
      "src/components/farmer/**",
      "src/components/intelligence/**",
      "src/components/radar/**",
      "src/components/carteira/**",
      "src/components/dashboard/**",
      "src/components/customer360/**",
      "src/components/visitas/**",
      "src/components/RecommendationCard.tsx",
      "src/components/RecommendationsPanel.tsx",
      "src/hooks/dashboard/**",
      "src/pages/Farmer*.tsx",
      "src/pages/MeuDia.tsx",
      "src/pages/CarteiraBoard.tsx",
      "src/pages/Customer360.tsx",
      "src/pages/IntelligenceDashboard.tsx",
      "src/pages/ExecutiveDashboard.tsx",
      "src/pages/PerformanceHub.tsx",
      "src/pages/RadarClientes.tsx",
      "src/pages/CoachingSPIN.tsx",
      "src/hooks/useFarmer*.ts",
      "src/hooks/useCarteira*.ts",
      "src/hooks/useVisitas*.ts",
      "src/hooks/useMyKpis.ts",
      "src/hooks/useMyMixGap.ts",
      "src/hooks/useMyPositivacao.ts",
      "src/hooks/useMyCarteiraScores.ts",
      "src/hooks/useMyVisitSuggestions.ts",
      "src/hooks/useMyAgendaToday.ts",
      "src/hooks/useTacticalPlan.ts",
      "src/hooks/useTeamKpis.ts",
      "src/hooks/useTeamRanking.ts",
      "src/hooks/useCoverage.ts",
      "src/hooks/useBundleArguments.ts",
      "src/hooks/useBundleEngine.ts",
      "src/hooks/useCopilotEngine.ts",
      "src/hooks/useRecommendationEngine.ts",
      "src/hooks/useKpisVisita*.ts",
      "src/hooks/useLastVisit.ts",
      "src/hooks/useFollowupsVisita.ts",
      "src/hooks/useMinhasVisitasResultado.ts",
      "src/hooks/useDefasagemCliente.ts",
      "src/hooks/useClienteTier.ts",
      "src/hooks/useCustomerSegments.ts",
      "src/hooks/useCustomerVisits.ts",
      "src/hooks/useDiagnosticQuestions.ts",
      "src/hooks/useMarkMixGapFeedback.ts",
      "src/queries/useRadar*.ts",
      "src/queries/useRegistrarContato.ts",
      "src/queries/useRegistrarContatoRadar.ts",
      "src/types/carteira.ts",
      "src/hooks/useFilaAcoes.ts",
      "src/hooks/useCriticaFila.ts",
      "src/hooks/useDashboardCompany.ts",
      "src/hooks/useDashboardLayout.ts",
    ],
    testes: [
      "src/components/intelligence/__tests__/tabs-erro-honesto.test.tsx",
      "src/hooks/__tests__/bundle-escopo-sob-falha.test.tsx",
      "src/hooks/__tests__/cluster-margin-cobertura.test.tsx",
      "src/hooks/__tests__/cluster-margin-paginacao.test.tsx",
      "src/hooks/__tests__/efficiency-margem-indisponivel.test.tsx",
      "src/hooks/__tests__/useBundleArguments.test.ts",
      "src/hooks/__tests__/farmer-performance-cobertura-guard.test.tsx",
      "src/hooks/__tests__/lens-atividade-vendedor.test.tsx",
      "src/hooks/__tests__/lens-engines-ia.test.tsx",
      "src/hooks/__tests__/lens-tactical-plan.test.tsx",
      "src/hooks/__tests__/tactical-plan-posse-dono.test.tsx",
      "src/hooks/__tests__/useLastVisit.test.tsx",
      "src/hooks/__tests__/useDashboardCompany.test.ts",
    ],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "caca",
    nome: "Caça (prospecção)",
    kind: "negocio",
    rotaPrefixos: ["/caca"],
    gates: ["RequireCaca"],
    codigo: ["src/lib/caca/**", "src/components/caca/**", "src/pages/Caca.tsx", "src/hooks/useCaca.ts"],
    testes: [],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: true },
  },
  {
    id: "admin-crm",
    nome: "Admin / CRM",
    kind: "negocio",
    rotaPrefixos: ["/admin"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/clientes-nao-vinculados/**",
      "src/lib/customer-contact/**",
      "src/lib/customer-process/**",
      "src/components/admin-order/**",
      "src/components/adminCustomers/**",
      "src/components/customer/**",
      "src/pages/Admin.tsx",
      "src/pages/AdminCustomers.tsx",
      "src/pages/AdminApprovals.tsx",
      "src/pages/AdminOrderDetail.tsx",
      "src/pages/AdminPriceTable.tsx",
      "src/pages/AdminDemandForecast.tsx",
      "src/pages/AdminMonthlyReports.tsx",
      "src/pages/AdminProductivity.tsx",
      "src/pages/AdminDepartments.tsx",
      "src/pages/AdminCalculadora.tsx",
      "src/pages/ClientesNaoVinculados.tsx",
      "src/hooks/useAdminOrderDetail.ts",
      "src/hooks/useApprovalQueue.ts",
      "src/hooks/useClientesNaoVinculados.ts",
      "src/hooks/useRefreshClientesNaoVinculados.ts",
      "src/hooks/useExportNaoVinculados.ts",
      "src/hooks/useCustomerContacts.ts",
      "src/hooks/useCustomerProcess.ts",
      "src/hooks/useDepartmentsAdmin.ts",
      "src/hooks/useCompletude.ts",
      "src/hooks/useCustomerLastSalesOrder.ts",
    ],
    testes: [],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "tintometrico",
    nome: "Tintométrico",
    kind: "negocio",
    rotaPrefixos: ["/tintometrico"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/tint/**",
      "src/components/tint/**",
      "src/components/tintColorSelect/**",
      "src/components/tintImport/**",
      "src/components/TintColorSelectDialog.tsx",
      "src/pages/Tint*.tsx",
      "src/hooks/useTint*.ts",
    ],
    testes: [],
    risco: { moneyPath: true, offlineFirst: false, authSensitive: false },
  },
  {
    id: "estoque-recebimento",
    nome: "Estoque / Recebimento",
    kind: "negocio",
    rotaPrefixos: ["/admin/estoque", "/recebimento"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/picking/**",
      "src/lib/recebimento/**",
      "src/components/picking/**",
      "src/components/recebimento/**",
      "src/pages/picking/**",
      "src/services/picking-confirm.ts",
      "src/services/recebimento-confirm.ts",
      "src/services/recebimento-cte.ts",
      "src/services/recebimento-divergencia.ts",
      "src/pages/AdminEstoquePicking.tsx",
      "src/pages/AdminEstoqueRecebimento.tsx",
      "src/pages/Recebimento.tsx",
      "src/pages/RecebimentoConferencia.tsx",
      "src/pages/NfeReceipt.tsx",
      "src/queries/useEnviarParaSeparacao.ts",
      "src/queries/usePedidosASeparar.ts",
      "src/hooks/useEstoqueValor.ts",
    ],
    testes: ["src/services/__tests__/picking-confirm.test.ts"],
    risco: { moneyPath: true, offlineFirst: true, authSensitive: false },
  },
  {
    id: "reposicao",
    nome: "Reposição / Compras",
    kind: "negocio",
    rotaPrefixos: ["/admin/reposicao", "/admin/sku-mapeamento"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/reposicao/**",
      "src/lib/reposicao.ts",
      "src/lib/fornecedores/**",
      "src/lib/custo/**",
      "src/lib/custos/**",
      "src/components/reposicao/**",
      "src/components/skuMapeamento/**",
      "src/pages/AdminReposicao*.tsx",
      "src/pages/AdminSkuMapeamento.tsx",
      "src/pages/ParamAutoMudancas.tsx",
      "src/hooks/useReposicaoSessao.ts",
      "src/hooks/useParamAutoMudancas.ts",
      "src/types/reposicao.ts",
      "src/contexts/ReposicaoEmpresaContext.tsx",
    ],
    testes: [
      "src/hooks/__tests__/useReposicaoSessao.test.ts",
      "src/pages/__tests__/AdminReposicaoPromocaoDetail.test.tsx",
    ],
    risco: { moneyPath: true, offlineFirst: false, authSensitive: false },
  },
  {
    id: "producao",
    nome: "Produção",
    kind: "negocio",
    rotaPrefixos: ["/producao"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/pcp/**",
      "src/services/pcp-apontamento.ts",
      "src/pages/Producao*.tsx",
      "src/pages/ProductionOrders.tsx",
    ],
    testes: [],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "governanca",
    nome: "Governança / Gestão",
    kind: "negocio",
    rotaPrefixos: ["/governance", "/gestao"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/governanca/**",
      "src/lib/dataHealth/**",
      "src/lib/melhorias/**",
      "src/lib/gestor/**",
      "src/lib/grupos/**",
      "src/components/governanca/**",
      "src/components/dataHealth/**",
      "src/components/melhorias/**",
      "src/components/grupos/**",
      "src/components/analyticsSync/**",
      "src/components/des/**",
      "src/pages/Gestao*.tsx",
      "src/pages/Governance*.tsx",
      "src/pages/SaudeDados.tsx",
      "src/pages/Melhorias.tsx",
      "src/pages/GrupoCliente360.tsx",
      "src/pages/AdminAnalyticsSync.tsx",
      "src/pages/AdminDesTrimestreAtual.tsx",
      "src/hooks/useDataHealth.ts",
      "src/hooks/useMelhorias.ts",
      "src/hooks/useExcecoesGestor.ts",
      "src/hooks/useIniciativasIceberg.ts",
      "src/hooks/useAuditTrail.ts",
      "src/queries/useClienteGrupos.ts",
      "src/queries/useGrupoComercial.ts",
      "src/queries/useGrupoContatos.ts",
      "src/queries/useGrupoFinanceiro.ts",
    ],
    testes: [
      "src/hooks/__tests__/useAuditTrail.test.tsx",
      "src/hooks/__tests__/useIniciativasIceberg.test.ts",
    ],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "knowledge-base",
    nome: "Base de Conhecimento / Processos",
    kind: "negocio",
    rotaPrefixos: ["/admin/knowledge-base", "/admin/standard-processes"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/knowledge-base/**",
      "src/lib/rag/**",
      "src/lib/standard-process/**",
      "src/components/knowledge-base/**",
      "src/components/standard-process/**",
      "src/pages/AdminKnowledgeBase*.tsx",
      "src/pages/AdminStandardProcess*.tsx",
      "src/hooks/useKb*.ts",
      "src/hooks/useKnowledgeBaseList.ts",
      "src/hooks/useSpecVersions.ts",
      "src/hooks/useExtractSpecs.ts",
      "src/hooks/useExtractionDrafts.ts",
      "src/hooks/useBatchExtract.ts",
      "src/hooks/useBatchUploadKbDocuments.ts",
      "src/hooks/useBulkApproveSpecs.ts",
      "src/hooks/useSaveProductSpecs.ts",
      "src/hooks/useProductSpecLink.ts",
      "src/hooks/useApproveStandardProcess.ts",
      "src/hooks/useSaveStandardProcess.ts",
      "src/hooks/useStandardProcess.ts",
      "src/hooks/useStandardProcessesList.ts",
      "src/hooks/useProcessComparison.ts",
      "src/hooks/useReindexRag.ts",
      "src/hooks/useIcMatches.ts",
    ],
    testes: [
      "src/hooks/__tests__/useExtractSpecs.test.tsx",
      "src/hooks/__tests__/useKnowledgeBaseList.test.tsx",
    ],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: false },
  },
  {
    id: "telefonia-whatsapp-rota",
    nome: "Telefonia / WhatsApp / Rota",
    kind: "negocio",
    rotaPrefixos: ["/telefonia", "/whatsapp", "/rota"],
    gates: ["RequireStaff"],
    codigo: [
      "src/lib/call/**",
      "src/lib/call-log/**",
      "src/lib/call-session/**",
      "src/lib/sip/**",
      "src/lib/transcription/**",
      "src/lib/whatsapp/**",
      "src/lib/route/**",
      "src/lib/maps/**",
      "src/lib/cep/**",
      "src/components/call/**",
      "src/components/telefonia/**",
      "src/components/whatsapp/**",
      "src/components/rota/**",
      "src/components/NvoipDialer.tsx",
      "src/pages/Telefonia.tsx",
      "src/pages/Whatsapp*.tsx",
      "src/pages/Rota*.tsx",
      "src/pages/AdminRoutePlanner.tsx",
      "src/pages/AdminVendorSipCredentials.tsx",
      "src/hooks/useCall*.ts",
      "src/hooks/useNvoipCall.ts",
      "src/hooks/useWebRTCCall.ts",
      "src/hooks/useIsTelefoniaManager.ts",
      "src/hooks/useGravacaoTranscricao.ts",
      "src/hooks/useTranscription.ts",
      "src/hooks/useLinkCallToCustomer.ts",
      "src/hooks/useCustomerCalls.ts",
      "src/hooks/useSendWhatsapp.ts",
      "src/hooks/useWhatsappPendentes.ts",
      "src/hooks/useWhatsappFunil.ts",
      "src/hooks/useRoutePlanner.ts",
      "src/hooks/useMunicaoLigacao.ts",
      "src/hooks/useCatalisadorLink.ts",
      "src/queries/useRoute*.ts",
      "src/queries/useSnapshotRouteQueue.ts",
      "src/queries/useWhatsapp*.ts",
      "src/queries/usePropostaPreview.ts",
      "src/contexts/WebRTCCallContext.tsx",
      "src/contexts/ConditionalWebRTCProvider.tsx",
      "src/contexts/webrtc-call-context.ts",
      "src/types/call-log.ts",
      "src/utils/whatsappShare.ts",
    ],
    testes: [
      "src/contexts/__tests__/WebRTCCallContext.test.tsx",
      "src/contexts/__tests__/webrtc-context-split.test.ts",
      "src/hooks/__tests__/useCallBackend.test.tsx",
      "src/hooks/__tests__/useCustomerCalls.test.tsx",
      "src/hooks/__tests__/useIsTelefoniaManager.test.tsx",
      "src/hooks/__tests__/useTranscription.test.tsx",
      "src/hooks/__tests__/useWebRTCCall.test.tsx",
      "src/pages/__tests__/Telefonia.test.tsx",
      "src/utils/__tests__/whatsappShare.test.ts",
    ],
    risco: { moneyPath: false, offlineFirst: false, authSensitive: true },
  },
  {
    id: "plataforma",
    nome: "Plataforma (shared)",
    kind: "plataforma",
    rotaPrefixos: ["/auth", "/settings", "/docs", "/design-system", "/ai-ops", "/admin/ajuda"],
    gates: [],
    codigo: [
      "src/App.tsx",
      "src/App.css",
      "src/main.tsx",
      "src/index.css",
      "src/vite-env.d.ts",
      "src/assets/**",
      "src/content/**",
      "src/test/**",
      "src/integrations/**",
      "src/types/index.ts",
      "src/components/ui/**",
      "src/components/shell/**",
      "src/components/auth/**",
      "src/components/help/**",
      "src/components/docs/**",
      "src/components/execucoes/**",
      "src/components/impersonation/**",
      "src/components/push/**",
      "src/components/notificacoes/**",
      "src/components/aiOps/**",
      "src/components/AppShell.tsx",
      "src/components/AppShellLayout.tsx",
      "src/components/EmptyState.tsx",
      "src/components/ErrorBoundary.tsx",
      "src/components/ForgotPasswordDialog.tsx",
      "src/components/NotificationPrompt.tsx",
      "src/components/OnboardingWizard.tsx",
      "src/components/PhotoUpload.tsx",
      "src/components/ProtectedRoute.tsx",
      "src/components/RequireCaca.tsx",
      "src/components/RequireFinanceiroAccess.tsx",
      "src/components/RequireStaff.tsx",
      "src/components/StatusBadge.tsx",
      "src/components/VoiceServiceInput.tsx",
      "src/lib/impersonation/**",
      "src/lib/mcp/**",
      "src/lib/nav/**",
      "src/lib/omie/**",
      "src/lib/posthog-error/**",
      "src/lib/push/**",
      "src/lib/time/**",
      "src/lib/modulos/**",
      "src/lib/agruparPorMes.ts",
      "src/lib/analytics.ts",
      "src/lib/escape-html.ts",
      "src/lib/format.ts",
      "src/lib/help-utils.ts",
      "src/lib/invoke-function.ts",
      "src/lib/leading-trailing-throttle.ts",
      "src/lib/logger.ts",
      "src/lib/logger-migration.md",
      "src/lib/offline-handlers.ts",
      "src/lib/offline-queue.ts",
      "src/lib/phone.ts",
      "src/lib/postgrest.ts",
      "src/lib/pwa-update.ts",
      "src/lib/routeCrumbs.ts",
      "src/lib/utils.ts",
      "src/pages/Auth.tsx",
      "src/pages/ResetPassword.tsx",
      "src/pages/OAuthConsent.tsx",
      "src/pages/NotFound.tsx",
      "src/pages/DesignPreview.tsx",
      "src/pages/DesignSystem.tsx",
      "src/pages/UXRules.tsx",
      "src/pages/TechnicalDocs.tsx",
      "src/pages/AIops.tsx",
      "src/pages/SettingsConfig.tsx",
      "src/pages/AdminAjuda.tsx",
      "src/pages/AdminNotificacoes.tsx",
      "src/contexts/AuthContext.tsx",
      "src/contexts/CompanyContext.tsx",
      "src/contexts/AppShellContext.tsx",
      "src/contexts/ImpersonationContext.tsx",
      "src/contexts/DashboardEditModeContext.tsx",
      "src/contexts/DashboardPersonaContext.tsx",
      "src/queries/useProfile.ts",
      "src/services/omieService.ts",
      "src/hooks/useAlertasCriticos.ts",
      "src/hooks/use-mobile.tsx",
      "src/hooks/useDebouncedValue.ts",
      "src/hooks/useInfiniteScroll.ts",
      "src/hooks/useUrlState.ts",
      "src/hooks/useNetworkStatus.ts",
      "src/hooks/useBiometricAuth.ts",
      "src/hooks/usePushNotifications.ts",
      "src/hooks/usePushSubscription.ts",
      "src/hooks/useFeatureFlag.ts",
      "src/hooks/useGlobalSearch.ts",
      "src/hooks/useBreadcrumbs.ts",
      "src/hooks/useSidebarFavorites.ts",
      "src/hooks/useIsTouchDevice.ts",
      "src/hooks/useOffline*.ts",
      "src/hooks/usePersona.ts",
      "src/hooks/useDisplayAccess.ts",
      "src/hooks/useImpersonat*.ts",
      "src/hooks/useCommercialRole.ts",
      "src/hooks/useAuthzContract.ts",
      "src/hooks/useMyCommercialRole.ts",
      "src/hooks/useUserDepartment.ts",
      "src/hooks/useSalesOnlyRestriction.ts",
    ],
    testes: [
      "src/__tests__/app-route-dedupe.test.ts",
      "src/__tests__/auth.test.ts",
      "src/__tests__/edge-app-url.test.ts",
      "src/__tests__/index-html.test.ts",
      "src/lib/escape-html.test.ts",
      "src/lib/__tests__/**",
      "src/components/__tests__/ErrorBoundary.test.tsx",
      "src/components/__tests__/RequireFinanceiroAccess.test.tsx",
      "src/components/__tests__/RequireStaff.test.tsx",
      "src/contexts/__tests__/AuthContext.failsafe.test.tsx",
      "src/contexts/__tests__/DashboardPersonaContext.test.tsx",
      "src/contexts/__tests__/ImpersonationContext.test.tsx",
      "src/hooks/__tests__/offline-flow-integration.test.tsx",
      "src/hooks/__tests__/useOffline*.test.tsx",
      "src/hooks/__tests__/useBreadcrumbs.test.ts",
      "src/hooks/__tests__/useDebouncedValue.test.tsx",
      "src/hooks/__tests__/useInfiniteScroll.test.ts",
      "src/hooks/__tests__/useDisplayAccess.test.tsx",
      "src/hooks/__tests__/useImpersonationTargets.test.tsx",
      "src/hooks/__tests__/useCommercialRole.test.tsx",
      "src/hooks/__tests__/useAuthzContract.test.tsx",
      "src/hooks/__tests__/useMyCommercialRole.test.tsx",
      "src/hooks/__tests__/useUserDepartment.test.tsx",
    ],
    risco: { moneyPath: false, offlineFirst: true, authSensitive: true },
  },
];

// Dívida de classificação do bootstrap F1 — burn-down visível no boletim.
// Regra do gate: entrada aqui NÃO pode ter dono (senão vira erro "nao-classificado-com-dono").
export const NAO_CLASSIFICADOS: NaoClassificado[] = [];

// Composition roots (F2): arquivos ISENTOS da regra de fronteira plataforma↛negócio,
// porque compor os módulos é o papel deles (o router lazy-importa as pages de todos).
// Adicionar entrada aqui é decisão de arquitetura — não use como escape de vazamento.
export const COMPOSICAO_RAIZ: string[] = ["src/App.tsx"];
