-- ========================================================================
-- AUDIT — Custom Migrations
-- ========================================================================
--
-- Gerado por: scripts/audit-custom-migrations.ts
-- Total de custom migrations: 195
--
-- Como usar:
--   1. Abra o Supabase SQL Editor (via Lovable Cloud → Backend → SQL Editor)
--   2. Cole TODO este arquivo numa query
--   3. Run
--   4. Olhe as duas tabelas de resultado: (A) timestamps aplicados, (B) objetos existentes
--
-- Read-only — não altera nada no banco.
-- ========================================================================

-- =====================================================
-- SECTION 1: Timestamps aplicados (canonical check)
-- =====================================================
-- Source of truth do Supabase. Se a row existe aqui, a migration rodou.

WITH expected (version, slug, filename) AS (VALUES
  ('20260328200000', 'financial_module', '20260328200000_financial_module.sql'),
  ('20260328200100', 'fin_categoria_dre_mapping', '20260328200100_fin_categoria_dre_mapping.sql'),
  ('20260328200300', 'fix_fluxo_caixa_dre_regime', '20260328200300_fix_fluxo_caixa_dre_regime.sql'),
  ('20260328200400', 'fix_cron_sync', '20260328200400_fix_cron_sync.sql'),
  ('20260328200500', 'financeiro_v2', '20260328200500_financeiro_v2.sql'),
  ('20260328200600', 'financeiro_v3_backend', '20260328200600_financeiro_v3_backend.sql'),
  ('20260516120000', 'vendor_sip_credentials', '20260516120000_vendor_sip_credentials.sql'),
  ('20260517100000', 'enable_realtime_dashboard_v3', '20260517100000_enable_realtime_dashboard_v3.sql'),
  ('20260517120000', 'user_departments', '20260517120000_user_departments.sql'),
  ('20260517140000', 'dashboard_visits', '20260517140000_dashboard_visits.sql'),
  ('20260517160000', 'farmer_calls_persist_session', '20260517160000_farmer_calls_persist_session.sql'),
  ('20260517170000', 'kb_foundation', '20260517170000_kb_foundation.sql'),
  ('20260517180000', 'kb_specs_and_competitors', '20260517180000_kb_specs_and_competitors.sql'),
  ('20260517190000', 'customer_processes', '20260517190000_customer_processes.sql'),
  ('20260517200000', 'standard_processes', '20260517200000_standard_processes.sql'),
  ('20260517210000', 'rag_chunks', '20260517210000_rag_chunks.sql'),
  ('20260517220000', 'customer_contacts', '20260517220000_customer_contacts.sql'),
  ('20260518000000', 'fin_audit_log', '20260518000000_fin_audit_log.sql'),
  ('20260518000100', 'fin_audit_trigger', '20260518000100_fin_audit_trigger.sql'),
  ('20260518000200', 'fin_audit_attach', '20260518000200_fin_audit_attach.sql'),
  ('20260518000300', 'set_config_rpc', '20260518000300_set_config_rpc.sql'),
  ('20260518001000', 'fin_period_overrides', '20260518001000_fin_period_overrides.sql'),
  ('20260518001100', 'fin_period_lock_trigger', '20260518001100_fin_period_lock_trigger.sql'),
  ('20260518001200', 'fin_period_lock_attach', '20260518001200_fin_period_lock_attach.sql'),
  ('20260518002000', 'dre_unique_with_regime', '20260518002000_dre_unique_with_regime.sql'),
  ('20260518002100', 'fechamento_dual_snapshots', '20260518002100_fechamento_dual_snapshots.sql'),
  ('20260518003000', 'fin_mapping_gate_trigger', '20260518003000_fin_mapping_gate_trigger.sql'),
  ('20260518003100', 'rpc_categorias_sem_mapping', '20260518003100_rpc_categorias_sem_mapping.sql'),
  ('20260518004000', 'fin_ic_matches', '20260518004000_fin_ic_matches.sql'),
  ('20260518004100', 'company_cnpjs', '20260518004100_company_cnpjs.sql'),
  ('20260518004200', 'fin_ic_cron', '20260518004200_fin_ic_cron.sql'),
  ('20260518004300', 'fin_consolidado_v2', '20260518004300_fin_consolidado_v2.sql'),
  ('20260518100000', 'commercial_role_add_values', '20260518100000_commercial_role_add_values.sql'),
  ('20260518110000', 'scoring_v2_signal_modifiers', '20260518110000_scoring_v2_signal_modifiers.sql'),
  ('20260518120000', 'visit_intelligence_v1', '20260518120000_visit_intelligence_v1.sql'),
  ('20260519000000', 'fin_a1_eventos', '20260519000000_fin_a1_eventos.sql'),
  ('20260519000100', 'fin_a1_snapshots_alertas_config', '20260519000100_fin_a1_snapshots_alertas_config.sql'),
  ('20260519000200', 'fin_a1_audit_lock_attach', '20260519000200_fin_a1_audit_lock_attach.sql'),
  ('20260519010000', 'fin_a1_cron', '20260519010000_fin_a1_cron.sql'),
  ('20260519020000', 'fin_onda1_ncg', '20260519020000_fin_onda1_ncg.sql'),
  ('20260520010000', 'scoring_visit_p1_fixes', '20260520010000_scoring_visit_p1_fixes.sql'),
  ('20260523120000', 'call_log', '20260523120000_call_log.sql'),
  ('20260523210000', 'drop_audit_trigger_fin_config_cashflow', '20260523210000_drop_audit_trigger_fin_config_cashflow.sql'),
  ('20260523230000', 'fin_a2_valor_inputs', '20260523230000_fin_a2_valor_inputs.sql'),
  ('20260523230835', 'sync_sla_view_stack', '20260523230835_sync_sla_view_stack.sql'),
  ('20260523233000', 'restaura_guardas_sla_view_stack', '20260523233000_restaura_guardas_sla_view_stack.sql'),
  ('20260524000000', 'fin_a3_cockpit_config', '20260524000000_fin_a3_cockpit_config.sql'),
  ('20260524095612', 'crons_scoring_visit_lendo_cron_secret_do_vault', '20260524095612_crons_scoring_visit_lendo_cron_secret_do_vault.sql'),
  ('20260524100500', 'cron_financeiro_e_fix_sayerlack', '20260524100500_cron_financeiro_e_fix_sayerlack.sql'),
  ('20260524102500', 'fix_fin_triggers_json_field_access', '20260524102500_fix_fin_triggers_json_field_access.sql'),
  ('20260524120000', 'carteira_omie_fase1', '20260524120000_carteira_omie_fase1.sql'),
  ('20260524120000', 'fin_regime_inputs', '20260524120000_fin_regime_inputs.sql'),
  ('20260524121531', 'restore_sla_guards', '20260524121531_restore_sla_guards.sql'),
  ('20260524170000', 'scores_unique_por_cliente', '20260524170000_scores_unique_por_cliente.sql'),
  ('20260524180000', 'carteira_scores_owner_e_filas', '20260524180000_carteira_scores_owner_e_filas.sql'),
  ('20260524202410', 'tuning_crons_estoque_freq_e_timeouts', '20260524202410_tuning_crons_estoque_freq_e_timeouts.sql'),
  ('20260524203000', 'rpc_staff_guard_permite_cron_backend', '20260524203000_rpc_staff_guard_permite_cron_backend.sql'),
  ('20260525000000', 'fin_crons_por_entidade', '20260525000000_fin_crons_por_entidade.sql'),
  ('20260525010000', 'fin_audit_skip_service_role', '20260525010000_fin_audit_skip_service_role.sql'),
  ('20260525020000', 'fin_sync_cursor', '20260525020000_fin_sync_cursor.sql'),
  ('20260525020001', 'fin_rpc_gate_auth_p1', '20260525020001_fin_rpc_gate_auth_p1.sql'),
  ('20260525120000', 'positivacao_kpis', '20260525120000_positivacao_kpis.sql'),
  ('20260525130000', 'fin_analise_dimensoes_rpc', '20260525130000_fin_analise_dimensoes_rpc.sql'),
  ('20260525140000', 'fin_refresh_analise_dimensoes_cron', '20260525140000_fin_refresh_analise_dimensoes_cron.sql'),
  ('20260525140000', 'v_otimizador_compras_insumos', '20260525140000_v_otimizador_compras_insumos.sql'),
  ('20260525160000', 'carteira_saude_rpc', '20260525160000_carteira_saude_rpc.sql'),
  ('20260525190000', 'mixgap_rpc', '20260525190000_mixgap_rpc.sql'),
  ('20260525200000', 'fin_sync_watchdog', '20260525200000_fin_sync_watchdog.sql'),
  ('20260525210000', 'viewas_rpcs_for', '20260525210000_viewas_rpcs_for.sql'),
  ('20260525220000', 'viewas_access_targets', '20260525220000_viewas_access_targets.sql'),
  ('20260525230000', 'impersonation_audit', '20260525230000_impersonation_audit.sql'),
  ('20260526020000', 'rls_score_carteira_hardening', '20260526020000_rls_score_carteira_hardening.sql'),
  ('20260526030000', 'fin_sync_watchdog_sweep_orphans', '20260526030000_fin_sync_watchdog_sweep_orphans.sql'),
  ('20260526040000', 'rls_carteira_relacionamento_hardening', '20260526040000_rls_carteira_relacionamento_hardening.sql'),
  ('20260526060000', 'views_security_invoker_hardening', '20260526060000_views_security_invoker_hardening.sql'),
  ('20260526080000', 'fix_sayerlack_cron_vault', '20260526080000_fix_sayerlack_cron_vault.sql'),
  ('20260526100000', 'fin_funding_inputs', '20260526100000_fin_funding_inputs.sql'),
  ('20260526160000', 'data_health_rpc', '20260526160000_data_health_rpc.sql'),
  ('20260526230000', 'mixgap_feedback', '20260526230000_mixgap_feedback.sql'),
  ('20260527010000', 'rls_copilot_sessions_select_own_only', '20260527010000_rls_copilot_sessions_select_own_only.sql'),
  ('20260527120000', 'clientes_nao_vinculados', '20260527120000_clientes_nao_vinculados.sql'),
  ('20260527120000', 'data_health_rpc_fix', '20260527120000_data_health_rpc_fix.sql'),
  ('20260527140000', 'revoke_carteira_internals_anon', '20260527140000_revoke_carteira_internals_anon.sql'),
  ('20260527160000', 'cron_vendas_sync_pedidos', '20260527160000_cron_vendas_sync_pedidos.sql'),
  ('20260527160000', 'matview_ranking_negociacao_private', '20260527160000_matview_ranking_negociacao_private.sql'),
  ('20260527170000', 'crons_timeout_fix', '20260527170000_crons_timeout_fix.sql'),
  ('20260527180000', 'data_health_add_vendas', '20260527180000_data_health_add_vendas.sql'),
  ('20260527180000', 'get_tint_price_rpc', '20260527180000_get_tint_price_rpc.sql'),
  ('20260527190000', 'drop_redundant_sync_orders_cron', '20260527190000_drop_redundant_sync_orders_cron.sql'),
  ('20260527190000', 'drop_tint_formula_itens_public_select', '20260527190000_drop_tint_formula_itens_public_select.sql'),
  ('20260527200000', 'data_health_add_estoque_reposicao', '20260527200000_data_health_add_estoque_reposicao.sql'),
  ('20260527210000', 'data_health_compute_internal', '20260527210000_data_health_compute_internal.sql'),
  ('20260527220000', 'data_health_watchdog', '20260527220000_data_health_watchdog.sql'),
  ('20260527220001', 'fin_sync_cursor_backfill_desde', '20260527220001_fin_sync_cursor_backfill_desde.sql'),
  ('20260527230000', 'cron_baseline', '20260527230000_cron_baseline.sql'),
  ('20260527235000', 'dispatch_notifications_frequente', '20260527235000_dispatch_notifications_frequente.sql'),
  ('20260527240000', 'data_health_alert_channel', '20260527240000_data_health_alert_channel.sql'),
  ('20260527250000', 'data_health_checks_high', '20260527250000_data_health_checks_high.sql'),
  ('20260527250000', 'nao_vinculados_cron', '20260527250000_nao_vinculados_cron.sql'),
  ('20260527260000', 'data_health_vendas_cadastros_dado', '20260527260000_data_health_vendas_cadastros_dado.sql'),
  ('20260528000000', 'fin_sync_watchdog_tail_failing', '20260528000000_fin_sync_watchdog_tail_failing.sql'),
  ('20260528010000', 'cron_sync_customers_dedicated', '20260528010000_cron_sync_customers_dedicated.sql'),
  ('20260528020000', 'data_health_reposicao_acoes', '20260528020000_data_health_reposicao_acoes.sql'),
  ('20260528030000', 'cron_sayerlack_lote_retry', '20260528030000_cron_sayerlack_lote_retry.sql'),
  ('20260528040000', 'sayerlack_retry_motor', '20260528040000_sayerlack_retry_motor.sql'),
  ('20260528120000', 'reposicao_custo_cmc_em_transito', '20260528120000_reposicao_custo_cmc_em_transito.sql'),
  ('20260528120001', 'v_titulo_baixas', '20260528120001_v_titulo_baixas.sql'),
  ('20260528120002', 'v_capital_giro_prazos', '20260528120002_v_capital_giro_prazos.sql'),
  ('20260528130000', 'fin_sync_heartbeat_tz_fix', '20260528130000_fin_sync_heartbeat_tz_fix.sql'),
  ('20260528130000', 'tarefas_bloco_a', '20260528130000_tarefas_bloco_a.sql'),
  ('20260528131000', 'tarefas_bloco_b', '20260528131000_tarefas_bloco_b.sql'),
  ('20260528132000', 'tarefas_bloco_c', '20260528132000_tarefas_bloco_c.sql'),
  ('20260528133000', 'tarefas_bloco_d', '20260528133000_tarefas_bloco_d.sql'),
  ('20260528134000', 'tarefas_bloco_e', '20260528134000_tarefas_bloco_e.sql'),
  ('20260528135000', 'tarefas_matcher_created_at_floor', '20260528135000_tarefas_matcher_created_at_floor.sql'),
  ('20260528140000', 'data_health_compute_msg_tz', '20260528140000_data_health_compute_msg_tz.sql'),
  ('20260528140000', 'whatsapp_fundacao', '20260528140000_whatsapp_fundacao.sql'),
  ('20260528150000', 'fin_estoque_omie_feed', '20260528150000_fin_estoque_omie_feed.sql'),
  ('20260528160000', 'route_fundacao', '20260528160000_route_fundacao.sql'),
  ('20260528194751', 'data_health_consolida_last_error_e_reposicao_checks', '20260528194751_data_health_consolida_last_error_e_reposicao_checks.sql'),
  ('20260530120000', 'visitas_agendadas', '20260530120000_visitas_agendadas.sql'),
  ('20260530140000', 'fin_watchdog_sync_stale_grace_email', '20260530140000_fin_watchdog_sync_stale_grace_email.sql'),
  ('20260530143818', 'reposicao_excluir_405ml', '20260530143818_reposicao_excluir_405ml.sql'),
  ('20260530160000', 'data_health_diagnostico_gate_status', '20260530160000_data_health_diagnostico_gate_status.sql'),
  ('20260530170000', 'unschedule_sayerlack_lote_retry', '20260530170000_unschedule_sayerlack_lote_retry.sql'),
  ('20260530180000', 'fix_sku_fornecedor_externo_atualizado_em_trigger', '20260530180000_fix_sku_fornecedor_externo_atualizado_em_trigger.sql'),
  ('20260530190000', 'data_health_portal_push', '20260530190000_data_health_portal_push.sql'),
  ('20260530190000', 'reposicao_preencher_parametros_faltantes', '20260530190000_reposicao_preencher_parametros_faltantes.sql'),
  ('20260530200000', 'data_health_checks_acionaveis', '20260530200000_data_health_checks_acionaveis.sql'),
  ('20260530200000', 'reposicao_classificar_sayerlack_grupo_default', '20260530200000_reposicao_classificar_sayerlack_grupo_default.sql'),
  ('20260530210000', 'data_health_restaura_portal_split', '20260530210000_data_health_restaura_portal_split.sql'),
  ('20260530210000', 'reposicao_candidatos_primeira_compra', '20260530210000_reposicao_candidatos_primeira_compra.sql'),
  ('20260530210001', 'cancelar_pedido_limpa_portal', '20260530210001_cancelar_pedido_limpa_portal.sql'),
  ('20260530230000', 'fix_portal_lock_retry_blindspot', '20260530230000_fix_portal_lock_retry_blindspot.sql'),
  ('20260531120000', 'reposicao_candidatos_inclui_habilitados', '20260531120000_reposicao_candidatos_inclui_habilitados.sql'),
  ('20260531130000', 'data_health_check_sayerlack_fabricado', '20260531130000_data_health_check_sayerlack_fabricado.sql'),
  ('20260531140000', 'reposicao_atualizar_params_nao_zera', '20260531140000_reposicao_atualizar_params_nao_zera.sql'),
  ('20260531150000', 'reposicao_param_limbo_watchdog', '20260531150000_reposicao_param_limbo_watchdog.sql'),
  ('20260531160000', 'reposicao_excluir_fabricado_04', '20260531160000_reposicao_excluir_fabricado_04.sql'),
  ('20260531170000', 'data_health_check_sayerlack_mapeamento_gap', '20260531170000_data_health_check_sayerlack_mapeamento_gap.sql'),
  ('20260531170000', 'route_contact_log_escrita', '20260531170000_route_contact_log_escrita.sql'),
  ('20260601000000', 'tarefas_escalonamento_titulo_mensagem', '20260601000000_tarefas_escalonamento_titulo_mensagem.sql'),
  ('20260601100000', 'tarefas_fase2_bloco_a', '20260601100000_tarefas_fase2_bloco_a.sql'),
  ('20260601101000', 'tarefas_fase2_bloco_b', '20260601101000_tarefas_fase2_bloco_b.sql'),
  ('20260601102000', 'tarefas_fase2_bloco_c', '20260601102000_tarefas_fase2_bloco_c.sql'),
  ('20260601103000', 'tarefas_fase2_bloco_d', '20260601103000_tarefas_fase2_bloco_d.sql'),
  ('20260601104000', 'tarefas_fase2_bloco_e', '20260601104000_tarefas_fase2_bloco_e.sql'),
  ('20260602101856', 'reposicao_refresh_descricao_sku_parametros', '20260602101856_reposicao_refresh_descricao_sku_parametros.sql'),
  ('20260604120000', 'loyalty_rls_hardening', '20260604120000_loyalty_rls_hardening.sql'),
  ('20260604120000', 'picking_bridge', '20260604120000_picking_bridge.sql'),
  ('20260604120000', 'route_queue_snapshot', '20260604120000_route_queue_snapshot.sql'),
  ('20260604130000', 'omie_products_tipo_produto_coluna', '20260604130000_omie_products_tipo_produto_coluna.sql'),
  ('20260604130000', 'whatsapp_sla', '20260604130000_whatsapp_sla.sql'),
  ('20260604140000', 'recebimento_efetivacao_ledger', '20260604140000_recebimento_efetivacao_ledger.sql'),
  ('20260604140000', 'tipo_produto_consumidores', '20260604140000_tipo_produto_consumidores.sql'),
  ('20260604140000', 'whatsapp_sla_digest', '20260604140000_whatsapp_sla_digest.sql'),
  ('20260604150000', 'envio_portal_claim_ids', '20260604150000_envio_portal_claim_ids.sql'),
  ('20260604150000', 'tipo_produto_vigia_cobertura', '20260604150000_tipo_produto_vigia_cobertura.sql'),
  ('20260604160000', 'route_queue_snapshot_nome', '20260604160000_route_queue_snapshot_nome.sql'),
  ('20260604170000', 'posthog_error_webhook', '20260604170000_posthog_error_webhook.sql'),
  ('20260604170000', 'reposicao_blindar_sku_sem_fornecedor', '20260604170000_reposicao_blindar_sku_sem_fornecedor.sql'),
  ('20260604170000', 'tint_catalog_rls_hardening', '20260604170000_tint_catalog_rls_hardening.sql'),
  ('20260604180000', 'envio_portal_claim_ids_lista_positiva', '20260604180000_envio_portal_claim_ids_lista_positiva.sql'),
  ('20260604180000', 'public_tool_history_rpc', '20260604180000_public_tool_history_rpc.sql'),
  ('20260604182408', 'embalagem_economica', '20260604182408_embalagem_economica.sql'),
  ('20260604190000', 'reposicao_minimo_forcado', '20260604190000_reposicao_minimo_forcado.sql'),
  ('20260605120000', 'param_auto_tabelas', '20260605120000_param_auto_tabelas.sql'),
  ('20260605120000', 'tarefas_guard_old_requer', '20260605120000_tarefas_guard_old_requer.sql'),
  ('20260605130000', 'param_auto_core', '20260605130000_param_auto_core.sql'),
  ('20260605130000', 'tarefas_leitura_na_instancia', '20260605130000_tarefas_leitura_na_instancia.sql'),
  ('20260605140000', 'afiacao_os_status_sync', '20260605140000_afiacao_os_status_sync.sql'),
  ('20260605140000', 'iniciar_envio_portal_pre_claim', '20260605140000_iniciar_envio_portal_pre_claim.sql'),
  ('20260605140000', 'param_auto_wrapper_revert_cron', '20260605140000_param_auto_wrapper_revert_cron.sql'),
  ('20260605150000', 'param_auto_fusivel_calibracao', '20260605150000_param_auto_fusivel_calibracao.sql'),
  ('20260605152437', 'caca_views', '20260605152437_caca_views.sql'),
  ('20260606120000', 'reposicao_rpc_account_aware', '20260606120000_reposicao_rpc_account_aware.sql'),
  ('20260606130000', 'detectar_skus_sem_grupo_exclui_04', '20260606130000_detectar_skus_sem_grupo_exclui_04.sql'),
  ('20260606140000', 'detectar_skus_sem_grupo_self_heal', '20260606140000_detectar_skus_sem_grupo_self_heal.sql'),
  ('20260606150000', 'a2_cmc_base_custo_view', '20260606150000_a2_cmc_base_custo_view.sql'),
  ('20260606150000', 'reposicao_qtde_inteira', '20260606150000_reposicao_qtde_inteira.sql'),
  ('20260606170000', 'reposicao_fix_aplicar_promocoes', '20260606170000_reposicao_fix_aplicar_promocoes.sql'),
  ('20260606180000', 'reposicao_aplicar_promocoes_hardening', '20260606180000_reposicao_aplicar_promocoes_hardening.sql'),
  ('20260606180000', 'reposicao_preco_pedido_cmc', '20260606180000_reposicao_preco_pedido_cmc.sql'),
  ('20260606190000', 'reposicao_preco_pedido_cmc_account', '20260606190000_reposicao_preco_pedido_cmc_account.sql'),
  ('20260606190000', 'reposicao_qtde_inteira_persist', '20260606190000_reposicao_qtde_inteira_persist.sql'),
  ('20260606200000', 'reposicao_promo_forward_buying_min', '20260606200000_reposicao_promo_forward_buying_min.sql'),
  ('20260606210000', 'order_feed_view', '20260606210000_order_feed_view.sql'),
  ('20260606230000', 'negociacao_paralela_v2_cleanup', '20260606230000_negociacao_paralela_v2_cleanup.sql'),
  ('20260608120000', 'tool_spec_custom_option', '20260608120000_tool_spec_custom_option.sql'),
  ('20260609085244', 'data_health_check_familia_ausente', '20260609085244_data_health_check_familia_ausente.sql'),
  ('20260609150000', 'reposicao_alerta_pedido_minimo', '20260609150000_reposicao_alerta_pedido_minimo.sql'),
  ('20260609150000', 'tint_sync_promote', '20260609150000_tint_sync_promote.sql'),
  ('20260609160000', 'reposicao_ciclo_intraday', '20260609160000_reposicao_ciclo_intraday.sql'),
  ('20260610150000', 'reposicao_auto_aprovacao_piloto', '20260610150000_reposicao_auto_aprovacao_piloto.sql'),
  ('20260610200000', 'push_vendedora', '20260610200000_push_vendedora.sql')
)
SELECT
  e.version,
  e.slug,
  CASE WHEN sm.version IS NOT NULL THEN '✅ applied' ELSE '❌ MISSING — apply manually' END AS status,
  e.filename
FROM expected e
LEFT JOIN supabase_migrations.schema_migrations sm ON sm.version = e.version
ORDER BY e.version;


-- =====================================================
-- SECTION 2: Object existence (cross-check)
-- =====================================================
-- Caso schema_migrations diga ✅ mas o objeto não exista (rollback manual,
-- partial apply), esta query captura. Para cada objeto esperado, checa pg_catalog.

WITH expected_objects (migration, kind, schema_name, object_name, parent_name) AS (VALUES
  ('financial_module', 'table', 'public', 'fin_categorias', ''),
  ('financial_module', 'table', 'public', 'fin_contas_correntes', ''),
  ('financial_module', 'table', 'public', 'fin_contas_pagar', ''),
  ('financial_module', 'table', 'public', 'fin_contas_receber', ''),
  ('financial_module', 'table', 'public', 'fin_movimentacoes', ''),
  ('financial_module', 'table', 'public', 'fin_dre_snapshots', ''),
  ('financial_module', 'index', 'public', 'idx_fin_categorias_company', 'fin_categorias'),
  ('financial_module', 'index', 'public', 'idx_fin_categorias_tipo', 'fin_categorias'),
  ('financial_module', 'index', 'public', 'idx_fin_cc_company', 'fin_contas_correntes'),
  ('financial_module', 'index', 'public', 'idx_fin_cp_company', 'fin_contas_pagar'),
  ('financial_module', 'index', 'public', 'idx_fin_cp_status', 'fin_contas_pagar'),
  ('financial_module', 'index', 'public', 'idx_fin_cp_vencimento', 'fin_contas_pagar'),
  ('financial_module', 'index', 'public', 'idx_fin_cp_fornecedor', 'fin_contas_pagar'),
  ('financial_module', 'index', 'public', 'idx_fin_cp_categoria', 'fin_contas_pagar'),
  ('financial_module', 'index', 'public', 'idx_fin_cr_company', 'fin_contas_receber'),
  ('financial_module', 'index', 'public', 'idx_fin_cr_status', 'fin_contas_receber'),
  ('financial_module', 'index', 'public', 'idx_fin_cr_vencimento', 'fin_contas_receber'),
  ('financial_module', 'index', 'public', 'idx_fin_cr_cliente', 'fin_contas_receber'),
  ('financial_module', 'index', 'public', 'idx_fin_cr_categoria', 'fin_contas_receber'),
  ('financial_module', 'index', 'public', 'idx_fin_mov_company', 'fin_movimentacoes'),
  ('financial_module', 'index', 'public', 'idx_fin_mov_data', 'fin_movimentacoes'),
  ('financial_module', 'index', 'public', 'idx_fin_mov_cc', 'fin_movimentacoes'),
  ('financial_module', 'index', 'public', 'idx_fin_dre_company_periodo', 'fin_dre_snapshots'),
  ('financial_module', 'rls_policy', 'public', 'fin_categorias_select', 'fin_categorias'),
  ('financial_module', 'rls_policy', 'public', 'fin_cc_select', 'fin_contas_correntes'),
  ('financial_module', 'rls_policy', 'public', 'fin_cp_select', 'fin_contas_pagar'),
  ('financial_module', 'rls_policy', 'public', 'fin_cr_select', 'fin_contas_receber'),
  ('financial_module', 'rls_policy', 'public', 'fin_mov_select', 'fin_movimentacoes'),
  ('financial_module', 'rls_policy', 'public', 'fin_dre_select', 'fin_dre_snapshots'),
  ('financial_module', 'rls_policy', 'public', 'fin_categorias_service', 'fin_categorias'),
  ('financial_module', 'rls_policy', 'public', 'fin_cc_service', 'fin_contas_correntes'),
  ('financial_module', 'rls_policy', 'public', 'fin_cp_service', 'fin_contas_pagar'),
  ('financial_module', 'rls_policy', 'public', 'fin_cr_service', 'fin_contas_receber'),
  ('financial_module', 'rls_policy', 'public', 'fin_mov_service', 'fin_movimentacoes'),
  ('financial_module', 'rls_policy', 'public', 'fin_dre_service', 'fin_dre_snapshots'),
  ('fin_categoria_dre_mapping', 'table', 'public', 'fin_categoria_dre_mapping', ''),
  ('fin_categoria_dre_mapping', 'index', 'public', 'idx_fin_cat_dre_company', 'fin_categoria_dre_mapping'),
  ('fin_categoria_dre_mapping', 'rls_policy', 'public', 'fin_cat_dre_select', 'fin_categoria_dre_mapping'),
  ('fin_categoria_dre_mapping', 'rls_policy', 'public', 'fin_cat_dre_all_service', 'fin_categoria_dre_mapping'),
  ('fin_categoria_dre_mapping', 'rls_policy', 'public', 'fin_cat_dre_admin_modify', 'fin_categoria_dre_mapping'),
  ('fix_cron_sync', 'table', 'public', 'fin_sync_log', ''),
  ('fix_cron_sync', 'index', 'public', 'idx_fin_sync_log_started', 'fin_sync_log'),
  ('financeiro_v2', 'table', 'public', 'fin_fechamentos', ''),
  ('financeiro_v2', 'table', 'public', 'fin_fechamento_log', ''),
  ('financeiro_v2', 'table', 'public', 'fin_conciliacao', ''),
  ('financeiro_v2', 'table', 'public', 'fin_eliminacoes_intercompany', ''),
  ('financeiro_v2', 'table', 'public', 'fin_eliminacoes_log', ''),
  ('financeiro_v2', 'table', 'public', 'fin_orcamento', ''),
  ('financeiro_v2', 'table', 'public', 'fin_forecast', ''),
  ('financeiro_v2', 'table', 'public', 'fin_permissoes', ''),
  ('financeiro_v2', 'table', 'public', 'fin_kpi_tributario', ''),
  ('financeiro_v2', 'index', 'public', 'idx_fin_fech_company_periodo', 'fin_fechamentos'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_fech_status', 'fin_fechamentos'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_fech_log_fech', 'fin_fechamento_log'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_conc_company', 'fin_conciliacao'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_conc_status', 'fin_conciliacao'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_conc_mov', 'fin_conciliacao'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_elim_log_periodo', 'fin_eliminacoes_log'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_orc_periodo', 'fin_orcamento'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_analise_cr_unique', 'fin_analise_cr_dimensoes'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_analise_cp_unique', 'fin_analise_cp_dimensoes'),
  ('financeiro_v2', 'index', 'public', 'idx_fin_kpi_trib_periodo', 'fin_kpi_tributario'),
  ('financeiro_v2', 'function', 'public', 'fin_refresh_analise_dimensoes', ''),
  ('financeiro_v2', 'function', 'public', 'fin_user_can_access', ''),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_fechamentos_service', 'fin_fechamentos'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_fechamento_log_service', 'fin_fechamento_log'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_conciliacao_service', 'fin_conciliacao'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_elim_service', 'fin_eliminacoes_intercompany'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_elim_log_service', 'fin_eliminacoes_log'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_orc_service', 'fin_orcamento'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_forecast_service', 'fin_forecast'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_perm_service', 'fin_permissoes'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_kpi_trib_service', 'fin_kpi_tributario'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_fechamentos_user', 'fin_fechamentos'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_fechamento_log_user', 'fin_fechamento_log'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_conciliacao_user', 'fin_conciliacao'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_elim_user', 'fin_eliminacoes_intercompany'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_elim_log_user', 'fin_eliminacoes_log'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_orc_user', 'fin_orcamento'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_forecast_user', 'fin_forecast'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_perm_user', 'fin_permissoes'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_kpi_trib_user', 'fin_kpi_tributario'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_orc_write', 'fin_orcamento'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_conc_write', 'fin_conciliacao'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_elim_write', 'fin_eliminacoes_intercompany'),
  ('financeiro_v2', 'rls_policy', 'public', 'fin_fech_write', 'fin_fechamentos'),
  ('financeiro_v3_backend', 'table', 'public', 'fin_sync_checkpoint', ''),
  ('financeiro_v3_backend', 'table', 'public', 'fin_confiabilidade', ''),
  ('financeiro_v3_backend', 'index', 'public', 'idx_fin_conf_periodo', 'fin_confiabilidade'),
  ('financeiro_v3_backend', 'function', 'public', 'fin_calcular_confiabilidade', ''),
  ('financeiro_v3_backend', 'function', 'public', 'fin_projecao_13_semanas', ''),
  ('financeiro_v3_backend', 'function', 'public', 'fin_consolidado_intercompany', ''),
  ('financeiro_v3_backend', 'rls_policy', 'public', 'fin_sync_ckpt_service', 'fin_sync_checkpoint'),
  ('financeiro_v3_backend', 'rls_policy', 'public', 'fin_sync_ckpt_user', 'fin_sync_checkpoint'),
  ('financeiro_v3_backend', 'rls_policy', 'public', 'fin_conf_service', 'fin_confiabilidade'),
  ('financeiro_v3_backend', 'rls_policy', 'public', 'fin_conf_user', 'fin_confiabilidade'),
  ('vendor_sip_credentials', 'table', 'public', 'vendor_sip_credentials', ''),
  ('vendor_sip_credentials', 'index', 'public', 'idx_vendor_sip_credentials_user_id', 'vendor_sip_credentials'),
  ('vendor_sip_credentials', 'function', 'public', 'update_vendor_sip_credentials_updated_at', ''),
  ('vendor_sip_credentials', 'trigger', 'public', 'vendor_sip_credentials_updated_at_trigger', 'vendor_sip_credentials'),
  ('user_departments', 'table', 'public', 'user_departments', ''),
  ('user_departments', 'index', 'public', 'idx_user_departments_user', 'user_departments'),
  ('user_departments', 'index', 'public', 'idx_user_departments_dept', 'user_departments'),
  ('user_departments', 'rls_policy', 'public', 'user_departments_read_own', 'user_departments'),
  ('user_departments', 'rls_policy', 'public', 'user_departments_master_all', 'user_departments'),
  ('user_departments', 'rls_policy', 'public', 'user_departments_service_all', 'user_departments'),
  ('dashboard_visits', 'table', 'public', 'dashboard_visits', ''),
  ('dashboard_visits', 'index', 'public', 'idx_dashboard_visits_user_recent', 'dashboard_visits'),
  ('dashboard_visits', 'rls_policy', 'public', 'dashboard_visits_user_insert', 'dashboard_visits'),
  ('dashboard_visits', 'rls_policy', 'public', 'dashboard_visits_user_read', 'dashboard_visits'),
  ('dashboard_visits', 'rls_policy', 'public', 'dashboard_visits_master_read', 'dashboard_visits'),
  ('dashboard_visits', 'rls_policy', 'public', 'dashboard_visits_service_all', 'dashboard_visits'),
  ('farmer_calls_persist_session', 'index', 'public', 'idx_farmer_calls_has_transcript', 'farmer_calls'),
  ('kb_foundation', 'table', 'public', 'kb_documents', ''),
  ('kb_foundation', 'table', 'public', 'kb_chunks', ''),
  ('kb_foundation', 'index', 'public', 'idx_kb_chunks_embedding', 'kb_chunks'),
  ('kb_foundation', 'index', 'public', 'idx_kb_documents_status_type', 'kb_documents'),
  ('kb_foundation', 'index', 'public', 'idx_kb_chunks_document', 'kb_chunks'),
  ('kb_foundation', 'function', 'public', 'kb_documents_set_updated_at', ''),
  ('kb_foundation', 'trigger', 'public', 'trg_kb_documents_updated_at', 'kb_documents'),
  ('kb_foundation', 'rls_policy', 'public', 'kb_documents_select_staff', 'kb_documents'),
  ('kb_foundation', 'rls_policy', 'public', 'kb_documents_insert_staff', 'kb_documents'),
  ('kb_foundation', 'rls_policy', 'public', 'kb_documents_update_master', 'kb_documents'),
  ('kb_foundation', 'rls_policy', 'public', 'kb_documents_delete_master', 'kb_documents'),
  ('kb_foundation', 'rls_policy', 'public', 'kb_chunks_select_staff', 'kb_chunks'),
  ('kb_foundation', 'rls_policy', 'storage', 'kb_bucket_select_staff', 'objects'),
  ('kb_foundation', 'rls_policy', 'storage', 'kb_bucket_insert_staff', 'objects'),
  ('kb_foundation', 'rls_policy', 'storage', 'kb_bucket_delete_master', 'objects'),
  ('kb_specs_and_competitors', 'table', 'public', 'kb_product_specs', ''),
  ('kb_specs_and_competitors', 'table', 'public', 'kb_competitors', ''),
  ('kb_specs_and_competitors', 'table', 'public', 'kb_competitor_products', ''),
  ('kb_specs_and_competitors', 'index', 'public', 'idx_kb_product_specs_product_code', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'index', 'public', 'idx_kb_product_specs_supplier_line', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'index', 'public', 'idx_kb_competitor_products_competitor', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'index', 'public', 'idx_kb_competitor_products_equivalent', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'function', 'public', 'kb_documents_set_updated_at', ''),
  ('kb_specs_and_competitors', 'trigger', 'public', 'trg_kb_product_specs_updated_at', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'trigger', 'public', 'trg_kb_competitors_updated_at', 'kb_competitors'),
  ('kb_specs_and_competitors', 'trigger', 'public', 'trg_kb_competitor_products_updated_at', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_product_specs_select_staff', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_product_specs_insert_staff', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_product_specs_update_master', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_product_specs_delete_master', 'kb_product_specs'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitors_select_staff', 'kb_competitors'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitors_insert_staff', 'kb_competitors'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitors_update_staff', 'kb_competitors'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitors_delete_master', 'kb_competitors'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitor_products_select_staff', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitor_products_insert_staff', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitor_products_update_staff', 'kb_competitor_products'),
  ('kb_specs_and_competitors', 'rls_policy', 'public', 'kb_competitor_products_delete_master', 'kb_competitor_products'),
  ('customer_processes', 'table', 'public', 'customer_processes', ''),
  ('customer_processes', 'index', 'public', 'idx_customer_processes_one_current', 'customer_processes'),
  ('customer_processes', 'index', 'public', 'idx_customer_processes_customer', 'customer_processes'),
  ('customer_processes', 'index', 'public', 'idx_customer_processes_segmento', 'customer_processes'),
  ('customer_processes', 'trigger', 'public', 'trg_customer_processes_updated_at', 'customer_processes'),
  ('customer_processes', 'rls_policy', 'public', 'customer_processes_select_staff', 'customer_processes'),
  ('customer_processes', 'rls_policy', 'public', 'customer_processes_insert_staff', 'customer_processes'),
  ('customer_processes', 'rls_policy', 'public', 'customer_processes_update_staff', 'customer_processes'),
  ('customer_processes', 'rls_policy', 'public', 'customer_processes_delete_master', 'customer_processes'),
  ('standard_processes', 'table', 'public', 'standard_processes', ''),
  ('standard_processes', 'index', 'public', 'idx_standard_processes_status_segmento', 'standard_processes'),
  ('standard_processes', 'index', 'public', 'idx_standard_processes_published_segmento', 'standard_processes'),
  ('standard_processes', 'index', 'public', 'idx_standard_processes_slug', 'standard_processes'),
  ('standard_processes', 'trigger', 'public', 'trg_standard_processes_updated_at', 'standard_processes'),
  ('standard_processes', 'rls_policy', 'public', 'standard_processes_select_visible', 'standard_processes'),
  ('standard_processes', 'rls_policy', 'public', 'standard_processes_insert_staff', 'standard_processes'),
  ('standard_processes', 'rls_policy', 'public', 'standard_processes_update_owner_or_master', 'standard_processes'),
  ('standard_processes', 'rls_policy', 'public', 'standard_processes_delete_master', 'standard_processes'),
  ('rag_chunks', 'table', 'public', 'rag_chunks', ''),
  ('rag_chunks', 'index', 'public', 'idx_rag_chunks_embedding', 'rag_chunks'),
  ('rag_chunks', 'index', 'public', 'idx_rag_chunks_source', 'rag_chunks'),
  ('rag_chunks', 'index', 'public', 'idx_rag_chunks_metadata_segmento', 'rag_chunks'),
  ('rag_chunks', 'rls_policy', 'public', 'rag_chunks_select_staff', 'rag_chunks'),
  ('customer_contacts', 'table', 'public', 'customer_contacts', ''),
  ('customer_contacts', 'index', 'public', 'idx_customer_contacts_customer', 'customer_contacts'),
  ('customer_contacts', 'index', 'public', 'idx_customer_contacts_phone', 'customer_contacts'),
  ('customer_contacts', 'index', 'public', 'idx_customer_contacts_one_primary', 'customer_contacts'),
  ('customer_contacts', 'index', 'public', 'idx_customer_contacts_birthday', 'customer_contacts'),
  ('customer_contacts', 'trigger', 'public', 'trg_customer_contacts_updated_at', 'customer_contacts'),
  ('customer_contacts', 'rls_policy', 'public', 'customer_contacts_select_staff', 'customer_contacts'),
  ('customer_contacts', 'rls_policy', 'public', 'customer_contacts_insert_staff', 'customer_contacts'),
  ('customer_contacts', 'rls_policy', 'public', 'customer_contacts_update_staff', 'customer_contacts'),
  ('customer_contacts', 'rls_policy', 'public', 'customer_contacts_delete_master', 'customer_contacts'),
  ('fin_audit_log', 'table', 'public', 'fin_audit_log', ''),
  ('fin_audit_log', 'index', 'public', 'fin_audit_log_table_row_idx', 'fin_audit_log'),
  ('fin_audit_log', 'index', 'public', 'fin_audit_log_company_period_idx', 'fin_audit_log'),
  ('fin_audit_log', 'index', 'public', 'fin_audit_log_user_idx', 'fin_audit_log'),
  ('fin_audit_log', 'rls_policy', 'public', 'fin_audit_log_select_staff', 'fin_audit_log'),
  ('fin_audit_trigger', 'function', 'public', 'fin_audit_trigger', ''),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_contas_receber'),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_contas_pagar'),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_categoria_dre_mapping'),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_orcamento'),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_fechamentos'),
  ('fin_audit_attach', 'trigger', 'public', 'trg_audit', 'fin_eliminacoes_intercompany'),
  ('set_config_rpc', 'function', 'public', 'set_config', ''),
  ('fin_period_overrides', 'table', 'public', 'fin_period_overrides', ''),
  ('fin_period_overrides', 'index', 'public', 'fin_period_overrides_active_idx', 'fin_period_overrides'),
  ('fin_period_overrides', 'rls_policy', 'public', 'fin_period_overrides_select_staff', 'fin_period_overrides'),
  ('fin_period_overrides', 'rls_policy', 'public', 'fin_period_overrides_insert_master', 'fin_period_overrides'),
  ('fin_period_overrides', 'rls_policy', 'public', 'fin_period_overrides_update_self', 'fin_period_overrides'),
  ('fin_period_lock_trigger', 'function', 'public', 'fin_period_lock_trigger', ''),
  ('fin_period_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_contas_receber'),
  ('fin_period_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_contas_pagar'),
  ('fin_period_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_movimentacoes'),
  ('fin_period_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_categoria_dre_mapping'),
  ('fin_period_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_orcamento'),
  ('fin_mapping_gate_trigger', 'function', 'public', 'fin_check_mapping_complete_trigger', ''),
  ('fin_mapping_gate_trigger', 'trigger', 'public', 'trg_mapping_gate', 'fin_fechamentos'),
  ('rpc_categorias_sem_mapping', 'function', 'public', 'fin_categorias_sem_mapping', ''),
  ('fin_ic_matches', 'table', 'public', 'fin_ic_matches', ''),
  ('fin_ic_matches', 'index', 'public', 'fin_ic_matches_status_idx', 'fin_ic_matches'),
  ('fin_ic_matches', 'index', 'public', 'fin_ic_matches_cr_idx', 'fin_ic_matches'),
  ('fin_ic_matches', 'index', 'public', 'fin_ic_matches_cp_idx', 'fin_ic_matches'),
  ('fin_ic_matches', 'index', 'public', 'fin_ic_matches_cr_unique', 'fin_ic_matches'),
  ('fin_ic_matches', 'index', 'public', 'fin_ic_matches_cp_unique', 'fin_ic_matches'),
  ('fin_ic_matches', 'rls_policy', 'public', 'fin_ic_matches_select_staff', 'fin_ic_matches'),
  ('fin_ic_matches', 'rls_policy', 'public', 'fin_ic_matches_update_staff', 'fin_ic_matches'),
  ('company_cnpjs', 'table', 'public', 'company_cnpjs', ''),
  ('company_cnpjs', 'index', 'public', 'company_cnpjs_normalized_idx', 'company_cnpjs'),
  ('company_cnpjs', 'rls_policy', 'public', 'company_cnpjs_select_authenticated', 'company_cnpjs'),
  ('company_cnpjs', 'rls_policy', 'public', 'company_cnpjs_master_write', 'company_cnpjs'),
  ('fin_consolidado_v2', 'function', 'public', 'fin_consolidado_intercompany', ''),
  ('commercial_role_add_values', 'enum_value', 'public', 'farmer', 'commercial_role'),
  ('commercial_role_add_values', 'enum_value', 'public', 'hunter', 'commercial_role'),
  ('commercial_role_add_values', 'enum_value', 'public', 'closer', 'commercial_role'),
  ('commercial_role_add_values', 'enum_value', 'public', 'master', 'commercial_role'),
  ('scoring_v2_signal_modifiers', 'table', 'public', 'score_recalc_queue', ''),
  ('scoring_v2_signal_modifiers', 'index', 'public', 'idx_score_recalc_queue_pending', 'score_recalc_queue'),
  ('scoring_v2_signal_modifiers', 'index', 'public', 'uniq_score_recalc_queue_pending', 'score_recalc_queue'),
  ('scoring_v2_signal_modifiers', 'function', 'public', 'enqueue_score_recalc_from_call', ''),
  ('scoring_v2_signal_modifiers', 'trigger', 'public', 'trg_farmer_calls_enqueue_recalc', 'farmer_calls'),
  ('visit_intelligence_v1', 'table', 'public', 'customer_visit_scores', ''),
  ('visit_intelligence_v1', 'table', 'public', 'visit_score_recalc_queue', ''),
  ('visit_intelligence_v1', 'index', 'public', 'idx_visit_scores_farmer_priority', 'customer_visit_scores'),
  ('visit_intelligence_v1', 'index', 'public', 'idx_visit_scores_farmer_city', 'customer_visit_scores'),
  ('visit_intelligence_v1', 'index', 'public', 'idx_visit_score_queue_pending', 'visit_score_recalc_queue'),
  ('visit_intelligence_v1', 'index', 'public', 'uniq_visit_score_queue_pending', 'visit_score_recalc_queue'),
  ('visit_intelligence_v1', 'function', 'public', 'enqueue_visit_score_recalc_from_visit', ''),
  ('visit_intelligence_v1', 'function', 'public', 'enqueue_visit_score_recalc_from_client_score', ''),
  ('visit_intelligence_v1', 'trigger', 'public', 'trg_route_visits_enqueue_visit_recalc', 'route_visits'),
  ('visit_intelligence_v1', 'trigger', 'public', 'trg_farmer_client_scores_enqueue_visit_recalc', 'farmer_client_scores'),
  ('fin_a1_eventos', 'table', 'public', 'fin_eventos_recorrentes', ''),
  ('fin_a1_eventos', 'table', 'public', 'fin_eventos_eventuais', ''),
  ('fin_a1_eventos', 'index', 'public', 'fin_eventos_rec_company_ativo_idx', 'fin_eventos_recorrentes'),
  ('fin_a1_eventos', 'index', 'public', 'fin_eventos_rec_categoria_idx', 'fin_eventos_recorrentes'),
  ('fin_a1_eventos', 'index', 'public', 'fin_eventos_ev_company_data_idx', 'fin_eventos_eventuais'),
  ('fin_a1_eventos', 'index', 'public', 'fin_eventos_ev_status_idx', 'fin_eventos_eventuais'),
  ('fin_a1_eventos', 'rls_policy', 'public', 'fin_eventos_rec_select_staff', 'fin_eventos_recorrentes'),
  ('fin_a1_eventos', 'rls_policy', 'public', 'fin_eventos_rec_write_staff', 'fin_eventos_recorrentes'),
  ('fin_a1_eventos', 'rls_policy', 'public', 'fin_eventos_ev_select_staff', 'fin_eventos_eventuais'),
  ('fin_a1_eventos', 'rls_policy', 'public', 'fin_eventos_ev_write_staff', 'fin_eventos_eventuais'),
  ('fin_a1_snapshots_alertas_config', 'table', 'public', 'fin_projecao_snapshots', ''),
  ('fin_a1_snapshots_alertas_config', 'table', 'public', 'fin_alertas', ''),
  ('fin_a1_snapshots_alertas_config', 'table', 'public', 'fin_config_cashflow', ''),
  ('fin_a1_snapshots_alertas_config', 'index', 'public', 'fin_proj_company_snap_idx', 'fin_projecao_snapshots'),
  ('fin_a1_snapshots_alertas_config', 'index', 'public', 'fin_proj_cenario_idx', 'fin_projecao_snapshots'),
  ('fin_a1_snapshots_alertas_config', 'index', 'public', 'fin_alertas_company_criado_idx', 'fin_alertas'),
  ('fin_a1_snapshots_alertas_config', 'index', 'public', 'fin_alertas_unique_ativo', 'fin_alertas'),
  ('fin_a1_snapshots_alertas_config', 'rls_policy', 'public', 'fin_proj_select_staff', 'fin_projecao_snapshots'),
  ('fin_a1_snapshots_alertas_config', 'rls_policy', 'public', 'fin_alertas_select_staff', 'fin_alertas'),
  ('fin_a1_snapshots_alertas_config', 'rls_policy', 'public', 'fin_alertas_update_staff', 'fin_alertas'),
  ('fin_a1_snapshots_alertas_config', 'rls_policy', 'public', 'fin_config_select_staff', 'fin_config_cashflow'),
  ('fin_a1_snapshots_alertas_config', 'rls_policy', 'public', 'fin_config_write_master', 'fin_config_cashflow'),
  ('fin_a1_audit_lock_attach', 'function', 'public', 'fin_period_lock_trigger', ''),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_audit', 'fin_eventos_recorrentes'),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_audit', 'fin_eventos_eventuais'),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_audit', 'fin_alertas'),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_audit', 'fin_config_cashflow'),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_eventos_recorrentes'),
  ('fin_a1_audit_lock_attach', 'trigger', 'public', 'trg_period_lock', 'fin_eventos_eventuais'),
  ('fin_onda1_ncg', 'table', 'public', 'fin_estoque_valor', ''),
  ('fin_onda1_ncg', 'index', 'public', 'fin_estoque_valor_company_data_idx', 'fin_estoque_valor'),
  ('fin_onda1_ncg', 'function', 'public', 'fin_period_lock_trigger', ''),
  ('fin_onda1_ncg', 'function', 'public', 'fin_estimar_estoque_omie', ''),
  ('fin_onda1_ncg', 'trigger', 'public', 'trg_audit', 'fin_estoque_valor'),
  ('fin_onda1_ncg', 'trigger', 'public', 'trg_period_lock', 'fin_estoque_valor'),
  ('fin_onda1_ncg', 'rls_policy', 'public', 'fin_estoque_valor_select_staff', 'fin_estoque_valor'),
  ('fin_onda1_ncg', 'rls_policy', 'public', 'fin_estoque_valor_write_master', 'fin_estoque_valor'),
  ('scoring_visit_p1_fixes', 'function', 'public', 'enqueue_visit_score_recalc_from_visit', ''),
  ('scoring_visit_p1_fixes', 'function', 'public', 'enqueue_visit_score_recalc_from_client_score', ''),
  ('call_log', 'table', 'public', 'call_log', ''),
  ('call_log', 'index', 'public', 'uq_call_log_provider_call_id', 'call_log'),
  ('call_log', 'index', 'public', 'uq_call_log_sip_call_id', 'call_log'),
  ('call_log', 'index', 'public', 'idx_call_log_farmer_started', 'call_log'),
  ('call_log', 'index', 'public', 'idx_call_log_missed_unack', 'call_log'),
  ('call_log', 'cron_job', 'cron', 'call-log-missed-backstop', ''),
  ('fin_a2_valor_inputs', 'table', 'public', 'fin_valor_inputs', ''),
  ('fin_a2_valor_inputs', 'rls_policy', 'public', 'fin_valor_inputs_select_master', 'fin_valor_inputs'),
  ('fin_a2_valor_inputs', 'rls_policy', 'public', 'fin_valor_inputs_write_master', 'fin_valor_inputs'),
  ('crons_scoring_visit_lendo_cron_secret_do_vault', 'cron_job', 'cron', 'scoring-recalc-batch-nightly', ''),
  ('crons_scoring_visit_lendo_cron_secret_do_vault', 'cron_job', 'cron', 'visit-score-recalc-batch-nightly', ''),
  ('cron_financeiro_e_fix_sayerlack', 'cron_job', 'cron', 'fin-omie-sync-2x-diario', ''),
  ('cron_financeiro_e_fix_sayerlack', 'cron_job', 'cron', 'sayerlack-portal-watchdog', ''),
  ('fix_fin_triggers_json_field_access', 'function', 'public', 'fin_audit_trigger', ''),
  ('fix_fin_triggers_json_field_access', 'function', 'public', 'fin_period_lock_trigger', ''),
  ('carteira_omie_fase1', 'table', 'public', 'omie_vendedor_map', ''),
  ('carteira_omie_fase1', 'table', 'public', 'carteira_assignments', ''),
  ('carteira_omie_fase1', 'table', 'public', 'carteira_coverage', ''),
  ('carteira_omie_fase1', 'index', 'public', 'idx_omie_vendedor_map_codigo', 'omie_vendedor_map'),
  ('carteira_omie_fase1', 'index', 'public', 'idx_carteira_owner', 'carteira_assignments'),
  ('carteira_omie_fase1', 'index', 'public', 'idx_carteira_owner_eligible', 'carteira_assignments'),
  ('carteira_omie_fase1', 'index', 'public', 'idx_coverage_covering_active', 'carteira_coverage'),
  ('carteira_omie_fase1', 'function', 'public', 'carteira_visivel_para', ''),
  ('carteira_omie_fase1', 'function', 'public', 'minha_carteira', ''),
  ('fin_regime_inputs', 'table', 'public', 'fin_regime_inputs', ''),
  ('fin_regime_inputs', 'rls_policy', 'public', 'fin_regime_inputs_select_master', 'fin_regime_inputs'),
  ('fin_regime_inputs', 'rls_policy', 'public', 'fin_regime_inputs_write_master', 'fin_regime_inputs'),
  ('scores_unique_por_cliente', 'index', 'public', 'idx_fcs_customer', 'farmer_client_scores'),
  ('scores_unique_por_cliente', 'index', 'public', 'idx_cvs_customer', 'customer_visit_scores'),
  ('carteira_scores_owner_e_filas', 'index', 'public', 'uniq_score_recalc_queue_pending', 'score_recalc_queue'),
  ('carteira_scores_owner_e_filas', 'index', 'public', 'uniq_visit_score_queue_pending', 'visit_score_recalc_queue'),
  ('carteira_scores_owner_e_filas', 'function', 'public', 'enqueue_score_recalc_from_call', ''),
  ('carteira_scores_owner_e_filas', 'function', 'public', 'enqueue_visit_score_recalc_from_visit', ''),
  ('carteira_scores_owner_e_filas', 'function', 'public', 'enqueue_visit_score_recalc_from_client_score', ''),
  ('tuning_crons_estoque_freq_e_timeouts', 'cron_job', 'cron', 'omie-sync-estoque-diario', ''),
  ('tuning_crons_estoque_freq_e_timeouts', 'cron_job', 'cron', 'sync-orders-vendas-2h', ''),
  ('tuning_crons_estoque_freq_e_timeouts', 'cron_job', 'cron', 'sync-products-customers-daily', ''),
  ('tuning_crons_estoque_freq_e_timeouts', 'cron_job', 'cron', 'sync-inventory-vendas-30m', ''),
  ('tuning_crons_estoque_freq_e_timeouts', 'cron_job', 'cron', 'sync-omie-services-hourly', ''),
  ('rpc_staff_guard_permite_cron_backend', 'function', 'public', 'sugerir_negociacao_paralela_hoje', ''),
  ('rpc_staff_guard_permite_cron_backend', 'function', 'public', 'refresh_sku_ranking_negociacao', ''),
  ('fin_crons_por_entidade', 'cron_job', 'cron', 'fin-sync-base-diario', ''),
  ('fin_crons_por_entidade', 'cron_job', 'cron', 'fin-sync-cp-2x', ''),
  ('fin_crons_por_entidade', 'cron_job', 'cron', 'fin-sync-cr-2x', ''),
  ('fin_crons_por_entidade', 'cron_job', 'cron', 'fin-sync-mov-2x', ''),
  ('fin_audit_skip_service_role', 'function', 'public', 'fin_audit_trigger', ''),
  ('fin_sync_cursor', 'table', 'public', 'fin_sync_cursor', ''),
  ('fin_sync_cursor', 'index', 'public', 'idx_fin_sync_cursor_pendentes', 'fin_sync_cursor'),
  ('fin_sync_cursor', 'cron_job', 'cron', 'fin-sync-continuacao-10min', ''),
  ('fin_sync_cursor', 'rls_policy', 'public', 'fin_sync_cursor_select_staff', 'fin_sync_cursor'),
  ('fin_sync_cursor', 'rls_policy', 'public', 'fin_sync_cursor_service_all', 'fin_sync_cursor'),
  ('fin_rpc_gate_auth_p1', 'function', 'public', 'fin_calcular_confiabilidade', ''),
  ('fin_rpc_gate_auth_p1', 'function', 'public', 'fin_categorias_sem_mapping', ''),
  ('fin_rpc_gate_auth_p1', 'function', 'public', 'fin_consolidado_intercompany', ''),
  ('fin_rpc_gate_auth_p1', 'function', 'public', 'fin_estimar_estoque_omie', ''),
  ('positivacao_kpis', 'table', 'public', 'carteira_positivacao_snapshot', ''),
  ('positivacao_kpis', 'index', 'public', 'idx_sales_orders_kpi_date', 'sales_orders'),
  ('positivacao_kpis', 'function', 'public', 'get_minha_positivacao', ''),
  ('fin_analise_dimensoes_rpc', 'function', 'public', 'fin_analise_cr_dimensoes_rpc', ''),
  ('fin_analise_dimensoes_rpc', 'function', 'public', 'fin_analise_cp_dimensoes_rpc', ''),
  ('fin_refresh_analise_dimensoes_cron', 'cron_job', 'cron', 'fin-refresh-analise-dimensoes', ''),
  ('carteira_saude_rpc', 'function', 'public', 'get_carteira_saude', ''),
  ('mixgap_rpc', 'function', 'public', 'get_meu_mixgap', ''),
  ('fin_sync_watchdog', 'function', 'public', 'fin_sync_watchdog_check', ''),
  ('fin_sync_watchdog', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('fin_sync_watchdog', 'cron_job', 'cron', 'fin-sync-watchdog', ''),
  ('fin_sync_watchdog', 'cron_job', 'cron', 'fin-sync-heartbeat', ''),
  ('viewas_rpcs_for', 'function', 'public', '_carteira_mixgap_for_owner', ''),
  ('viewas_rpcs_for', 'function', 'public', 'get_meu_mixgap', ''),
  ('viewas_rpcs_for', 'function', 'public', 'get_meu_mixgap_for', ''),
  ('viewas_rpcs_for', 'function', 'public', '_carteira_positivacao_for_owner', ''),
  ('viewas_rpcs_for', 'function', 'public', 'get_minha_positivacao', ''),
  ('viewas_rpcs_for', 'function', 'public', 'get_minha_positivacao_for', ''),
  ('viewas_access_targets', 'function', 'public', 'get_user_access_profile_for', ''),
  ('viewas_access_targets', 'function', 'public', 'list_impersonation_targets', ''),
  ('impersonation_audit', 'table', 'public', 'impersonation_audit', ''),
  ('impersonation_audit', 'function', 'public', 'log_impersonation_start', ''),
  ('impersonation_audit', 'function', 'public', 'end_impersonation', ''),
  ('rls_score_carteira_hardening', 'function', 'public', 'pode_ver_carteira_completa', ''),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'fcs_select_carteira', 'farmer_client_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'fcs_insert_own_or_gestor', 'farmer_client_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'fcs_update_own_or_gestor', 'farmer_client_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'fcs_delete_own_or_gestor', 'farmer_client_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'cvs_select_carteira', 'customer_visit_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'cvs_insert_own_or_gestor', 'customer_visit_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'cvs_update_own_or_gestor', 'customer_visit_scores'),
  ('rls_score_carteira_hardening', 'rls_policy', 'public', 'cvs_delete_own_or_gestor', 'customer_visit_scores'),
  ('fin_sync_watchdog_sweep_orphans', 'function', 'public', 'fin_sync_watchdog_check', ''),
  ('rls_carteira_relacionamento_hardening', 'function', 'public', 'pode_ver_carteira_completa', ''),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'frec_select_carteira', 'farmer_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'frec_insert_own_or_gestor', 'farmer_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'frec_update_own_or_gestor', 'farmer_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'frec_delete_own_or_gestor', 'farmer_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fbrec_select_carteira', 'farmer_bundle_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fbrec_insert_own_or_gestor', 'farmer_bundle_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fbrec_update_own_or_gestor', 'farmer_bundle_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fbrec_delete_own_or_gestor', 'farmer_bundle_recommendations'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcall_select_carteira', 'farmer_calls'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcall_insert_own_or_gestor', 'farmer_calls'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcall_update_own_or_gestor', 'farmer_calls'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcall_delete_own_or_gestor', 'farmer_calls'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'rvis_select_carteira', 'route_visits'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'rvis_insert_own_or_gestor', 'route_visits'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'rvis_update_own_or_gestor', 'route_visits'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'rvis_delete_own_or_gestor', 'route_visits'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcop_select_carteira', 'farmer_copilot_sessions'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcop_insert_own_or_gestor', 'farmer_copilot_sessions'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcop_update_own_or_gestor', 'farmer_copilot_sessions'),
  ('rls_carteira_relacionamento_hardening', 'rls_policy', 'public', 'fcop_delete_own_or_gestor', 'farmer_copilot_sessions'),
  ('fix_sayerlack_cron_vault', 'cron_job', 'cron', 'sayerlack-portal-watchdog', ''),
  ('fin_funding_inputs', 'table', 'public', 'fin_funding_inputs', ''),
  ('fin_funding_inputs', 'rls_policy', 'public', 'fin_funding_inputs_select_master', 'fin_funding_inputs'),
  ('fin_funding_inputs', 'rls_policy', 'public', 'fin_funding_inputs_write_master', 'fin_funding_inputs'),
  ('data_health_rpc', 'function', 'public', 'get_data_health', ''),
  ('mixgap_feedback', 'table', 'public', 'farmer_mixgap_feedback', ''),
  ('mixgap_feedback', 'function', 'public', 'mark_mixgap_feedback', ''),
  ('mixgap_feedback', 'function', 'public', '_carteira_mixgap_for_owner', ''),
  ('rls_copilot_sessions_select_own_only', 'rls_policy', 'public', 'fcop_select_carteira', 'farmer_copilot_sessions'),
  ('clientes_nao_vinculados', 'table', 'public', 'omie_clientes_nao_vinculados', ''),
  ('clientes_nao_vinculados', 'table', 'public', 'omie_nao_vinculados_state', ''),
  ('clientes_nao_vinculados', 'index', 'public', 'idx_nv_empresa_synced', 'omie_clientes_nao_vinculados'),
  ('clientes_nao_vinculados', 'function', 'public', 'finalize_nao_vinculados_snapshot', ''),
  ('clientes_nao_vinculados', 'rls_policy', 'public', 'nv_select', 'omie_clientes_nao_vinculados'),
  ('clientes_nao_vinculados', 'rls_policy', 'public', 'nv_state_select', 'omie_nao_vinculados_state'),
  ('data_health_rpc_fix', 'function', 'public', 'get_data_health', ''),
  ('cron_vendas_sync_pedidos', 'cron_job', 'cron', 'vendas-sync-pedidos-oben-2h', ''),
  ('cron_vendas_sync_pedidos', 'cron_job', 'cron', 'vendas-sync-pedidos-colacor-2h', ''),
  ('matview_ranking_negociacao_private', 'function', 'public', 'refresh_sku_ranking_negociacao', ''),
  ('matview_ranking_negociacao_private', 'function', 'public', 'get_sku_ranking_negociacao_paralela', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'carteira-positivacao-snapshot-mensal', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'carteira-rebuild-nightly', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'compute-association-rules-daily', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'compute-costs-daily', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'monthly-tool-report', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'omie-sync-metadados-daily', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'omie-sync-status-produtos-diario', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'process-recurring-orders-daily', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'sayerlack-portal-watchdog', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'sync-colacor-vendas-products', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'sync-reprocess-operational', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'sync-reprocess-strategic', ''),
  ('crons_timeout_fix', 'cron_job', 'cron', 'weekly-algorithm-a-audit', ''),
  ('data_health_add_vendas', 'function', 'public', 'get_data_health', ''),
  ('get_tint_price_rpc', 'function', 'public', 'get_tint_price', ''),
  ('data_health_add_estoque_reposicao', 'function', 'public', 'get_data_health', ''),
  ('data_health_compute_internal', 'function', 'public', '_data_health_compute', ''),
  ('data_health_compute_internal', 'function', 'public', 'get_data_health', ''),
  ('data_health_watchdog', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_watchdog', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('data_health_watchdog', 'cron_job', 'cron', 'data-health-watchdog', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_ciclo_oportunidade_diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_dispatch_notificacoes_diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_estados_eventos_diarios', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_limpeza_sugestoes_mensal', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_omie_oben_sku_items_history_daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_omie_oben_sync_incremental_2h', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_ranking_refresh_semanal', ''),
  ('cron_baseline', 'cron_job', 'cron', 'afiacao_sugestoes_diarias', ''),
  ('cron_baseline', 'cron_job', 'cron', 'call-log-missed-backstop', ''),
  ('cron_baseline', 'cron_job', 'cron', 'carteira-positivacao-snapshot-mensal', ''),
  ('cron_baseline', 'cron_job', 'cron', 'carteira-rebuild-nightly', ''),
  ('cron_baseline', 'cron_job', 'cron', 'compute-association-rules-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'compute-costs-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'daily-calculate-scores', ''),
  ('cron_baseline', 'cron_job', 'cron', 'data-health-watchdog', ''),
  ('cron_baseline', 'cron_job', 'cron', 'detectar-outliers-diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'disparar-pedidos-aprovados-oben', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-cashflow-snapshot-diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-ic-reconcile-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-refresh-analise-dimensoes', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-base-diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-continuacao-10min', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-cp-2x', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-cr-2x', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-heartbeat', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-mov-2x', ''),
  ('cron_baseline', 'cron_job', 'cron', 'fin-sync-watchdog', ''),
  ('cron_baseline', 'cron_job', 'cron', 'gerar-pedidos-diario-oben', ''),
  ('cron_baseline', 'cron_job', 'cron', 'monthly-tool-report', ''),
  ('cron_baseline', 'cron_job', 'cron', 'omie-sync-estoque-diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'omie-sync-metadados-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'omie-sync-status-produtos-diario', ''),
  ('cron_baseline', 'cron_job', 'cron', 'process-recurring-orders-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sayerlack-portal-watchdog', ''),
  ('cron_baseline', 'cron_job', 'cron', 'scoring-recalc-batch-nightly', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-colacor-vendas-products', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-inventory-vendas-30m', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-omie-services-hourly', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-products-customers-daily', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-reprocess-operational', ''),
  ('cron_baseline', 'cron_job', 'cron', 'sync-reprocess-strategic', ''),
  ('cron_baseline', 'cron_job', 'cron', 'vendas-sync-pedidos-colacor-2h', ''),
  ('cron_baseline', 'cron_job', 'cron', 'vendas-sync-pedidos-oben-2h', ''),
  ('cron_baseline', 'cron_job', 'cron', 'visit-score-recalc-batch-nightly', ''),
  ('cron_baseline', 'cron_job', 'cron', 'weekly-algorithm-a-audit', ''),
  ('dispatch_notifications_frequente', 'cron_job', 'cron', 'afiacao_dispatch_notificacoes_30min', ''),
  ('data_health_alert_channel', 'function', 'public', '_data_health_compute', ''),
  ('data_health_alert_channel', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('data_health_checks_high', 'function', 'public', '_data_health_compute', ''),
  ('data_health_checks_high', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_checks_high', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('nao_vinculados_cron', 'cron_job', 'cron', 'nao-vinculados-refresh-diario', ''),
  ('data_health_vendas_cadastros_dado', 'function', 'public', '_data_health_compute', ''),
  ('fin_sync_watchdog_tail_failing', 'function', 'public', 'fin_sync_watchdog_check', ''),
  ('cron_sync_customers_dedicated', 'cron_job', 'cron', 'sync-customers-vendas-daily', ''),
  ('data_health_reposicao_acoes', 'function', 'public', '_data_health_compute', ''),
  ('data_health_reposicao_acoes', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('cron_sayerlack_lote_retry', 'cron_job', 'cron', 'sayerlack-portal-lote-retry', ''),
  ('sayerlack_retry_motor', 'table', 'public', 'sayerlack_retry_motor_log', ''),
  ('sayerlack_retry_motor', 'function', 'public', 'sayerlack_retry_orfaos', ''),
  ('sayerlack_retry_motor', 'cron_job', 'cron', 'sayerlack-retry-orfaos', ''),
  ('reposicao_custo_cmc_em_transito', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('fin_sync_heartbeat_tz_fix', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('tarefas_bloco_a', 'table', 'public', 'tarefas', ''),
  ('tarefas_bloco_a', 'index', 'public', 'idx_tarefas_assigned_aberta', 'tarefas'),
  ('tarefas_bloco_a', 'index', 'public', 'idx_tarefas_created_by', 'tarefas'),
  ('tarefas_bloco_a', 'index', 'public', 'idx_tarefas_customer_aberta', 'tarefas'),
  ('tarefas_bloco_a', 'index', 'public', 'idx_tarefas_aberta_auto', 'tarefas'),
  ('tarefas_bloco_b', 'table', 'public', 'tarefa_satisfacao_candidatos', ''),
  ('tarefas_bloco_b', 'table', 'public', 'tarefa_eventos', ''),
  ('tarefas_bloco_b', 'index', 'public', 'idx_candidato_tarefa_pending', 'tarefa_satisfacao_candidatos'),
  ('tarefas_bloco_b', 'index', 'public', 'idx_evento_tarefa', 'tarefa_eventos'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tarefas_select', 'tarefas'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tarefas_insert', 'tarefas'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tarefas_update', 'tarefas'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tcand_select', 'tarefa_satisfacao_candidatos'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tcand_update', 'tarefa_satisfacao_candidatos'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tevt_select', 'tarefa_eventos'),
  ('tarefas_bloco_c', 'rls_policy', 'public', 'tevt_insert', 'tarefa_eventos'),
  ('tarefas_bloco_d', 'function', 'public', 'tarefas_matcher_tick', ''),
  ('tarefas_bloco_d', 'function', 'public', 'tarefas_escalonamento_tick', ''),
  ('tarefas_bloco_d', 'cron_job', 'cron', 'tarefas-matcher-15min', ''),
  ('tarefas_bloco_d', 'cron_job', 'cron', 'tarefas-escalonamento-diario', ''),
  ('tarefas_matcher_created_at_floor', 'function', 'public', 'tarefas_matcher_tick', ''),
  ('data_health_compute_msg_tz', 'function', 'public', '_data_health_compute', ''),
  ('whatsapp_fundacao', 'table', 'public', 'whatsapp_webhook_events', ''),
  ('whatsapp_fundacao', 'table', 'public', 'whatsapp_conversations', ''),
  ('whatsapp_fundacao', 'table', 'public', 'whatsapp_messages', ''),
  ('whatsapp_fundacao', 'index', 'public', 'idx_wa_conv_customer', 'whatsapp_conversations'),
  ('whatsapp_fundacao', 'index', 'public', 'idx_wa_conv_operator', 'whatsapp_conversations'),
  ('whatsapp_fundacao', 'index', 'public', 'idx_wa_conv_last_msg', 'whatsapp_conversations'),
  ('whatsapp_fundacao', 'index', 'public', 'idx_wa_msg_conv', 'whatsapp_messages'),
  ('whatsapp_fundacao', 'rls_policy', 'public', 'wa_events_staff_select', 'whatsapp_webhook_events'),
  ('whatsapp_fundacao', 'rls_policy', 'public', 'wa_conv_staff_all', 'whatsapp_conversations'),
  ('whatsapp_fundacao', 'rls_policy', 'public', 'wa_msg_staff_all', 'whatsapp_messages'),
  ('fin_estoque_omie_feed', 'function', 'public', 'fin_estimar_estoque_omie', ''),
  ('fin_estoque_omie_feed', 'cron_job', 'cron', 'sync-inventory-colacor-vendas-1h', ''),
  ('fin_estoque_omie_feed', 'cron_job', 'cron', 'sync-inventory-servicos-1h', ''),
  ('route_fundacao', 'table', 'public', 'route_schedule', ''),
  ('route_fundacao', 'table', 'public', 'route_calendar_override', ''),
  ('route_fundacao', 'table', 'public', 'route_disparo_config', ''),
  ('route_fundacao', 'table', 'public', 'route_contact_log', ''),
  ('route_fundacao', 'index', 'public', 'idx_route_schedule_weekday', 'route_schedule'),
  ('route_fundacao', 'index', 'public', 'idx_route_contact_log_customer', 'route_contact_log'),
  ('route_fundacao', 'index', 'public', 'idx_route_contact_log_data', 'route_contact_log'),
  ('route_fundacao', 'rls_policy', 'public', 'route_sched_staff_read', 'route_schedule'),
  ('route_fundacao', 'rls_policy', 'public', 'route_sched_master_write', 'route_schedule'),
  ('route_fundacao', 'rls_policy', 'public', 'route_override_staff_read', 'route_calendar_override'),
  ('route_fundacao', 'rls_policy', 'public', 'route_override_master_write', 'route_calendar_override'),
  ('route_fundacao', 'rls_policy', 'public', 'route_config_staff_read', 'route_disparo_config'),
  ('route_fundacao', 'rls_policy', 'public', 'route_config_master_write', 'route_disparo_config'),
  ('route_fundacao', 'rls_policy', 'public', 'route_log_staff_read', 'route_contact_log'),
  ('data_health_consolida_last_error_e_reposicao_checks', 'function', 'public', '_data_health_compute', ''),
  ('data_health_consolida_last_error_e_reposicao_checks', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('visitas_agendadas', 'table', 'public', 'visitas_agendadas', ''),
  ('visitas_agendadas', 'index', 'public', 'uq_vag_pendente_cliente_vendedor_data', 'visitas_agendadas'),
  ('visitas_agendadas', 'index', 'public', 'uq_vag_route_visit_id', 'visitas_agendadas'),
  ('visitas_agendadas', 'index', 'public', 'idx_vag_scheduled_by_date', 'visitas_agendadas'),
  ('visitas_agendadas', 'index', 'public', 'idx_vag_pending_by_seller', 'visitas_agendadas'),
  ('visitas_agendadas', 'function', 'public', 'set_updated_at_visitas_agendadas', ''),
  ('visitas_agendadas', 'function', 'public', 'reconcile_visita_agendada', ''),
  ('visitas_agendadas', 'trigger', 'public', 'trg_vag_updated_at', 'visitas_agendadas'),
  ('visitas_agendadas', 'trigger', 'public', 'trg_reconcile_visita_agendada', 'route_visits'),
  ('visitas_agendadas', 'rls_policy', 'public', 'vag_select_own', 'visitas_agendadas'),
  ('visitas_agendadas', 'rls_policy', 'public', 'vag_insert_own_carteira', 'visitas_agendadas'),
  ('visitas_agendadas', 'rls_policy', 'public', 'vag_update_own_pending', 'visitas_agendadas'),
  ('visitas_agendadas', 'rls_policy', 'public', 'vag_delete_gestor', 'visitas_agendadas'),
  ('fin_watchdog_sync_stale_grace_email', 'function', 'public', 'fin_sync_watchdog_check', ''),
  ('reposicao_excluir_405ml', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('data_health_diagnostico_gate_status', 'function', 'public', '_data_health_compute', ''),
  ('fix_sku_fornecedor_externo_atualizado_em_trigger', 'function', 'public', 'set_atualizado_em_column', ''),
  ('fix_sku_fornecedor_externo_atualizado_em_trigger', 'trigger', 'public', 'sku_fornecedor_externo_set_atualizado_em', 'sku_fornecedor_externo'),
  ('data_health_portal_push', 'function', 'public', '_data_health_compute', ''),
  ('data_health_portal_push', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_portal_push', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('reposicao_preencher_parametros_faltantes', 'function', 'public', 'preencher_parametros_faltantes_skus', ''),
  ('reposicao_preencher_parametros_faltantes', 'cron_job', 'cron', 'reposicao-preencher-parametros-faltantes', ''),
  ('data_health_checks_acionaveis', 'function', 'public', '_data_health_compute', ''),
  ('reposicao_classificar_sayerlack_grupo_default', 'function', 'public', 'classificar_sayerlack_grupo_default', ''),
  ('reposicao_classificar_sayerlack_grupo_default', 'cron_job', 'cron', 'reposicao-classificar-sayerlack-grupo', ''),
  ('data_health_restaura_portal_split', 'function', 'public', '_data_health_compute', ''),
  ('data_health_restaura_portal_split', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_restaura_portal_split', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('reposicao_candidatos_primeira_compra', 'index', 'public', 'idx_vih_recorrencia_180d', 'venda_items_history'),
  ('reposicao_candidatos_primeira_compra', 'function', 'public', 'promover_candidato_primeira_compra', ''),
  ('cancelar_pedido_limpa_portal', 'function', 'public', 'cancelar_pedido_sugerido', ''),
  ('fix_portal_lock_retry_blindspot', 'function', 'public', 'envio_portal_lock_candidatos', ''),
  ('reposicao_candidatos_inclui_habilitados', 'function', 'public', 'promover_candidato_primeira_compra', ''),
  ('data_health_check_sayerlack_fabricado', 'function', 'public', '_data_health_compute', ''),
  ('data_health_check_sayerlack_fabricado', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_check_sayerlack_fabricado', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('reposicao_atualizar_params_nao_zera', 'function', 'public', 'atualizar_parametros_numericos_skus', ''),
  ('reposicao_param_limbo_watchdog', 'table', 'public', 'reposicao_param_limbo_log', ''),
  ('reposicao_param_limbo_watchdog', 'index', 'public', 'uq_reposicao_param_limbo_log_dia', 'reposicao_param_limbo_log'),
  ('reposicao_param_limbo_watchdog', 'function', 'public', 'reposicao_param_limbo_watchdog', ''),
  ('reposicao_param_limbo_watchdog', 'cron_job', 'cron', 'reposicao-param-limbo-watchdog', ''),
  ('reposicao_excluir_fabricado_04', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('data_health_check_sayerlack_mapeamento_gap', 'function', 'public', '_data_health_compute', ''),
  ('data_health_check_sayerlack_mapeamento_gap', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_check_sayerlack_mapeamento_gap', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('route_contact_log_escrita', 'function', 'public', 'registrar_contato_rota', ''),
  ('route_contact_log_escrita', 'function', 'public', 'desfazer_contato_rota', ''),
  ('tarefas_escalonamento_titulo_mensagem', 'function', 'public', 'tarefas_escalonamento_tick', ''),
  ('tarefas_fase2_bloco_a', 'table', 'public', 'tarefa_templates', ''),
  ('tarefas_fase2_bloco_a', 'index', 'public', 'idx_tt_ativo_assigned', 'tarefa_templates'),
  ('tarefas_fase2_bloco_b', 'index', 'public', 'uq_tarefa_template_assignee_dia', 'tarefas'),
  ('tarefas_fase2_bloco_c', 'rls_policy', 'public', 'tt_select', 'tarefa_templates'),
  ('tarefas_fase2_bloco_c', 'rls_policy', 'public', 'tt_insert', 'tarefa_templates'),
  ('tarefas_fase2_bloco_c', 'rls_policy', 'public', 'tt_update', 'tarefa_templates'),
  ('tarefas_fase2_bloco_c', 'rls_policy', 'public', 'tt_delete', 'tarefa_templates'),
  ('tarefas_fase2_bloco_d', 'function', 'public', 'tarefas_guard_comprovacao', ''),
  ('tarefas_fase2_bloco_d', 'function', 'public', 'concluir_com_comprovacao', ''),
  ('tarefas_fase2_bloco_d', 'function', 'public', 'auditar_tarefa', ''),
  ('tarefas_fase2_bloco_d', 'function', 'public', 'tarefas_materializar_recorrentes', ''),
  ('tarefas_fase2_bloco_d', 'trigger', 'public', 'trg_tarefas_guard_comprovacao', 'tarefas'),
  ('tarefas_fase2_bloco_d', 'cron_job', 'cron', 'tarefas-materializar-recorrentes', ''),
  ('tarefas_fase2_bloco_e', 'rls_policy', 'storage', 'tarefa_comprov_insert_own', 'objects'),
  ('tarefas_fase2_bloco_e', 'rls_policy', 'storage', 'tarefa_comprov_select_own_ou_gestor', 'objects'),
  ('reposicao_refresh_descricao_sku_parametros', 'function', 'public', 'atualizar_descricao_sku_parametros', ''),
  ('reposicao_refresh_descricao_sku_parametros', 'cron_job', 'cron', 'reposicao-refresh-descricao-diario', ''),
  ('loyalty_rls_hardening', 'function', 'public', 'resgatar_recompensa', ''),
  ('picking_bridge', 'index', 'public', 'uq_picking_tasks_sales_order', 'picking_tasks'),
  ('picking_bridge', 'index', 'public', 'idx_sales_orders_account_kpi', 'sales_orders'),
  ('picking_bridge', 'function', 'public', 'ensure_picking_task_for_sales_order', ''),
  ('picking_bridge', 'function', 'public', 'recalcular_picking_task', ''),
  ('picking_bridge', 'function', 'public', 'confirmar_item_picking', ''),
  ('picking_bridge', 'function', 'public', 'listar_pedidos_a_separar', ''),
  ('route_queue_snapshot', 'table', 'public', 'route_queue_snapshot', ''),
  ('route_queue_snapshot', 'index', 'public', 'idx_rqs_data', 'route_queue_snapshot'),
  ('route_queue_snapshot', 'index', 'public', 'idx_rqs_farmer_data', 'route_queue_snapshot'),
  ('route_queue_snapshot', 'rls_policy', 'public', 'rqs_staff_read', 'route_queue_snapshot'),
  ('route_queue_snapshot', 'rls_policy', 'public', 'rqs_self_write', 'route_queue_snapshot'),
  ('omie_products_tipo_produto_coluna', 'index', 'public', 'idx_omie_products_account_tipo_produto', 'omie_products'),
  ('omie_products_tipo_produto_coluna', 'function', 'public', 'preserve_tipo_produto', ''),
  ('omie_products_tipo_produto_coluna', 'trigger', 'public', 'trg_preserve_tipo_produto', 'omie_products'),
  ('whatsapp_sla', 'function', 'public', 'wa_is_stop_keyword', ''),
  ('whatsapp_sla', 'function', 'public', 'whatsapp_minutos_uteis', ''),
  ('whatsapp_sla', 'function', 'public', 'wa_owner_efetivo', ''),
  ('recebimento_efetivacao_ledger', 'table', 'public', 'nfe_efetivacao_tentativas', ''),
  ('recebimento_efetivacao_ledger', 'index', 'public', 'idx_nfe_efetivacao_tentativas_receb', 'nfe_efetivacao_tentativas'),
  ('recebimento_efetivacao_ledger', 'rls_policy', 'public', 'staff_select_nfe_efetivacao_tentativas', 'nfe_efetivacao_tentativas'),
  ('tipo_produto_consumidores', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('whatsapp_sla_digest', 'table', 'public', 'whatsapp_sla_digest_log', ''),
  ('whatsapp_sla_digest', 'function', 'public', 'whatsapp_sla_digest_tick', ''),
  ('whatsapp_sla_digest', 'cron_job', 'cron', 'whatsapp-sla-digest-diario', ''),
  ('envio_portal_claim_ids', 'function', 'public', 'envio_portal_claim_ids', ''),
  ('tipo_produto_vigia_cobertura', 'function', 'public', '_data_health_compute', ''),
  ('tipo_produto_vigia_cobertura', 'function', 'public', 'data_health_watchdog', ''),
  ('tipo_produto_vigia_cobertura', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('posthog_error_webhook', 'table', 'public', 'posthog_error_webhook_log', ''),
  ('posthog_error_webhook', 'function', 'public', 'enfileirar_erro_app', ''),
  ('reposicao_blindar_sku_sem_fornecedor', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('envio_portal_claim_ids_lista_positiva', 'function', 'public', 'envio_portal_claim_ids', ''),
  ('public_tool_history_rpc', 'function', 'public', 'get_public_tool_history', ''),
  ('embalagem_economica', 'table', 'public', 'sku_embalagem_equivalencia', ''),
  ('embalagem_economica', 'table', 'public', 'sku_preco_fornecedor_capturado', ''),
  ('embalagem_economica', 'index', 'public', 'uniq_sku_emb_equiv_ativo', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'index', 'public', 'idx_sku_emb_equiv_grupo', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'index', 'public', 'idx_sku_preco_cap_lookup', 'sku_preco_fornecedor_capturado'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_emb_equiv_select', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_emb_equiv_insert', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_emb_equiv_update', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_emb_equiv_delete', 'sku_embalagem_equivalencia'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_preco_cap_select', 'sku_preco_fornecedor_capturado'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_preco_cap_insert', 'sku_preco_fornecedor_capturado'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_preco_cap_update', 'sku_preco_fornecedor_capturado'),
  ('embalagem_economica', 'rls_policy', 'public', 'staff_sku_preco_cap_delete', 'sku_preco_fornecedor_capturado'),
  ('reposicao_minimo_forcado', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('param_auto_tabelas', 'table', 'public', 'reposicao_param_auto_run', ''),
  ('param_auto_tabelas', 'table', 'public', 'reposicao_param_auto_log', ''),
  ('param_auto_tabelas', 'table', 'public', 'reposicao_param_pin', ''),
  ('param_auto_tabelas', 'index', 'public', 'uq_param_auto_run_dia', 'reposicao_param_auto_run'),
  ('param_auto_tabelas', 'index', 'public', 'idx_param_auto_log_run', 'reposicao_param_auto_log'),
  ('param_auto_tabelas', 'index', 'public', 'idx_param_auto_log_sku', 'reposicao_param_auto_log'),
  ('param_auto_tabelas', 'rls_policy', 'public', 'param_auto_run_sel', 'reposicao_param_auto_run'),
  ('param_auto_tabelas', 'rls_policy', 'public', 'param_auto_log_sel', 'reposicao_param_auto_log'),
  ('param_auto_tabelas', 'rls_policy', 'public', 'param_auto_pin_sel', 'reposicao_param_pin'),
  ('tarefas_guard_old_requer', 'function', 'public', 'tarefas_guard_comprovacao', ''),
  ('param_auto_core', 'function', 'public', 'atualizar_parametros_numericos_skus', ''),
  ('tarefas_leitura_na_instancia', 'function', 'public', 'tarefas_materializar_recorrentes', ''),
  ('afiacao_os_status_sync', 'table', 'public', 'afiacao_os_sync_fila', ''),
  ('afiacao_os_status_sync', 'index', 'public', 'idx_afiacao_os_sync_fila_retry', 'afiacao_os_sync_fila'),
  ('afiacao_os_status_sync', 'function', 'public', 'mapear_status_etapa', ''),
  ('afiacao_os_status_sync', 'function', 'public', 'afiacao_os_enqueue', ''),
  ('afiacao_os_status_sync', 'function', 'public', 'afiacao_os_sync_kick', ''),
  ('afiacao_os_status_sync', 'trigger', 'public', 'trg_afiacao_os_enqueue', 'orders'),
  ('afiacao_os_status_sync', 'cron_job', 'cron', 'afiacao-os-sync', ''),
  ('afiacao_os_status_sync', 'rls_policy', 'public', 'staff_le_afiacao_os_sync_fila', 'afiacao_os_sync_fila'),
  ('iniciar_envio_portal_pre_claim', 'function', 'public', 'iniciar_envio_portal_pre_claim', ''),
  ('param_auto_wrapper_revert_cron', 'function', 'public', 'aplicar_parametros_automatico_diario', ''),
  ('param_auto_wrapper_revert_cron', 'function', 'public', 'reverter_parametro_auto', ''),
  ('param_auto_wrapper_revert_cron', 'function', 'public', 'reverter_run_auto', ''),
  ('param_auto_wrapper_revert_cron', 'function', 'public', 'despinar_parametro', ''),
  ('param_auto_wrapper_revert_cron', 'function', 'public', 'reposicao_param_auto_resumo_tick', ''),
  ('param_auto_wrapper_revert_cron', 'cron_job', 'cron', 'reposicao-param-auto-resumo', ''),
  ('param_auto_fusivel_calibracao', 'function', 'public', 'atualizar_parametros_numericos_skus', ''),
  ('reposicao_rpc_account_aware', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('detectar_skus_sem_grupo_exclui_04', 'function', 'public', 'detectar_skus_sem_grupo', ''),
  ('detectar_skus_sem_grupo_self_heal', 'function', 'public', 'detectar_skus_sem_grupo', ''),
  ('reposicao_qtde_inteira', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('reposicao_fix_aplicar_promocoes', 'function', 'public', 'aplicar_promocoes_no_ciclo', ''),
  ('reposicao_aplicar_promocoes_hardening', 'function', 'public', 'aplicar_promocoes_no_ciclo', ''),
  ('reposicao_preco_pedido_cmc', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('reposicao_preco_pedido_cmc_account', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('reposicao_qtde_inteira_persist', 'function', 'public', 'reposicao_persistir_qtde_inteira', ''),
  ('reposicao_promo_forward_buying_min', 'function', 'public', 'aplicar_promocoes_no_ciclo', ''),
  ('tool_spec_custom_option', 'function', 'public', 'adicionar_opcao_tool_spec', ''),
  ('data_health_check_familia_ausente', 'function', 'public', '_data_health_compute', ''),
  ('data_health_check_familia_ausente', 'function', 'public', 'data_health_watchdog', ''),
  ('data_health_check_familia_ausente', 'function', 'public', 'fin_sync_heartbeat', ''),
  ('reposicao_alerta_pedido_minimo', 'table', 'public', 'reposicao_alerta_pedido_minimo', ''),
  ('reposicao_alerta_pedido_minimo', 'index', 'public', 'reposicao_alerta_pedido_minimo_ativo', 'reposicao_alerta_pedido_minimo'),
  ('reposicao_alerta_pedido_minimo', 'function', 'public', 'reposicao_alerta_pedido_minimo_tick', ''),
  ('reposicao_alerta_pedido_minimo', 'cron_job', 'cron', 'reposicao-alerta-pedido-minimo', ''),
  ('tint_sync_promote', 'table', 'public', 'tint_staging_precos_base', ''),
  ('tint_sync_promote', 'table', 'public', 'tint_keys_snapshots', ''),
  ('tint_sync_promote', 'index', 'public', 'idx_tsp_precos_chave', 'tint_staging_precos_base'),
  ('tint_sync_promote', 'index', 'public', 'idx_tint_formulas_ativas', 'tint_formulas'),
  ('tint_sync_promote', 'function', 'public', 'tint_promote_sync_run', ''),
  ('tint_sync_promote', 'function', 'public', 'tint_ensure_corante_stub', ''),
  ('tint_sync_promote', 'function', 'public', 'tint_calc_preco_final', ''),
  ('tint_sync_promote', 'function', 'public', 'tint_recalc_preco_oficial', ''),
  ('tint_sync_promote', 'function', 'public', 'tint_apply_keys_snapshot', ''),
  ('reposicao_ciclo_intraday', 'function', 'public', 'gerar_pedidos_sugeridos_ciclo', ''),
  ('reposicao_ciclo_intraday', 'cron_job', 'cron', 'gerar-pedidos-intraday-oben', ''),
  ('reposicao_ciclo_intraday', 'cron_job', 'cron', 'omie-sync-estoque-intraday-oben', ''),
  ('reposicao_ciclo_intraday', 'cron_job', 'cron', 'omie-sync-estoque-diario', ''),
  ('reposicao_auto_aprovacao_piloto', 'table', 'public', 'reposicao_auto_aprovacao_log', ''),
  ('reposicao_auto_aprovacao_piloto', 'index', 'public', 'reposicao_auto_aprovacao_log_criado_em', 'reposicao_auto_aprovacao_log'),
  ('reposicao_auto_aprovacao_piloto', 'function', 'public', 'reposicao_pedido_auto_aprovavel', ''),
  ('reposicao_auto_aprovacao_piloto', 'function', 'public', 'reposicao_alerta_pedido_minimo_tick', ''),
  ('push_vendedora', 'table', 'public', 'push_subscriptions', ''),
  ('push_vendedora', 'index', 'public', 'idx_push_subscriptions_user', 'push_subscriptions'),
  ('push_vendedora', 'function', 'public', 'upsert_push_subscription', ''),
  ('push_vendedora', 'function', 'public', 'delete_push_subscription', ''),
  ('push_vendedora', 'function', 'public', '_push_enviar', ''),
  ('push_vendedora', 'function', 'public', 'push_whatsapp_inbound', ''),
  ('push_vendedora', 'function', 'public', 'push_tarefa_nova', ''),
  ('push_vendedora', 'function', 'public', 'push_sla_tick', ''),
  ('push_vendedora', 'trigger', 'public', 'trg_push_whatsapp_inbound', 'whatsapp_messages'),
  ('push_vendedora', 'trigger', 'public', 'trg_push_tarefa_nova', 'tarefas'),
  ('push_vendedora', 'cron_job', 'cron', 'push-sla-tick', ''),
  ('push_vendedora', 'rls_policy', 'public', 'push_subscriptions_own', 'push_subscriptions'),
  ('push_vendedora', 'rls_policy', 'public', 'push_subscriptions_service', 'push_subscriptions')
)
SELECT
  e.migration,
  e.kind,
  e.schema_name || '.' || e.object_name AS object,
  CASE
    WHEN e.kind = 'table' AND EXISTS (
      SELECT 1 FROM information_schema.tables t
      WHERE t.table_schema = e.schema_name AND t.table_name = e.object_name
    ) THEN '✅'
    WHEN e.kind = 'index' AND EXISTS (
      SELECT 1 FROM pg_indexes i
      WHERE i.schemaname = e.schema_name AND i.indexname = e.object_name
    ) THEN '✅'
    WHEN e.kind = 'function' AND EXISTS (
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = e.schema_name AND p.proname = e.object_name
    ) THEN '✅'
    WHEN e.kind = 'trigger' AND EXISTS (
      SELECT 1 FROM pg_trigger tr
      JOIN pg_class c ON c.oid = tr.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = e.schema_name AND tr.tgname = e.object_name AND c.relname = e.parent_name
    ) THEN '✅'
    WHEN e.kind = 'cron_job' AND EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = e.object_name
    ) THEN '✅'
    WHEN e.kind = 'enum_value' AND EXISTS (
      SELECT 1 FROM pg_enum en
      JOIN pg_type ty ON ty.oid = en.enumtypid
      JOIN pg_namespace n ON n.oid = ty.typnamespace
      WHERE n.nspname = e.schema_name AND ty.typname = e.parent_name AND en.enumlabel = e.object_name
    ) THEN '✅'
    WHEN e.kind = 'rls_policy' AND EXISTS (
      SELECT 1 FROM pg_policies p
      WHERE p.schemaname = e.schema_name AND p.tablename = e.parent_name AND p.policyname = e.object_name
    ) THEN '✅'
    ELSE '❌'
  END AS status,
  NULLIF(e.parent_name, '') AS parent
FROM expected_objects e
ORDER BY status DESC, e.migration, e.kind, e.object_name;

-- ========================================================================
-- FIM
-- ========================================================================
