-- ============================================================================
-- A — Sensor de NÍVEL + COMPOSIÇÃO + IDADE da fila de parâmetros de reposição
--
-- POR QUÊ (medido em prod 2026-08-26, narrativa em
-- docs/historico/fila-de-prontidao-e-sensor-de-derivada.md):
--   `reposicao_param_limbo_watchdog` só alerta se o limbo SALTAR +30 num dia, e o
--   ramo ELSE faz `dismissed_at = now()`. A série `reposicao_param_limbo_log` foi
--   146 (31/05) -> 119 (05/08) -> CONGELADA em 119 desde então, com o sensor VERDE
--   o tempo todo. Alerta de DERIVADA não responde "a fila está parada?".
--
-- ESTE OBJETO NÃO SUBSTITUI O WATCHDOG EXISTENTE. Ele continua servindo ao
-- propósito original (detectar regressão do cron que zerava config, fix #521).
-- Aqui entra o eixo que faltava: nível por ESTÁGIO + idade + estagnação.
--
-- Idempotente. Migration de nome custom => NÃO auto-aplica no Lovable (cole no
-- SQL Editor). Query de validação pós-apply no fim do arquivo.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) View de composição: 1 linha por SKU travado, com o ESTÁGIO em que parou
-- ─────────────────────────────────────────────────────────────────────────────
-- Regra de completude: um SKU está "travado" quando ativo e sem ponto_pedido OU
-- sem estoque_maximo. O estágio sai do `status_sugestao` da view de sugestões; se
-- o SKU nem aparece lá, o estágio é FORA_JANELA_DEMANDA (o universo da view exige
-- venda nos últimos 90d, via v_sku_classificacao_abc_xyz <- v_sku_demanda_estatisticas).
-- LEFT JOIN + COALESCE garantem que TODO travado receba exatamente um estágio.

CREATE OR REPLACE VIEW public.v_reposicao_param_fila
WITH (security_invoker = on) AS
SELECT
  sp.empresa,
  sp.sku_codigo_omie,
  sp.sku_descricao,
  sp.fornecedor_nome,
  sp.habilitado_reposicao_automatica  AS habilitado,
  COALESCE(sp.tipo_reposicao, 'automatica') AS tipo_reposicao,
  sp.parametro_cold_start,
  COALESCE(v.status_sugestao, 'FORA_JANELA_DEMANDA') AS estagio,
  v.num_ordens,
  v.fonte_leadtime,
  sp.ultima_atualizacao_calculo
  -- IDADE: deliberadamente AUSENTE aqui. `sku_parametros` não tem `criado_em` (medido
  -- 2026-08-26), e `ultima_atualizacao_calculo` é tocada a cada run mesmo quando NADA
  -- é escrito ⇒ usá-la como idade fabricaria um número (ausente != zero). A idade real
  -- passa a existir a partir de `reposicao_param_fila_log`: min(medido_em) por SKU-estágio.
  -- Superfície de medição nasce COM o sensor; antes dele não há idade a reportar.
FROM public.sku_parametros sp
LEFT JOIN public.v_sku_parametros_sugeridos v
  ON v.empresa = sp.empresa AND v.sku_codigo_omie = sp.sku_codigo_omie
WHERE sp.ativo IS TRUE
  AND (sp.ponto_pedido IS NULL OR sp.estoque_maximo IS NULL);

COMMENT ON VIEW public.v_reposicao_param_fila IS
  'Fila de prontidão de parâmetros de reposição: 1 linha por SKU ativo sem ponto_pedido/estoque_maximo, '
  'classificada pelo ESTÁGIO em que parou. FORA_JANELA_DEMANDA = nem entra em v_sku_parametros_sugeridos '
  '(universo exige venda em 90d). Base do sensor de nível/composição (docs/historico/fila-de-prontidao-e-sensor-de-derivada.md).';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) Log diário da composição (nível por estágio, não só o total)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reposicao_param_fila_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa      text        NOT NULL,
  medido_em    date        NOT NULL DEFAULT CURRENT_DATE,
  estagio      text        NOT NULL,
  total        integer     NOT NULL,
  habilitados  integer     NOT NULL,
  criado_em    timestamptz NOT NULL DEFAULT now()
);

-- Único por (empresa, dia, estágio) — mesmo padrão de uq_reposicao_param_limbo_log_dia,
-- que é ÍNDICE único (não constraint) e é o que o ON CONFLICT abaixo referencia.
CREATE UNIQUE INDEX IF NOT EXISTS uq_reposicao_param_fila_log_dia
  ON public.reposicao_param_fila_log (empresa, medido_em, estagio);

ALTER TABLE public.reposicao_param_fila_log ENABLE ROW LEVEL SECURITY;

-- Tabela nova SEMPRE com RLS (regra do repo). Leitura só para staff; escrita só
-- pela função SECURITY DEFINER / service_role (nenhuma policy de IUD para authenticated).
DROP POLICY IF EXISTS "staff le fila log" ON public.reposicao_param_fila_log;
CREATE POLICY "staff le fila log" ON public.reposicao_param_fila_log
  FOR SELECT TO authenticated
  USING ((SELECT private.cap_compras_ler((SELECT auth.uid()))));

COMMENT ON TABLE public.reposicao_param_fila_log IS
  'Snapshot diário da COMPOSIÇÃO da fila de parâmetros (nível por estágio). Complementa '
  'reposicao_param_limbo_log, que guarda só o total. Alimenta o alerta de ESTAGNAÇÃO.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) Config do sensor
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO public.company_config (key, value)
VALUES ('reposicao_param_fila_estagnacao_dias', '14')
ON CONFLICT (key) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4) Sensor: popula o log e alerta ESTAGNAÇÃO (nível sem queda há N dias)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.reposicao_param_fila_sensor(p_empresa text DEFAULT 'OBEN')
RETURNS TABLE(estagios integer, total integer, estagnado boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_dias      int;
  v_total     int := 0;
  v_estagios  int := 0;
  v_min_ant   int;
  v_dias_serie int;
  v_estagnado boolean := false;
  v_msg       text;
BEGIN
  -- SEM gate auth.role(): roda por pg_cron como postgres (auth.role() = NULL), igual
  -- às irmãs reposicao_cold_start_parametros / reposicao_param_limbo_watchdog.
  -- A proteção é o REVOKE/GRANT no fim do arquivo (anon/authenticated barrados).

  SELECT COALESCE((SELECT value::int FROM public.company_config
                   WHERE key = 'reposicao_param_fila_estagnacao_dias'), 14)
    INTO v_dias;

  -- (a) snapshot da composição do dia
  INSERT INTO public.reposicao_param_fila_log (empresa, medido_em, estagio, total, habilitados)
  SELECT f.empresa, CURRENT_DATE, f.estagio, count(*)::int,
         count(*) FILTER (WHERE f.habilitado)::int
  FROM public.v_reposicao_param_fila f
  WHERE f.empresa = p_empresa
  GROUP BY f.empresa, f.estagio
  ON CONFLICT (empresa, medido_em, estagio) DO UPDATE
    SET total = EXCLUDED.total, habilitados = EXCLUDED.habilitados, criado_em = now();

  -- Aliases OBRIGATÓRIOS: `total`/`estagios` são também colunas OUT do RETURNS TABLE, e
  -- plpgsql resolve a ambiguidade com erro em RUNTIME (late-bound) — não no CREATE.
  SELECT COALESCE(sum(l.total), 0)::int, count(*)::int
    INTO v_total, v_estagios
  FROM public.reposicao_param_fila_log l
  WHERE l.empresa = p_empresa AND l.medido_em = CURRENT_DATE;

  -- (b) ESTAGNAÇÃO: o nível não caiu em nenhum dia da janela.
  -- FAIL-CLOSED de leitura: sem série suficiente NÃO alerta e NÃO dismissa — ausência
  -- de dado não é "saudável" nem "estagnado". É exatamente o erro que este sensor
  -- existe para não repetir (o ELSE do watchdog antigo dismissa por ausência de piora).
  SELECT count(*)::int, min(limbo_count)::int
    INTO v_dias_serie, v_min_ant
  FROM public.reposicao_param_limbo_log
  WHERE empresa = p_empresa
    AND medido_em >= (CURRENT_DATE - v_dias)
    AND medido_em <  CURRENT_DATE;

  IF v_dias_serie >= v_dias THEN
    -- estagnado = o menor valor observado na janela não é MENOR que o de hoje,
    -- isto é: em N dias a fila não drenou nada.
    SELECT (v_min_ant IS NOT NULL AND v_min_ant <= lc.limbo_count)
      INTO v_estagnado
    FROM public.reposicao_param_limbo_log lc
    WHERE lc.empresa = p_empresa AND lc.medido_em = CURRENT_DATE;

    v_estagnado := COALESCE(v_estagnado, false);
  END IF;

  IF v_estagnado THEN
    v_msg := 'Fila de parâmetros de reposição PARADA: ' || v_total || ' SKUs sem ponto_pedido/estoque_maximo '
          || 'e o nível não caiu em ' || v_dias || ' dias. Composição por estágio em '
          || 'reposicao_param_fila_log / v_reposicao_param_fila. Sensor de nível — o watchdog de delta '
          || '(reposicao_param_limbo_watchdog) fica VERDE nesta situação por desenho.';

    INSERT INTO public.fin_alertas (company, tipo, severidade, mensagem, valor, threshold, contexto)
    VALUES (lower(p_empresa), 'reposicao_param_fila_estagnada', 'aviso', v_msg, v_total, v_dias,
            jsonb_build_object('total', v_total, 'estagios', v_estagios, 'janela_dias', v_dias))
    ON CONFLICT (company, tipo) WHERE dismissed_at IS NULL DO NOTHING;
  ELSE
    -- Só dismissa quando houve série suficiente para CONCLUIR que não está estagnado.
    -- Sem série, o alerta anterior (se houver) permanece — ausência de dado não resolve alerta.
    IF v_dias_serie >= v_dias THEN
      UPDATE public.fin_alertas SET dismissed_at = now()
      WHERE company = lower(p_empresa) AND tipo = 'reposicao_param_fila_estagnada'
        AND dismissed_at IS NULL;
    END IF;
  END IF;

  RETURN QUERY SELECT v_estagios, v_total, v_estagnado;
END;
$function$;

COMMENT ON FUNCTION public.reposicao_param_fila_sensor(text) IS
  'Sensor de NÍVEL/COMPOSIÇÃO/ESTAGNAÇÃO da fila de parâmetros. Complementa (não substitui) '
  'reposicao_param_limbo_watchdog, que é sensor de DERIVADA e fica verde com a fila congelada.';

-- Fechamento de superfície: a função é SECURITY DEFINER e escreve em fin_alertas.
-- REVOKE de PUBLIC não tira anon/authenticated (grant explícito) => revogar POR NOME.
REVOKE ALL ON FUNCTION public.reposicao_param_fila_sensor(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reposicao_param_fila_sensor(text) FROM anon;
REVOKE ALL ON FUNCTION public.reposicao_param_fila_sensor(text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.reposicao_param_fila_sensor(text) TO postgres, service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5) Agendamento — sem isto o sensor NUNCA roda (construir e não ligar é o erro
--    que já deixou um piloto 3 semanas parado com o circuit breaker em false)
-- ─────────────────────────────────────────────────────────────────────────────
-- 11:45 é DEPOIS do reposicao-param-limbo-watchdog (11:30), que popula
-- reposicao_param_limbo_log do dia — a série que o teste de estagnação lê.
-- Rodar antes deixaria o sensor sem a linha de hoje (fail-closed: não alerta),
-- o que seria um sensor permanentemente mudo. `cron.schedule` faz UPSERT por nome.
SELECT cron.schedule(
  'reposicao-param-fila-sensor',
  '45 11 * * *',
  $cron$ SELECT public.reposicao_param_fila_sensor('OBEN'); $cron$
);

-- ============================================================================
-- VALIDAÇÃO PÓS-APPLY (read-only — rode depois do Run)
-- ============================================================================
-- SELECT * FROM public.reposicao_param_fila_sensor('OBEN');
-- SELECT estagio, total, habilitados FROM public.reposicao_param_fila_log
--   WHERE empresa='OBEN' AND medido_em=CURRENT_DATE ORDER BY total DESC;
-- -- completude: todo SKU travado tem exatamente 1 estágio (esperado: iguais)
-- SELECT (SELECT count(*) FROM public.v_reposicao_param_fila WHERE empresa='OBEN') AS na_view,
--        (SELECT count(*) FROM public.sku_parametros
--          WHERE empresa='OBEN' AND ativo IS TRUE
--            AND (ponto_pedido IS NULL OR estoque_maximo IS NULL)) AS travados;
-- -- ACL fechada (esperado: f para anon/authenticated)
-- SELECT has_function_privilege('anon','public.reposicao_param_fila_sensor(text)','EXECUTE') AS anon,
--        has_function_privilege('authenticated','public.reposicao_param_fila_sensor(text)','EXECUTE') AS auth;
-- -- o cron existe e está ATIVO? (esperado: 1 linha, active = t)
-- SELECT jobid, jobname, schedule, active FROM cron.job WHERE jobname = 'reposicao-param-fila-sensor';
