// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createLensGuardedClient } from '@/lib/impersonation/lens-write-guard';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Write-guard da lente "ver como pessoa": bloqueia mutações enquanto a lente está
// ativa. Preservar este wrap (e o supabaseUnguarded abaixo) se este arquivo for
// regenerado pelo Lovable.
const rawClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: { storage: localStorage, persistSession: true, autoRefreshToken: true },
});

export const supabase = createLensGuardedClient(rawClient);

// Client SEM o write-guard da lente. ⚠️ USO RESTRITO: apenas o bookkeeping da PRÓPRIA
// lente (log_impersonation_start / end_impersonation no ImpersonationContext) — RPCs
// mutantes que SÃO do master e PRECISAM rodar mesmo com a lente ativa (senão o guard
// de RPC as bloquearia na entrada / troca de alvo / saída). NÃO usar para nenhuma
// outra escrita.
export const supabaseUnguarded = rawClient;