// Baseline do gate `hoje-utc` (src/lib/gates/hoje-utc.ts) — os sítios da classe que EXISTEM em 2026-10-01,
// cada um com o veredito lido no código e medido na varredura de 2026-09-30/10-01 (dois subagentes read-only,
// os de gravidade alta conferidos à mão): docs/historico/hoje-sp-typescript-e-data-ciclo.md. A lista só ENCOLHE —
// sítio novo reprova; entrada quitada que fica reprova; a contagem `n` é parte da identidade. `[fase …]` nos
// afetados é o dono: a PR de domínio que os conserta (financeiro, visitas, datas-omie-e-edges, reposicao, resto).
import type { SitioConhecido } from './hoje-utc';

export const CONHECIDOS: readonly SitioConhecido[] = [
  { arquivo: 'src/components/customer/CustomerBrief.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: 'recenciaLabel vs recencia.ts fatia timestamptz UTC — consertar os 2 lados' },
  { arquivo: 'src/components/des/checkinQualitativo/useCheckinQualitativo.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase visitas] data_avaliacao persistido' },
  { arquivo: 'src/components/des/historico/format.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'meia-noite local (só vale em UTC−3)' },
  { arquivo: 'src/components/financeiro/CockpitDrillDown.tsx', trecho: 'cutoff60.toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] drill-down aging crítico .lt(data_vencimento)' },
  { arquivo: 'src/components/financeiro/cashflow/ConfigCashflowDialog.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] data_ref default persistido' },
  { arquivo: 'src/components/financeiro/cashflow/EventosManager.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 2, veredito: 'afetado-alto',
    motivo: '[fase financeiro] fallback inicio persistido' },
  { arquivo: 'src/components/financeiro/cashflow/EventosOnboarding.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] inicio persistido 1 clique' },
  { arquivo: 'src/components/financeiro/endividamento/IndicadoresEndividamento.tsx', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'aritmética de calendário: ate12mISO parte de uma data YYYY-MM-DD ancorada em T00:00:00Z (UTC puro, sem relógio)' },
  { arquivo: 'src/components/notificacoes/useNotificacoes.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: 'buckets vs criado_em.slice UTC — consertar os 2 lados' },
  { arquivo: 'src/components/reposicao/SkuDetailSheet.tsx', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase reposicao] buckets do gráfico 90d' },
  { arquivo: 'src/components/reposicao/baixoGiro/DesovaMissaoDialog.tsx', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase reposicao] due_date da tarefa persistido' },
  { arquivo: 'src/components/reposicao/baixoGiro/useBaixoGiro.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase reposicao] diasSemVender +1 à noite' },
  { arquivo: 'src/components/reposicao/baixoGiro/useExcessoEstoque.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase reposicao] HOJE_ISO UTC em dias_sem_vender da fila de desova: +1 dia das 21h às 24h BRT (nada gravado)' },
  { arquivo: 'src/components/reposicao/cadeiaLogistica/TrocaParceiroDialog.tsx', trecho: 'new Date().toISOString().split("T")[0]', n: 2, veredito: 'afetado-alto',
    motivo: '[fase reposicao] default dataTroca persistido' },
  { arquivo: 'src/components/reposicao/cadeiaLogistica/useCadeiaLogistica.ts', trecho: 'new Date().toISOString().split("T")[0]', n: 1, veredito: 'afetado-alto',
    motivo: '[fase reposicao] valido_ate persistido' },
  { arquivo: 'src/components/reposicao/negociacaoParalela/helpers.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'meia-noite local último dia (só vale em UTC−3)' },
  { arquivo: 'src/components/reposicao/negociacaoParalela/useNegociacaoParalela.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase reposicao] data_geracao explícita UTC sobrescreve DEFAULT SP' },
  { arquivo: 'src/components/reposicao/negociacaoParalela/useNegociacaoParalela.ts', trecho: 'validoAte.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase reposicao] valido_ate setDate local + UTC' },
  { arquivo: 'src/components/reposicao/slaFornecedor/useSlaFornecedor.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase reposicao] nome do CSV' },
  { arquivo: 'src/hooks/useExportNaoVinculados.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase resto] só o nome do arquivo CSV baixado: das 21h às 24h BRT sai com a data de amanhã' },
  { arquivo: 'src/hooks/useFarmerPerformance.ts', trecho: 'periodStart.toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-alto',
    motivo: '[fase resto] period_start persistido farmer_performance_scores' },
  { arquivo: 'src/hooks/useFarmerPerformance.ts', trecho: 'periodEnd.toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-alto',
    motivo: '[fase resto] period_end persistido' },
  { arquivo: 'src/hooks/useFollowupsVisita.ts', trecho: 'new Date(Date.now() - JANELA_DIAS * 86_400_000).toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: '.gte(visit_date) — visit_date DEFAULT CURRENT_DATE (UTC); muda com o DEFAULT' },
  { arquivo: 'src/hooks/useKpisVisita.ts', trecho: 'new Date(Date.now() - janelaDias * 86_400_000).toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: '.gte(visit_date) janela 30d; muda com o DEFAULT' },
  { arquivo: 'src/hooks/useRoutePlanner.ts', trecho: 'new Date().toISOString().split(\'T\')[0]', n: 2, veredito: 'afetado-alto',
    motivo: '[fase visitas] .eq(scheduled_date) planner carrega amanhã' },
  { arquivo: 'src/lib/analytics-ledger.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: 'espelha v_dia UTC da RPC analytics_ledger_registrar (chave_dedup)' },
  { arquivo: 'src/lib/financeiro/aging-helpers.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'addDays: aritmética sobre YYYY-MM-DD ancorada em UTC (sem relógio); o hoje vem de quem chama' },
  { arquivo: 'src/lib/financeiro/cashflow-format.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'inicioSemana aritmética pura' },
  { arquivo: 'src/lib/financeiro/cashflow-format.ts', trecho: 'candidato.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'expansão de recorrência com Date.UTC: calendário puro, sem relógio' },
  { arquivo: 'src/lib/visitas/today.ts', trecho: 'new Date().toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-alto',
    motivo: '[fase visitas] hojeISO: AgendarVisitaDialog valor inicial e min → visitas_agendadas.scheduled_date' },
  { arquivo: 'src/lib/whatsapp/cesta-recompra.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'addDays: aritmética sobre YYYY-MM-DD ancorada em UTC (sem relógio); o hoje vem de quem chama' },
  { arquivo: 'src/lib/whatsapp/route-schedule.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'addDaysIso aritmética pura' },
  { arquivo: 'src/pages/AdminReposicaoAlertas.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'utc-consistente',
    motivo: 'decidido_em?.startsWith(hoje) prefixo UTC — consertar os 2 lados' },
  { arquivo: 'src/pages/AdminReposicaoBaixoGiro.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase reposicao] nome do CSV' },
  { arquivo: 'src/pages/FinanceiroDashboard.tsx', trecho: 'sixMonthsAgo.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'new Date(y,m-6,1) meia-noite LOCAL → 03:00Z mesmo dia (só vale em UTC−3)' },
  { arquivo: 'src/pages/FinanceiroDashboard.tsx', trecho: 'threeMonthsAhead.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'new Date(y,m-6,1) meia-noite LOCAL → 03:00Z mesmo dia (só vale em UTC−3)' },
  { arquivo: 'src/pages/RotaPropostas.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase visitas] workday → prazo da proposta WhatsApp' },
  { arquivo: 'src/pages/VendasFerramentas.tsx', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'latente',
    motivo: 'sales_print_jobs ausente (safeQuery 0)' },
  { arquivo: 'src/queries/usePropostaPreview.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase visitas] hojeIso → cesta de recompra (cutoff 180d, due) enviada por WhatsApp em RotaPropostas' },
  { arquivo: 'src/queries/usePropostaPreview.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'addDays aritmética pura ancorada T12:00Z' },
  { arquivo: 'supabase/functions/_shared/dia-operacional.ts', trecho: 'emBrt.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'helper que já desloca −3h' },
  { arquivo: 'supabase/functions/ai-ops-agent/index.ts', trecho: 'new Date().toISOString().split("T")[0]', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] rótulo notes' },
  { arquivo: 'supabase/functions/algorithm-a-audit/index.ts', trecho: 'periodStartDate.setDate(periodStartDate.getDate() - 365)', n: 1, veredito: 'falso-positivo',
    motivo: 'o instante é usado inteiro como filtro de created_at (timestamptz); o fatiamento é outro sítio (l.290)' },
  { arquivo: 'supabase/functions/algorithm-a-audit/index.ts', trecho: 'periodStartDate.getDate()', n: 1, veredito: 'falso-positivo',
    motivo: 'o instante é usado inteiro como filtro de created_at (timestamptz); o fatiamento é outro sítio (l.290)' },
  { arquivo: 'supabase/functions/algorithm-a-audit/index.ts', trecho: 'periodStartDate.toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] period_start margin_audit_log (botão noturno)' },
  { arquivo: 'supabase/functions/algorithm-a-audit/index.ts', trecho: 'now.toISOString().split(\'T\')[0]', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] period_end margin_audit_log (botão noturno)' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'nowBrt.getFullYear()', n: 1, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'nowBrt.getMonth()', n: 1, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'inicio.getFullYear()', n: 2, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'inicio.getMonth()', n: 2, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'fim.getFullYear()', n: 1, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/carteira-positivacao-snapshot/index.ts', trecho: 'fim.getMonth()', n: 1, veredito: 'falso-positivo',
    motivo: 'nowBrt já é o relógio de SP (toLocaleString com timeZone); inicio/fim são calendário puro derivado dele' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'd.setDate(d.getDate() + 1)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] diasUteisFromHoje → dDtPrevisao IncluirPedCompra parte de D+1' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'd.getDate()', n: 2, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] diasUteisFromHoje → dDtPrevisao IncluirPedCompra parte de D+1' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'd.getDay()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] diasUteisFromHoje → dDtPrevisao IncluirPedCompra parte de D+1' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] diasUteisFromHoje → dDtPrevisao IncluirPedCompra parte de D+1' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] diasUteisFromHoje → dDtPrevisao IncluirPedCompra parte de D+1' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'new Date() .toISOString() .slice(2, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] o yymmdd do número do pedido Omie sai com o dia UTC (a idempotência é o cCodIntPed)' },
  { arquivo: 'supabase/functions/disparar-pedidos-aprovados/index.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 1, veredito: 'latente',
    motivo: 'dataCiclo do lote só no cron 13:00 UTC (família data_ciclo)' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: '_hojeTtm.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] _cutoffMesIdx noite do último dia do mês' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: '_hojeTtm.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] _cutoffMesIdx noite do último dia do mês' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 4, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] hojeIso calibrarCurvas; persiste só cron 10:00 UTC' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'new Date(agora - 12 * 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] cutoff 12m taxas históricas' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'd.toISOString().slice(0, 10)', n: 2, veredito: 'falso-positivo',
    motivo: 'inicioSemanaUTC aritmética' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'candidato.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'expandirRecorrenteDeno Date.UTC' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'hoje.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] rótulo mes projeção' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'hoje.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] rótulo mes projeção' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] rótulo mes projeção' },
  { arquivo: 'supabase/functions/fin-cashflow-engine/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] rótulo mes projeção' },
  { arquivo: 'supabase/functions/fin-funding/index.ts', trecho: 'hoje.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] .gt(data_vencimento) lista antecipável' },
  { arquivo: 'supabase/functions/fin-suggest-mapping/index.ts', trecho: 'new Date(ano, mes, 0).toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'new Date(ano,mes,0) calendário puro (Deno UTC)' },
  { arquivo: 'supabase/functions/fin-valor-cockpit/index.ts', trecho: 'now.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela TTM' },
  { arquivo: 'supabase/functions/fin-valor-cockpit/index.ts', trecho: 'new Date(now.getTime() - 365 * 86400000).toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela TTM (início)' },
  { arquivo: 'supabase/functions/fin-valor-cockpit/index.ts', trecho: 'new Date(now.getTime() - (365 + 90) * 86400000).toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela TTM prefetch' },
  { arquivo: 'supabase/functions/monthly-report/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] formatDate timestamptz exibe D+1' },
  { arquivo: 'supabase/functions/monthly-report/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] formatDate timestamptz exibe D+1' },
  { arquivo: 'supabase/functions/monthly-report/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] formatDate timestamptz exibe D+1' },
  { arquivo: 'supabase/functions/monthly-report/index.ts', trecho: 'now.getMonth()', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] monthYear e-mail' },
  { arquivo: 'supabase/functions/monthly-report/index.ts', trecho: 'now.getFullYear()', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] monthYear e-mail' },
  { arquivo: 'supabase/functions/omie-analytics-sync/index.ts', trecho: 'new Date().toLocaleDateString("pt-BR")', n: 2, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDataPosicao toLocaleDateString sem TZ; crons */30 noite' },
  { arquivo: 'supabase/functions/omie-desconto-backfill/index.ts', trecho: 'de.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] borda janela manual' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'hoje.getDate()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] ListarExtrato período D+1' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'hoje.getMonth()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] ListarExtrato período D+1' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'hoje.getFullYear()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] ListarExtrato período D+1' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'new Date().toISOString().split("T")[0]', n: 1, veredito: 'afetado-alto',
    motivo: '[fase financeiro] saldo_data D+1 com saldo pedido ao Omie p/ D+1' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'falso-positivo',
    motivo: 'formatOmieDate: helper puro — formata o Date que recebe; o dia errado vem de quem passa o instante (sítios acima)' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'falso-positivo',
    motivo: 'formatOmieDate: helper puro — formata o Date que recebe; o dia errado vem de quem passa o instante (sítios acima)' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'falso-positivo',
    motivo: 'formatOmieDate: helper puro — formata o Date que recebe; o dia errado vem de quem passa o instante (sítios acima)' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'new Date().setMonth(new Date().getMonth() - 6)', n: 3, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela busca' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'new Date().getMonth()', n: 6, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela busca' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'new Date().setMonth(new Date().getMonth() - 3)', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] janela busca' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'nowDre.getFullYear()', n: 1, veredito: 'latente',
    motivo: 'defaultAno/defaultMes; front sempre passa' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'nowDre.getMonth()', n: 1, veredito: 'latente',
    motivo: 'defaultAno/defaultMes; front sempre passa' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: 'new Date().getFullYear()', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] calcular_dre_year mês seguinte zerado' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: '_hoje.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] debug_raw: o _hojeBR mandado ao Omie no modo debug' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: '_hoje.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] debug_raw: o _hojeBR mandado ao Omie no modo debug' },
  { arquivo: 'supabase/functions/omie-financeiro/index.ts', trecho: '_hoje.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase financeiro] debug_raw: o _hojeBR mandado ao Omie no modo debug' },
  { arquivo: 'supabase/functions/omie-nfe-recebimento-sync/index.ts', trecho: 'thirtyDaysAgo.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] dtDe 30d (o dia mandado ao Omie)' },
  { arquivo: 'supabase/functions/omie-nfe-recebimento-sync/index.ts', trecho: 'thirtyDaysAgo.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] dtDe 30d (o dia mandado ao Omie)' },
  { arquivo: 'supabase/functions/omie-nfe-recebimento-sync/index.ts', trecho: 'thirtyDaysAgo.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] dtDe 30d (o dia mandado ao Omie)' },
  { arquivo: 'supabase/functions/omie-sonda-recebimento/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'latente',
    motivo: 'sonda diagnóstica: sem cron, sem front e sem gravação — nunca roda em produção sozinha' },
  { arquivo: 'supabase/functions/omie-sonda-recebimento/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'latente',
    motivo: 'sonda diagnóstica: sem cron, sem front e sem gravação — nunca roda em produção sozinha' },
  { arquivo: 'supabase/functions/omie-sonda-recebimento/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'latente',
    motivo: 'sonda diagnóstica: sem cron, sem front e sem gravação — nunca roda em produção sozinha' },
  { arquivo: 'supabase/functions/omie-sonda-recebimento/index.ts', trecho: 'x.setDate(x.getDate() + dias)', n: 1, veredito: 'latente',
    motivo: 'sonda diagnóstica: sem cron, sem front e sem gravação — nunca roda em produção sozinha' },
  { arquivo: 'supabase/functions/omie-sonda-recebimento/index.ts', trecho: 'x.getDate()', n: 1, veredito: 'latente',
    motivo: 'sonda diagnóstica: sem cron, sem front e sem gravação — nunca roda em produção sozinha' },
  { arquivo: 'supabase/functions/omie-sync-ctes-recebidos/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela ListarRecebimentos' },
  { arquivo: 'supabase/functions/omie-sync-ctes-recebidos/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela ListarRecebimentos' },
  { arquivo: 'supabase/functions/omie-sync-ctes-recebidos/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela ListarRecebimentos' },
  { arquivo: 'supabase/functions/omie-sync-nfes-recebidas/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela busca' },
  { arquivo: 'supabase/functions/omie-sync-nfes-recebidas/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela busca' },
  { arquivo: 'supabase/functions/omie-sync-nfes-recebidas/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela busca' },
  { arquivo: 'supabase/functions/omie-sync-nfes-recebidas/index.ts', trecho: 'inicio.setDate(hoje.getDate() - dias)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] a janela de busca do Omie parte do dia UTC (cron noturno via omie-cron-diario)' },
  { arquivo: 'supabase/functions/omie-sync-nfes-recebidas/index.ts', trecho: 'hoje.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] a janela de busca do Omie parte do dia UTC (cron noturno via omie-cron-diario)' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela PesquisarPedCompra' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela PesquisarPedCompra' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela PesquisarPedCompra' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'inicio.setDate(hoje.getDate() - passadoDias)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] a janela do PesquisarPedCompra parte do dia UTC; summary.janela_de/ate persistida deslocada' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'hoje.getDate()', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] a janela do PesquisarPedCompra parte do dia UTC; summary.janela_de/ate persistida deslocada' },
  { arquivo: 'supabase/functions/omie-sync-pedidos-compra/index.ts', trecho: 'fimJanela.setDate(hoje.getDate() + futuroDias)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] a janela do PesquisarPedCompra parte do dia UTC; summary.janela_de/ate persistida deslocada' },
  { arquivo: 'supabase/functions/omie-sync-vendas-items/index.ts', trecho: 'inicio.toISOString().slice(0, 10)', n: 1, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] janela 3d dedupe data_emissao; cron 15 */2 UTC roda 21:15/23:15 BRT' },
  { arquivo: 'supabase/functions/omie-sync/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDtVenc parcelas OS enviado ao Omie' },
  { arquivo: 'supabase/functions/omie-sync/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDtVenc parcelas OS enviado ao Omie' },
  { arquivo: 'supabase/functions/omie-sync/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDtVenc parcelas OS enviado ao Omie' },
  { arquivo: 'supabase/functions/omie-sync/index.ts', trecho: 'r.setDate(r.getDate() + days)', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDtVenc parcelas OS enviado ao Omie' },
  { arquivo: 'supabase/functions/omie-sync/index.ts', trecho: 'r.getDate()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDtVenc parcelas OS enviado ao Omie' },
  { arquivo: 'supabase/functions/omie-vendas-sync/index.ts', trecho: 'new Date().toLocaleDateString("pt-BR")', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] dDataPosicao syncEstoque toLocaleDateString sem TZ' },
  { arquivo: 'supabase/functions/omie-vendas-sync/index.ts', trecho: 'new Date().toISOString().split("T")[0]', n: 3, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] data_previsao IncluirPedido D+1; vira order_date_kpi sem dInc' },
  { arquivo: 'supabase/functions/process-recurring-orders/index.ts', trecho: 'new Date().toISOString().split(\'T\')[0]', n: 1, veredito: 'latente',
    motivo: 'cron 07:00 UTC; sem botão' },
  { arquivo: 'supabase/functions/process-recurring-orders/index.ts', trecho: 'nextDate.setDate(nextDate.getDate() + schedule.frequency_days)', n: 1, veredito: 'falso-positivo',
    motivo: 'next_order_date: aritmética de calendário sobre a data salva (date), sem o relógio' },
  { arquivo: 'supabase/functions/process-recurring-orders/index.ts', trecho: 'nextDate.getDate()', n: 1, veredito: 'falso-positivo',
    motivo: 'next_order_date: aritmética de calendário sobre a data salva (date), sem o relógio' },
  { arquivo: 'supabase/functions/process-recurring-orders/index.ts', trecho: 'nextDate.toISOString().split(\'T\')[0]', n: 1, veredito: 'falso-positivo',
    motivo: 'next_order_date: aritmética de calendário sobre a data salva (date), sem o relógio' },
  { arquivo: 'supabase/functions/promocao-extrair-via-vision/index.ts', trecho: 'new Date().toISOString().slice(0, 10)', n: 2, veredito: 'afetado-baixo',
    motivo: '[fase datas-omie-e-edges] data_inicio/fim placeholder em rascunho' },
  { arquivo: 'supabase/functions/promocao-extrair-via-vision/vision-helpers.ts', trecho: 'd.toISOString().slice(0, 10)', n: 1, veredito: 'falso-positivo',
    motivo: 'dataValida: round-trip de validação de uma string de data (sem relógio)' },
  { arquivo: 'supabase/functions/sync-reprocess/index.ts', trecho: 'd.getDate()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] formatOmieDate: dDataPosicao D+1 toda noite (cron 21:15/23:15/23:30 BRT) + janela ±1' },
  { arquivo: 'supabase/functions/sync-reprocess/index.ts', trecho: 'd.getMonth()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] formatOmieDate: dDataPosicao D+1 toda noite (cron 21:15/23:15/23:30 BRT) + janela ±1' },
  { arquivo: 'supabase/functions/sync-reprocess/index.ts', trecho: 'd.getFullYear()', n: 1, veredito: 'afetado-alto',
    motivo: '[fase datas-omie-e-edges] formatOmieDate: dDataPosicao D+1 toda noite (cron 21:15/23:15/23:30 BRT) + janela ±1' },
  { arquivo: 'supabase/functions/visit-score-recalc-batch/index.ts', trecho: 'cutoff.slice(0, 10)', n: 1, veredito: 'latente',
    motivo: '[fase datas-omie-e-edges] .gte(visit_date) janela 30d; só cron 07:00 UTC = 04:00 BRT (o dia UTC = o de SP nessa hora), 0 chamadas do front' },
];
